### ISSUE TITLE
librtsp/source/rtsp-reason.c:1:10: fatal error: 'http-reason.h' file not found

### ISSUE THREAD

**Issue by since2014** [ireader/media-server#10]
source/rtsp-reason.c:1:10: fatal error: 'http-reason.h' file not found
#include "http-reason.h"
         ^~~~~~~~~~~~~~~
1 error generated.
make[1]: *** [source/rtsp-reason.o] Error 1
make: *** [all] Error 2

./librtsp/source/rtsp-reason.c:31:		return http_reason_phrase(code);

**Comment by ireader** [comment]
The rtsp project dependence: https://github.com/ireader/sdk

add include header path: sdk/include and sdk/libhttp/include

If you use aio socket, add sdk/libaio/include too

link with sdk/source/md5.c, sdk/source/base64.c

**Comment by santhku** [comment]
How to add this paths
"add include header path: sdk/include and sdk/libhttp/include"

**Comment by ireader** [comment]
git clone https://github.com/ireader/sdk
git clone https://github.com/ireader/media-server
cd media-server && make
