### ISSUE TITLE
librtsp/source/client/rtsp-client.c:100: rtsp_client_input: Assertion `r <= 1' failed.

### ISSUE THREAD

**Issue by chenbd** [ireader/media-server#101]
Hello,
I found a assert when testing rtsp client using vlc(2.2.2 Ubuntu 16.04) as a rtsp server.
the value 'r' is 2(INPUT_HEADER) when assert happened.

**Comment by ireader** [comment]
It trigger assert when need read more data.

change: assert(r <= 1) ==> assert(r <= 2);

**Comment by chenbd** [comment]
> It trigger assert when need read more data.
> 
> change: assert(r <= 1) ==> assert(r <= 2);

should it be fixed with a PR?

**Comment by ireader** [comment]
> > It trigger assert when need read more data.
> > change: assert(r <= 1) ==> assert(r <= 2);
> 
> should it be fixed with a PR?

Welcome!
