### ISSUE TITLE
rtsp: suddenly  'RTCP_MSG_BYE' from rtcp channel and playback stopped

### ISSUE THREAD

**Issue by chenbd** [ireader/media-server#102]
Hello,

I'm testing rtsp client function using vlc(2.2.2 ubuntu 16.04) streaming server from a mp4 file.
the playback works well for about 1 miniute, and suddenly RTCP_MSG_BYE received. and the playback stopped.
I can see the log "finished"  which from 'rtp_on_rtcp' twice from terminal.

Not sure about the reason, does this because we are missing some report which vlc need?

**Comment by ireader** [comment]
check rtsp client send rtcp RR interval.

**Comment by chenbd** [comment]
> check rtsp client send rtcp RR interval.

Thanks for your quick response.

After looks ino [vlc](https://github.com/videolan/vlc/blob/6e17543d418a398129335b95f80329c80fe2e20b/modules/stream_out/rtsp.c#L393), the server seems having time out.
After calling rtsp_client_get_parameter as keep-alive, the playback works well now.
is this is what your 'rtsp client send rtcp RR interval' means?

**Comment by ireader** [comment]
rtsp keep-alive methods：
1. rtp rtcp
2. rtsp GET_PARAMETER
3. rtsp PLAY

VLC maybe use GET_PARAMETER to keep-alive.

**Comment by ireader** [comment]
fix rtp_receiver RTCP report send error.

commit id: ab83220c56b113217d80b7db07a93ca8304065de
