### ISSUE TITLE
librtmp使用咨询

### ISSUE THREAD

**Issue by hctym1995** [ireader/media-server#104]
我想做的事情是使用librtmp将h264视频数据发送给rtmp服务器,操作系统为windwos
我单独编译了librtmp.lib静态库,并加载到了项目中
我的接口调用顺序是这样的:
rtmp_client_t* rtmp = rtmp_client_create("live", "hello", "rtmp://192.168.6.1:19351/live", NULL, &handler);
int r = rtmp_client_start(rtmp, 0);
rtmp_client_push_video(rtmp, data, len, dts);
请问这样的使用方法是否合理?

**Comment by ireader** [comment]
在rtmp_client_push_video之前需要先完成rtmp握手，请参考librtmp/test/rtmp-publish-test.cpp文件.
```
while (4 != rtmp_client_getstate(rtmp) && (r = socket_recv(socket, packet, sizeof(packet), 0)) > 0)
{
		r = rtmp_client_input(rtmp, packet, r);
}
```
