### ISSUE TITLE
RTSP支持L16音频问题？

### ISSUE THREAD

**Issue by rmokerone** [ireader/media-server#106]
Chen您好，我修改了pcm-file-source.cpp文件，用来支持16位的LPCM音频数据。

修改后的程序代码如下：

https://gist.github.com/rmokerone/3d78cc62563f933c31c1eb05004a1894

但是遇到了一个很奇怪的问题，ffplay播放rtsp流的时候，声音都是噪音。

但是使用``ffmpeg -i rtsp://10.10.10.34:8554/live/16k.pcm -acodec copy -f s16le rtsple.pcm``取流后保存成``rtsple.pcm``文件。

再使用``ffplay -ar 16000 -ac 1 -f s16le -i rtsple.pcm``播放，声音正常。

附上在rtsp服务端上使用的16k_be.pcm文件。

您能帮我分析下是什么原因吗？不胜感激

[16k_s16be.pcm.zip](https://github.com/ireader/media-server/files/5083506/16k_s16be.pcm.zip)

**Comment by ireader** [comment]
![image](https://user-images.githubusercontent.com/1535445/90395417-1b56ab80-e0c7-11ea-978e-6af80c73f8b6.png)

L16 对应标准RTP Payload 10/11，你指定的Payload是97，实际是解析不出来的。

另外L16对应的标准采样率是44100。

**Comment by rmokerone** [comment]
![image](https://user-images.githubusercontent.com/3683271/90466213-cc9b2700-e143-11ea-99ca-7cd20f4f9f0b.png)
我看到这个动态的L16格式，好像能够支持16000的采样率，请问这个可不可以用？

**Comment by ireader** [comment]
服务端肯定没问题，主要是ffmpeg好像不支持。

**Comment by rmokerone** [comment]
确实是这个问题，我把采样率换成44100的s16be文件就能够顺利播放了。非常感谢~
