### ISSUE TITLE
libsip的使用

### ISSUE THREAD

**Issue by kqbi** [ireader/media-server#108]
![图片](https://user-images.githubusercontent.com/40823194/91783804-d8064c00-ec33-11ea-9569-1bb1cf3306e1.png)
收到注册后调用sip_agent_set_rport(msg, ep.address().to_string().c_str(), ep.port());添加接收ip和port后调用
sip_agent_input(_dum._agent, msg);，然后
···
static int
    sip_uas_onregister(void *param, const struct sip_message_t *req, struct sip_uas_transaction_t *t, const char *user,
                       const char *location, int expires) {
        return sip_uas_reply(t, 200, NULL, 0);
    }
···
响应注册后回复：
![图片](https://user-images.githubusercontent.com/40823194/91783968-3f240080-ec34-11ea-83c0-4f2d016a838a.png)
就变成这样了，是什么原因怎么解决

**Comment by aliveyun** [comment]
在sip_uas_transport_send  那里要修改一下代码。
	int r = socket_addr_from(&addr, &addrlen, cstrvalid(received) ? std::string(received->p, received->n).c_str() : uri->host, rport > 0 ? rport : (uri->port ? uri->port : SIP_PORT));

> 取到ip[](url)

**Comment by aliveyun** [comment]
> ![图片](https://user-images.githubusercontent.com/40823194/91783804-d8064c00-ec33-11ea-9569-1bb1cf3306e1.png)
> 收到注册后调用sip_agent_set_rport(msg, ep.address().to_string().c_str(), ep.port());添加接收ip和port后调用
> sip_agent_input(_dum._agent, msg);，然后
> ···
> static int
> sip_uas_onregister(void *param, const struct sip_message_t *req, struct sip_uas_transaction_t *t, const char *user,
> const char *location, int expires) {
> return sip_uas_reply(t, 200, NULL, 0);
> }
> ···
> 响应注册后回复：
> ![图片](https://user-images.githubusercontent.com/40823194/91783968-3f240080-ec34-11ea-83c0-4f2d016a838a.png)
> 就变成这样了，是什么原因怎么解决

**Comment by aliveyun** [comment]
> ![图片](https://user-images.githubusercontent.com/40823194/91783804-d8064c00-ec33-11ea-9569-1bb1cf3306e1.png)
> 收到注册后调用sip_agent_set_rport(msg, ep.address().to_string().c_str(), ep.port());添加接收ip和port后调用
> sip_agent_input(_dum._agent, msg);，然后
> ···
> static int
> sip_uas_onregister(void *param, const struct sip_message_t *req, struct sip_uas_transaction_t *t, const char *user,
> const char *location, int expires) {
> return sip_uas_reply(t, 200, NULL, 0);
> }
> ···
> 响应注册后回复：
> ![图片](https://user-images.githubusercontent.com/40823194/91783968-3f240080-ec34-11ea-83c0-4f2d016a838a.png)
> 就变成这样了，是什么原因怎么解决

在static int sip_uas_transport_send(void* param, const struct cstring_t* /*protocol*/, const struct cstring_t* peer, const struct cstring_t* received, int rport, const void* data, int bytes)
{
修改一下 int r = socket_addr_from(&addr, &addrlen, cstrvalid(received) ? std::string(received->p, received->n).c_str() : uri->host, rport > 0 ? rport : (uri->port ? uri->port : SIP_PORT));
	if (0 != r)
把IP填上

**Comment by kqbi** [comment]
我是这个static int sip_uas_transport_send(void* param, const struct cstring_t* /protocol/, const struct cstring_t* peer, const struct cstring_t* received, int rport, const void* data, int bytes)函数的入参data数据里的Contact字段不对，并不是没有获取到远端的ip和端口，我已经能发送注册回复了，只是回复数据里的Contact不对而已

**Comment by aliveyun** [comment]
> 我是这个static int sip_uas_transport_send(void* param, const struct cstring_t* /protocol/, const struct cstring_t* peer, const struct cstring_t* received, int rport, const void* data, int bytes)函数的入参data数据里的Contact字段不对，并不是没有获取到远端的ip和端口，我已经能发送注册回复了，只是回复数据里的Contact不对而已

你修改一下  看看  我之前遇到就是这个问题

**Comment by kqbi** [comment]
我调试发现是这里的问题在这个sip_message_set_reply_default_contact函数里
![图片](https://user-images.githubusercontent.com/40823194/91790605-cb89ef80-ec43-11ea-854f-0999cb138416.png)
使用了这个函数sip_agent_input后via->received就有值了，然后会执行sip_message_copy2，然后contact就错了，
我如果不加sip_agent_input这个函数，注册回复就是这样的
![图片](https://user-images.githubusercontent.com/40823194/91790887-5b2f9e00-ec44-11ea-8653-c59c264a3e72.png)

**Comment by aliveyun** [comment]
> 我调试发现是这里的问题在这个sip_message_set_reply_default_contact函数里
> ![图片](https://user-images.githubusercontent.com/40823194/91790605-cb89ef80-ec43-11ea-854f-0999cb138416.png)
> 使用了这个函数sip_agent_input后via->received就有值了，然后会执行sip_message_copy2，然后contact就错了，
> 我如果不加sip_agent_input这个函数，注册回复就是这样的
> ![图片](https://user-images.githubusercontent.com/40823194/91790887-5b2f9e00-ec44-11ea-8653-c59c264a3e72.png)

socket_addr_from(&addr, &addrlen, cstrvalid(received) ? std::string(received->p, received->n).c_str() :
就是IP地址错了啊  ，你修改就可以啦

**Comment by ireader** [comment]
> ![图片](https://user-images.githubusercontent.com/40823194/91783804-d8064c00-ec33-11ea-9569-1bb1cf3306e1.png)
> 收到注册后调用sip_agent_set_rport(msg, ep.address().to_string().c_str(), ep.port());添加接收ip和port后调用
> sip_agent_input(_dum._agent, msg);，然后
> ···
> static int
> sip_uas_onregister(void *param, const struct sip_message_t *req, struct sip_uas_transaction_t *t, const char *user,
> const char *location, int expires) {
> return sip_uas_reply(t, 200, NULL, 0);
> }
> ···
> 响应注册后回复：
> ![图片](https://user-images.githubusercontent.com/40823194/91783968-3f240080-ec34-11ea-83c0-4f2d016a838a.png)
> 就变成这样了，是什么原因怎么解决

![image](https://user-images.githubusercontent.com/1535445/91797484-414a8700-ec55-11ea-8c3d-f228a17ba0e7.png)

是个bug，sip_contact_clone后没有更新contact内部buffer指针，导致sip_message_copy2重复写内存，最终导致问题。
修改如图所示在sip_message_set_reply_default_contact函数中增加红色框内代码。

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/91798333-401a5980-ec57-11ea-99fe-251d0494eb97.png)
加了变成这样了，不知道对不对，REGISTER给的Contact是<sip:user@ip:port>这样的

**Comment by ireader** [comment]
// update contact host by via.received
//    via = sip_vias_get(&reply->vias, 0);
//    if (via && cstrvalid(&via->received))
//        sip_message_copy2(reply, &contact.uri.host, &via->received);

这几行代码有问题，注释掉。

**Comment by kqbi** [comment]
OK
