### ISSUE TITLE
 libsip的使用:onmessage获取的payload为空

### ISSUE THREAD

**Issue by kqbi** [ireader/media-server#109]
使用sip连接上级后，上级发送携带payload的信息过来，然后调用sip_agent_input函数，调用的时候payload是有值的，在onmessage中
![图片](https://user-images.githubusercontent.com/40823194/93282680-8815b080-f801-11ea-9d33-fa3d4bdc8af2.png)
![图片](https://user-images.githubusercontent.com/40823194/93282715-9d8ada80-f801-11ea-8114-705c9405aafc.png)
size有值，payload是空。调试发现在sip_uas_input开始payload是有值的
![图片](https://user-images.githubusercontent.com/40823194/93282842-da56d180-f801-11ea-8f29-7db4010e106b.png)
从sip_uas_transaction_create函数出来后payload就是空了
![图片](https://user-images.githubusercontent.com/40823194/93282963-1e49d680-f802-11ea-91e6-40e2a9b9151d.png)

调试发现在刚进sip_uas_transaction_create这个函数payload也是有值的
![图片](https://user-images.githubusercontent.com/40823194/93283230-b2b43900-f802-11ea-8893-eecd2b08da33.png)
但是执行完这里后t->reply = sip_message_create(SIP_MESSAGE_REPLY);     payload就空了
![图片](https://user-images.githubusercontent.com/40823194/93283319-e727f500-f802-11ea-9337-268386f1ddbb.png)
![图片](https://user-images.githubusercontent.com/40823194/93283485-366e2580-f803-11ea-9ea9-582430590390.png)

不知道是什么原因造成的

**Comment by ireader** [comment]
sip message对应的http parser调用http_parser_destroy了吗？  payload指向的是http parser内部的内存，在使用过程中不能释放.

**Comment by kqbi** [comment]
‘’‘
struct sip_message_t *Req2sip(const char *req) {
        struct sip_message_t *msg;
        msg = sip_message_create(SIP_MESSAGE_REQUEST);

        size_t n = strlen(req);
        http_parser_t *parser = http_parser_create(HTTP_PARSER_REQUEST, NULL, NULL);
        assert(0 == http_parser_input(parser, req, &n) && 0 == n);
        assert(0 == sip_message_load(msg, parser));
        http_parser_destroy(parser);
        return msg;
    }
’‘’
我是socket收到数据后调用了这个函数转成sip message，然后调用的sip_agent_input函数

**Comment by ireader** [comment]
payload数据长度不定，所以内存管理是有外部处理的
uac端使用sip_uac_send函数中的data、bytes；
uas端借助了http_parser内部的内存，需要保证http_parser_input调用后才能http_parser_destroy；

![image](https://user-images.githubusercontent.com/1535445/93330689-bde28580-f851-11ea-8da6-3fb99ea865b8.png)
一般使用模式如上。

**Comment by kqbi** [comment]
好的，我本来是想封装成这样的函数用的，看来是不行了

struct sip_message_t * Data2sip(const char *data) {
			int dataType = (0 == strncasecmp("SIP", (char *)data, 3)) ? SIP_MESSAGE_REPLY : SIP_MESSAGE_REQUEST;
			if (!dataType) {
				return Req2sip(data);
			}
			else {
				return Reply2sip(data);
			}
    }

    struct sip_message_t *Req2sip(const char *req) {
        struct sip_message_t *msg;
        msg = sip_message_create(SIP_MESSAGE_REQUEST);

        size_t n = strlen(req);
        http_parser_t *parser = http_parser_create(HTTP_PARSER_REQUEST, NULL, NULL);
        assert(0 == http_parser_input(parser, req, &n) && 0 == n);
        assert(0 == sip_message_load(msg, parser));
        http_parser_destroy(parser);
        return msg;
    }

    struct sip_message_t *Reply2sip(const char *reply) {
        struct sip_message_t *msg;
        msg = sip_message_create(SIP_MESSAGE_REPLY);

        size_t n = strlen(reply);
        http_parser_t *parser = http_parser_create(HTTP_PARSER_RESPONSE, NULL, NULL);
        assert(0 == http_parser_input(parser, reply, &n) && 0 == n);
        assert(0 == sip_message_load(msg, parser));
        http_parser_destroy(parser);
        return msg;
    }
