### ISSUE TITLE
librtmp在WEB断用video.js播放能连上，但是一直黑屏，查了上网上的资料，是因为不支持complex handshake的原因

### ISSUE THREAD

**Issue by jinleihit** [ireader/media-server#110]
整个库写得非常好，拿来就可以用；
如果能够支持complex handshake就完美了；

nginx-rtmp-module是支持的，可以参考；
https://blog.csdn.net/win_lin/article/details/13006803这个里面也有相关介绍。

不知道楼主什么时候能够升级一个版本？

**Comment by ireader** [comment]
支持flush，编译librtmp时定义_FLASH_HANDSHAKE_宏即可。 
ssl库可以选择openssl或者用sdk中自带的sha实现，分别对应_OPENSSL_、_IETF_HMAC_宏。

详见librtmp/source/rtmp-handshake.c文件实现.

**Comment by jinleihit** [comment]
看到了，多谢
