### ISSUE TITLE
libsip的使用notify

### ISSUE THREAD

**Issue by kqbi** [ireader/media-server#111]
收到订阅后
![图片](https://user-images.githubusercontent.com/40823194/93852549-ca992a80-fce4-11ea-9256-ee225646fb6d.png)
![图片](https://user-images.githubusercontent.com/40823194/93852639-f74d4200-fce4-11ea-85df-e55981e8cfd1.png)
调用sip_uac_notify后，生成的notify如下
![图片](https://user-images.githubusercontent.com/40823194/93852794-3e3b3780-fce5-11ea-98df-c979619a1ec7.png)
缺少uri，调试发现在sip_message_init2里
![图片](https://user-images.githubusercontent.com/40823194/93852799-3f6c6480-fce5-11ea-9c9e-414ef602ab9d.png)
这里size为0, dialog->target为空， NOTIFY消息头里的from to也应该反过来

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/94112289-c94c3700-fe77-11ea-8068-e03241881991.png)
将此处1改为0解决from to 颠倒问题，
![图片](https://user-images.githubusercontent.com/40823194/94112339-df59f780-fe77-11ea-904d-24c8d694d194.png)
发送消息前增加sip_message_set_uri函数解决uri为空问题

**Comment by kqbi** [comment]
暂时先这样改用用看吧

**Comment by kqbi** [comment]
sip_message_set_uri 函数应该是这样的上边写错了sip_message_set_uri(t->req,"sip:15000000002000000001@192.168.1.61:5060");
还有一个问题，上级发的订阅请求里有contacts回复也应该有
SUBSCRIBE sip:14000000001310000002@192.168.1.191:5061 SIP/2.0
Via: SIP/2.0/UDP 192.168.1.61:5060;branch=z9hG4bK-524287-1---b7438f24e01b714f;rport
Max-Forwards: 70
Contact: <sip:15000000002000000001@192.168.1.61:5060>
To: <sip:14000000001310000002@192.168.1.191:5061>
From: <sip:15000000002000000001@192.168.1.61:5060>;tag=094d7f7e
Call-ID: EuBoqr9Npk4tEFVtf9wCNg..
CSeq: 1 SUBSCRIBE
Expires: 60
Allow: REGISTER, MESSAGE, INVITE, INFO, BYE, ACK, NOTIFY
Content-Type: Application/MANSCDP+xml
User-Agent: ICTT SIP V1.0
Event: presence
Content-Length: 132

<?xml version="1.0" ?>
<Query>
    <CmdType>Catalog</CmdType>
    <SN>2</SN>
    <DeviceID>14000000001310000002</DeviceID>
</Query>
结果发现在使用sip_uas_reply这个函数的回复里没有contacts

**Comment by kqbi** [comment]
在sip_message_init3函数里添加
`
for (i = 0; i < sip_contacts_count(&req->contacts); i++)
	{
		msg->ptr.ptr = sip_contact_clone(msg->ptr.ptr, msg->ptr.end, &contact, sip_contacts_get(&req->contacts, i));
		sip_contacts_push(&msg->contacts, &contact);
	}
`

**Comment by ireader** [comment]
> sip_message_set_uri 函数应该是这样的上边写错了sip_message_set_uri(t->req,"sip:15000000002000000001@192.168.1.61:5060");
> 还有一个问题，上级发的订阅请求里有contact回复也应该有
> SUBSCRIBE sip:14000000001310000002@192.168.1.191:5061 SIP/2.0
> Via: SIP/2.0/UDP 192.168.1.61:5060;branch=z9hG4bK-524287-1---b7438f24e01b714f;rport
> Max-Forwards: 70
> Contact: sip:15000000002000000001@192.168.1.61:5060
> To: sip:14000000001310000002@192.168.1.191:5061
> From: sip:15000000002000000001@192.168.1.61:5060;tag=094d7f7e
> Call-ID: EuBoqr9Npk4tEFVtf9wCNg..
> CSeq: 1 SUBSCRIBE
> Expires: 2629000
> Allow: REGISTER, MESSAGE, INVITE, INFO, BYE, ACK, NOTIFY
> Content-Type: Application/MANSCDP+xml
> User-Agent: ICTT SIP V1.0
> Event: presence
> Content-Length: 132
> 
> 结果发现在使用sip_uas_reply这个函数的回复里没有contact

reply默认都没有带contact，因为需要contact需要获取本地地址，这个可以调用add_header添加。
