### ISSUE TITLE
libmov的MP4需要添加一个封面的函数

### ISSUE THREAD

**Issue by fancong5201314** [ireader/media-server#112]
libmov针对写MP4的接口，需要增加一个添加封面的接口，用于指定JPG或者PNG图片作为MP4文件的封面。通过对比发现，MP4添加封面前后，MOOV里面增加了一个udta的box，里面有meta，下面hdlr和list里面存放的是图片的信息。

**Comment by ireader** [comment]
使用代码： test/mov-writer-test.cpp

![image](https://user-images.githubusercontent.com/1535445/97079693-b7051a80-1628-11eb-91ae-09c1a6558bdc.png)
