### ISSUE TITLE
librtmp rtmp_chunk_basic_header_write中的疑问

### ISSUE THREAD

**Issue by chuanjiong** [ireader/media-server#113]
librtmp\source\rtmp-chunk-header.c
rtmp_chunk_basic_header_write中，

int rtmp_chunk_basic_header_write(uint8_t* out, uint8_t fmt, uint32_t id)
{
	if (id >= 64 + 255) **//这里是否要改成 64+256?**
	{
		*out++ = (fmt << 6) | 1;

**Comment by ireader** [comment]
是的，感谢指正！
