### ISSUE TITLE
rtsp->auth.username 中为空

### ISSUE THREAD

**Issue by 156704883** [ireader/media-server#115]
media-server\librtsp\source\client\rtsp-client-auth.c 中   
int rtsp_client_www_authenticate(struct rtsp_client_t* rtsp, const char* filed)｛	
memset(&rtsp->auth, 0, sizeof(rtsp->auth));     
strcpy(rtsp->auth.username,rtsp->usr);  //增加这一行,如果不加后面用到 rtsp->auth.username  为空
｝

**Comment by ireader** [comment]
是需要加上username，之前的测试不知道怎么通过的，非常感谢指正！

**Comment by 156704883** [comment]
我也是刚用，正好跑一个测试 rtsp 连接，跟踪到这个问题 
还有一个  int rtsp_addr_is_multicast(const char* ip);  这个放在 rtsp-client-test.c 文件中，放到 rtsp-client.h 中更好，这样不包函测试文件，也可以把这个函数导出来用

**Comment by ireader** [comment]
这个函数实现在librtsp/source/rtsp-multicast.c中，使用时直接声明下函数就可以，不用包含测试文件。

rtsp_addr_is_multicast算是工具函数，跟rtsp本身没什么关系，暂时还没合适的地方声明。
