### ISSUE TITLE
关于mov duration计算

### ISSUE THREAD

**Issue by asmgcc** [ireader/media-server#117]
关于mov duration计算有一点不明，比如1min 25fps的h264 mux成mp4文件，第一帧dts=0，最后一帧dts为59960，那么函数mov_writer_destroy中计算出来的duration=59960，而真实的duration应该为60000。最终通过mux出来的mp4文件通过工具（vlc播放器）查看并非25fps，而是25.016678. 这里是否存在问题？还是我在mux的时候dts计算有误？
望解答，谢谢！

**Comment by ireader** [comment]
1. mov的实现原则是只做基本容器格式封装，duration计算没有考虑帧率，所以跟你预期的有差别。
2. vlc具体帧率计算方式没有了解过，大概应该是总duration/总帧数，或者采样一段时间之内的pts和帧数计算出来的。

你可以贴一下每帧视频的时间戳，确认下间隔是否总是相等。

**Comment by asmgcc** [comment]
h264是25fps，1min总帧数1500，dts是固定值40，通过打印得出第一帧dts=0， 最后一帧dts=59960， 而mov_writer_destroy中计算
track->mdhd.duration = track->samples[track->sample_count - 1].dts - track->samples[0].dts;  得出track->mdhd.duration=59960，这样计算出来的duration 应该少了40，可能这样播放器识别出的帧率就有误差了， 而且播放器进度条的总时间是59秒。
后面我试验修改将track->mdhd.duration = track->samples[track->sample_count - 1].dts - track->samples[0].dts+40;，播放器计算的帧率就正确了，播放器精度掉总时间也是1:00;

**Comment by ireader** [comment]
回头我修复下这个问题，在计算duration时加一个平均duration值。
