### ISSUE TITLE
Questions about Librtp

### ISSUE THREAD

**Issue by ShootingKing-AM** [ireader/media-server#118]
Hi, I have some questions about ireader/ librtp.
I have an application requirement of Streaming video from desktop to mobile, for gaming purposes, which requires ultra low latency streaming so i chose RTP protocol, (webRTC being lossy)

While i was going accross open-source rtb libs available in C/C++, i came accross various different libraries.

My Questions,
1. Does media-server/ librtp utilize hardware accleration if avalilable for encoding and decoding ? Like can it use FFMPEG to utilize GPU ?
2. What are the difference between your RTP library and others (pjsip/pjmedia (RTP), GNU ccRTP, FFMPEG's RTP, gstreamer RTP, live555 RTP, etc etc to mention some)
3. Is this library cross-platform, can i compile it on Android Native JNI ?
4. Does this libary have mechanisms to handle Jitter ?

Thankyou.

**Comment by ireader** [comment]
A1: media-server/librtp don't have encoding/decoding module, it only use as rtp packing/unpacking(mux/demux);
A3: media-server/librtp/Android.mk can use to build android native static library
A4: what do you mean about jitter?   RTCP jitter or webrtc netEQ?

Totally, if you want to use with video encoding/decoding, ffmpeg/gstream is the best choose; If have exist audio/video encoding module, only want to send streaming audio/video packet, pjrtp/librtp maybe perferred.

**Comment by ShootingKing-AM** [comment]
> A1: media-server/librtp don't have encoding/decoding module, it only use as rtp packing/unpacking(mux/demux);
> A3: media-server/librtp/Android.mk can use to build android native static library
> A4: what do you mean about jitter? RTCP jitter or webrtc netEQ?
> 
> Totally, if you want to use with video encoding/decoding, ffmpeg/gstream is the best choose; If have exist audio/video encoding module, only want to send streaming audio/video packet, pjrtp/librtp maybe perferred.

First of all, thanks for your quick reply :)

A4: I meant RTP Transmission jitter, like does this Library has any mechanisms specificallly to reduce negative effects of jitter in transmission.

Anyways, thanks for clarifying the different library usages for different application requirements. Thats a lot of help :D

**Comment by ireader** [comment]
RTP jitter just as a network statistics metric, it can't be reduce by rtp library.  APP can use jitter metrics to adjust audio/video bitrate.

**Comment by ShootingKing-AM** [comment]
Ok, Thanks for the clarification.
