### ISSUE TITLE
libsip uas

### ISSUE THREAD

**Issue by kqbi** [ireader/media-server#119]
![图片](https://user-images.githubusercontent.com/40823194/101478726-170f1080-398c-11eb-84b1-b70021e035aa.png)
这个是在哪析构的为什么用valgrind跑会有内存泄漏啊

**Comment by kqbi** [comment]
好像只要调用sip_uas_reply触发sip_timer_start就会这样

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/101479075-969cdf80-398c-11eb-92ef-bc6e27afc27d.png)
![图片](https://user-images.githubusercontent.com/40823194/101479088-9997d000-398c-11eb-8b7e-24114b9c193e.png)
sip_uac_message好像也会

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/101483807-ab30a600-3993-11eb-8297-178621c0ffcf.png)
还有如果ctrl +c 有没有清理后台呢，比如调用aio_timeout_clean

**Comment by ireader** [comment]
> ![图片](https://user-images.githubusercontent.com/40823194/101478726-170f1080-398c-11eb-84b1-b70021e035aa.png)
> 这个是在哪析构的为什么用valgrind跑会有内存泄漏啊

reply会对sip uas transaction释放引用计数。 这个有专门的测试用例sip_agent_test，从测试看应该没有transaction级别的内存泄露。

**Comment by kqbi** [comment]
观察发现是reply调用了
![图片](https://user-images.githubusercontent.com/40823194/101558704-73a91480-39fa-11eb-9bc7-a844991926c7.png)
![图片](https://user-images.githubusercontent.com/40823194/101558718-7ad02280-39fa-11eb-9110-29203a2ce2ef.png)
出发了sip_timer_start，有个64的数组然后我把指针地址打出来，没看到相同地址的sip_timer_stop释放

**Comment by ireader** [comment]
知道原因了，sip_uas_transaction_timewait超时后，只做了release transaction 操作，因为是走的正常超时流程，没有调用sip_timer_stop函数。 

犯了逻辑错误，只想着应该释放transaction的内存，忘记了释放timer本身的内存，修改如下图：

![image](https://user-images.githubusercontent.com/1535445/101560384-28910080-39fe-11eb-82bd-94f74a4cf80d.png)

**Comment by ireader** [comment]
libsip里所有t->timerxx = NULL的地方都有同样的问题，周末我查一下，统一修改过来。

谢谢你仔细的测试！

**Comment by kqbi** [comment]
好的，能解决问题就是好事，辛苦大佬！！!

**Comment by ireader** [comment]
还是有点问题，调用stop会可能会多减一次引用计数，我再确认下。。。

**Comment by ireader** [comment]
刚扒了下timer部分的实现，应该可以正常使用，虽然看上去不太优雅，但是勉强可以用。

**Comment by kqbi** [comment]
OK，期待新版！！！

**Comment by kqbi** [comment]
大佬有空的话，也可以用valgrind跑下valgrind --tool=memcheck --leak-check=yes --show-reachable=yes --log-file=val.log ./test
有些still reachable的我不确定算不算内存泄漏

**Comment by kqbi** [comment]
我在看代码的时候有几个疑惑顺便问下，结构体里的层层嵌套的指针不需要一个个去释放吗
![图片](https://user-images.githubusercontent.com/40823194/101570485-719e8000-3a11-11eb-8941-c0e450c17d6f.png)
![图片](https://user-images.githubusercontent.com/40823194/101570491-75ca9d80-3a11-11eb-8ddc-c3ebee7ab835.png)
![图片](https://user-images.githubusercontent.com/40823194/101570499-7b27e800-3a11-11eb-850d-ae65ae973196.png)
![图片](https://user-images.githubusercontent.com/40823194/101570512-85e27d00-3a11-11eb-893b-fd0a9ba06984.png)
还有这种中间使用的结构体
![图片](https://user-images.githubusercontent.com/40823194/101570665-dbb72500-3a11-11eb-964e-eea231783fcf.png)
不需要将结构体里的指针单独free吗

**Comment by ireader** [comment]
正常来说是需要释放，但是各种结构体内部嵌套太复杂了，为了简化代码，提前在sip_message_t这个结构体内申请了一块内存，各种sip header结构体内部都使用msg预申请的内存，释放时只需要保证msg内存正确释放就行。

sip_message_copy / sip_header_contact / sip_header_via / sip_header_xxx 系列函数都需要外部传入内存，实际中使用的就是sip_message_t里的内存块。

**Comment by kqbi** [comment]
哦哦，谢谢解惑，我理解理解

**Comment by kqbi** [comment]
大佬内存的问题怎么样了

**Comment by kqbi** [comment]
@ireader

**Comment by ireader** [comment]
分析中。。。
