### ISSUE TITLE
libmpeg ts-enc H.265 写入数据保存为文件后，读取出来的格式不正常

### ISSUE THREAD

**Issue by yangchar** [ireader/media-server#12]
ffplay 软件版本：ffmpeg-3.3.1

H.264 + AAC 测试正常

只修改了tsctx->pat.pmt[0].streams[1].avtype = PSI_STREAM_H265;
然后送入AAC的音频和H.265 视频数据，用ffplay 播放只有音频，解析提示如下：

yangchar@yangchar:~$ ffmpeg-3.3.1/ffplay /tftpboot/output.ts 
ffplay version 3.3.1 Copyright (c) 2003-2017 the FFmpeg developers
  built with gcc 4.8 (Ubuntu 4.8.4-2ubuntu1~14.04.1)
  configuration: 
  libavutil      55. 58.100 / 55. 58.100
  libavcodec     57. 89.100 / 57. 89.100
  libavformat    57. 71.100 / 57. 71.100
  libavdevice    57.  6.100 / 57.  6.100
  libavfilter     6. 82.100 /  6. 82.100
  libswscale      4.  6.100 /  4.  6.100
  libswresample   2.  7.100 /  2.  7.100
[mpegts @ 0x7fdcc40008c0] PES packet size mismatchsq=    0B f=0/0   
[mp3 @ 0x7fdcc4009540] Header missingB vq=    0KB sq=    0B f=0/0   
    Last message repeated 5 times
[mpegts @ 0x7fdcc40008c0] decoding for stream 0 failed
[mpegts @ 0x7fdcc40008c0] PES packet size mismatch
[mpegts @ 0x7fdcc40008c0] Could not find codec parameters for stream 0 (Audio: mp3, 0 channels, s16p): unspecified frame size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from '/tftpboot/output.ts':
  Duration: 00:00:15.83, start: 156.592000, bitrate: 711 kb/s
  Program 1 
  No Program
    Stream #0:0[0x102]: Audio: mp3, 0 channels, s16p
    Stream #0:1[0x101]: Audio: aac (LC), 44100 Hz, mono, fltp, 128 kb/s
 160.61 M-A: -0.000 fd=   0 aq=   21KB vq=    0KB sq=    0B f=0/0 

文件在附件中
[output.zip](https://github.com/ireader/media-server/files/1446412/output.zip)

**Comment by ireader** [comment]
H.265 AUD 写入错误，更新后再试试。
