### ISSUE TITLE
libsip更换新后使用崩溃

### ISSUE THREAD

**Issue by kqbi** [ireader/media-server#120]
![图片](https://user-images.githubusercontent.com/40823194/102077632-95fcc100-3e44-11eb-8c62-86aeb864151d.png)
跟下级级联发送指令，下级回复200ok就崩溃了
![图片](https://user-images.githubusercontent.com/40823194/102077938-099ece00-3e45-11eb-9f0f-23bd01b96ff8.png)

**Comment by ireader** [comment]
抱歉，周末更新时提交的版本不对，下面是修复记录。  valgraind内存泄露问题还没来得及看，这周末我再细查一遍。

![image](https://user-images.githubusercontent.com/1535445/102079651-0b1dc580-3e48-11eb-8085-8f7cfd90ce95.png)

**Comment by kqbi** [comment]
OK
