### ISSUE TITLE
chrome在2020年就不支持flash player了，网页上播放rtmp楼主有什么推荐方案吗？ 

### ISSUE THREAD

**Issue by jinleihit** [ireader/media-server#121]
chrome在2020年就不支持flash player了，网页上播放rtmp楼主有什么推荐方案吗？ 

网上有推荐服务器用flv协议，用bilibili的flv.js播放，楼主的库能在rtmp的基础上增加flv点播吗？

**Comment by ireader** [comment]
有FLV支持，HTTP-FLV播放时，使用libflv/include/flv-writer.h中的flv_writer_create2函数，把write回调参数设置成http发送函数，生成的回调数据就是HTTP-FLV需要的数据格式。

flv_writer_input输入为音视频数据。

**Comment by jinleihit** [comment]
非常感谢您的解答。
我把我的使用场景具体描述下，**请您再帮忙分析下最快的实现方案；**

我是做一个嵌入式linux的转码设备，将多个摄像头过来的实时h264视频数据转码供网页点播；
之前是用您这个librtmp实现rtmp server，web端用video.js就可以实现rtmp点播；

现在chrome上flash-player不再继续支持，只能换成http-flv了，这样实时视频演示小一些；
按照您建议的方案，使用libflv/include/flv-writer.h中的flv_writer_create2函数；把write回调参数设置成http发送函数，生成的回调数据就是HTTP-FLV需要的数据格式。flv_writer_input输入为音视频数据。

具体如何实现完整的http-flv我还没太想明白，还需要详细请教下。
**使用ireader/sdk中的libhttp库结合libflv库是否就可以创建一个http-flv server？是否还需要其他的步骤？**
如果能有个简单的sample就太好了

**Comment by ireader** [comment]
新增了一个http-flv的例子，libflv/test/http-flv-live.cpp

**Comment by jinleihit** [comment]
太给力、太专业了，万分感谢。
我们参考sample先试下
