### ISSUE TITLE
请教一下librtmp里面的宏_FLASH_HANDSHAKE_,定义了两种握手方式，这两种方式分别用于什么场合？

### ISSUE THREAD

**Issue by 7956968** [ireader/media-server#122]

**Comment by ireader** [comment]
如字面意义，如果需要使用flash播放rtmp流，需要定义_FLASH_HANDSHAKE_这个宏，否则只有音频，无法播放H.264视频。

定义这个宏时会使用flash私有方式加密握手包，只有这种方式才能让flash播放器正常播放视频流。

其它播放器不需要定义，默认不需要。

**Comment by 7956968** [comment]
我看srs就没有这种区分开的握手方式，是他做了兼容吗？还是他只支持_FLASH_HANDSHAKE_这种方式？

**Comment by ireader** [comment]
可能是默认支持了。   

定义这个宏会使用一些加密算法，需要引入openssl依赖。

**Comment by 7956968** [comment]
我粗略的看了下，ffmpeg命令行推流是不需要_FLASH_HANDSHAKE_支持的，obs推流必须要这个宏。这就很有点难受，做不到ffmpeg推流和obs推流兼容。

**Comment by ireader** [comment]
定义这个宏没有副作用，ffmpeg、obs都可以正常推流、拉流。

根据实际情况使用openssl或者用sdk项目中的ietf实现加密算法实现都可。

**Comment by 7956968** [comment]
哦。那我搞错了。非常感谢。这么晚了还回答我的问题。
