### ISSUE TITLE
ps流打包, 音频无法播放

### ISSUE THREAD

**Issue by hh-kai** [ireader/media-server#124]
[h264_g711a.zip](https://github.com/ireader/media-server/files/5854071/h264_g711a.zip)
这是打包后的文件 
用mpeg_ps_dec_test("h264_g711a.ps") 
添加 
![image](https://user-images.githubusercontent.com/19390025/105457865-7f0e8180-5cc2-11eb-9650-6b8d4944bdaf.png)
分离音视频 得到g711a音频 用ffplay播放正常 ffplay -i a.aac  -f alaw -ac 1 -ar 8000
再用 mpeg_ps_test("h264_g711a.ps") 得到 h264_g711a.ps.ps
然后再分离h264_g711a.ps.ps 得到的音频也是正常的
迷惑的地方：
1. h264_g711a.ps有问题，应该解码失败，或者解出的音频有问题，实际是分离成功，并且音视频都正常
2. h264_g711a.ps没有问题，应该解码失败，实际是解码成功，并且试过几个播放器都不能播放出音频

h264_g711a.ps 打包过程
![image](https://user-images.githubusercontent.com/19390025/105458662-f690e080-5cc3-11eb-9657-63c5185833e9.png)
这里打印一条，就会调用一次 ps_muxer_input()

**Comment by ireader** [comment]
> h264_g711a.ps有问题，应该解码失败，或者解出的音频有问题，实际是分离成功，并且音视频都正常
> h264_g711a.ps没有问题，应该解码失败，实际是解码成功，并且试过几个播放器都不能播放出音频

这2条看着有点绕，没看懂具体意思。

标准ps不支持g711，所以播放器只播放视频，不能播放音频是正常的，目前只有国标播放器可以支持g711音频。

**Comment by hh-kai** [comment]
> > h264_g711a.ps有问题，应该解码失败，或者解出的音频有问题，实际是分离成功，并且音视频都正常
> > h264_g711a.ps没有问题，应该解码失败，实际是解码成功，并且试过几个播放器都不能播放出音频
> 
> 这2条看着有点绕，没看懂具体意思。
> 
> 标准ps不支持g711，所以播放器只播放视频，不能播放音频是正常的，目前只有国标播放器可以支持g711音频。
意思就是源文件能够支持音视频分离，但是播放器不能播放，这就矛盾了
试过aac的音频 vlc也播放不了

**Comment by ireader** [comment]
上传个aac音频打包的测试文件

**Comment by hh-kai** [comment]
> 上传个aac音频打包的测试文件


[h264_aac.zip](https://github.com/ireader/media-server/files/5863775/h264_aac.zip)
用ffplay能播放 
用vlc音频播放不了 提示这个
![image](https://user-images.githubusercontent.com/19390025/105653297-6ab2ca80-5ef6-11eb-9a72-cef979d9e9b5.png)

**Comment by ireader** [comment]
VLC不支持动态更新PSM，需要在写入开始时添加全部音视频流，示例代码如下：
![image](https://user-images.githubusercontent.com/1535445/105656720-d8aec000-5efd-11eb-9883-2ff963a4bfb1.png)

**Comment by hh-kai** [comment]
这样的话 加g711格式的应该也能播放了吧 我试试

**Comment by ireader** [comment]
g711播不了，711是国标扩展，标准ps流不支持。

**Comment by hh-kai** [comment]
测试了 设备端可以播放
