### ISSUE TITLE
内存问题疑惑

### ISSUE THREAD

**Issue by kqbi** [ireader/media-server#125]
![图片](https://user-images.githubusercontent.com/40823194/106257839-0d04e200-6258-11eb-9b2f-d1f799b5eb63.png)
![图片](https://user-images.githubusercontent.com/40823194/106257849-10986900-6258-11eb-8c29-9fb5381398cd.png)
我看很多测试代码在循环里调用了aio_timeout_process，那么是不是会循环调用aio_timeout_init，进而调用time_wheel_create，然后调用calloc申请内存，然后没看到有调用free的地方，是否有问题。
aio_timeout_clean函数也没调用，里边也没有free函数。
大佬，求解惑

**Comment by kqbi** [comment]
onetime_exec这个是能保证全局只调用一次aio_timeout_init吗

**Comment by ireader** [comment]
onetime_exec，如函数名，只执行一次。

具体实现可以参考 sdk/include/sys/onetime.h

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/106261666-d382a580-625c-11eb-9577-c71527bfb132.png)
![图片](https://user-images.githubusercontent.com/40823194/106261682-d9788680-625c-11eb-9730-3129945112f9.png)
valgrind跑，还有几个这样的泄漏不知道为啥

**Comment by ireader** [comment]
OK，周末我再查一下。

**Comment by kqbi** [comment]
有一个场景比如说对方不在线，我一直发注册消息，因为对方不在线，肯定不会回复的，这个时候程序关闭，创建注册这个消息时的sip_uac_transaction_t似乎就没释放，不知道是不是有必要加个清除uac和uas的transaction列表的函数

**Comment by ireader** [comment]
为了保证非可靠网络场景下，客户端/服务端状态一致，uac/uas transaction只会在超时才会释放（内部定时器触发）。如果中途异常退出，就会造成transaction没有及时关闭，打印异常泄露。 

可以测试下，退出之前sleep 60s（调用aio_timer_process），验证是否还有内存泄露。

**Comment by kqbi** [comment]
OK

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/106346407-e4312b00-62f1-11eb-85fe-b75c973843ef.png)
![图片](https://user-images.githubusercontent.com/40823194/106346409-e8f5df00-62f1-11eb-8299-8bfb14011417.png)
我调试发现sip_uac_transaction_addref一开始就是2，结果导致后边sip_uac_transaction_release里边atomic_decrement32没办法归0，
是我这边代码sip_uac_transaction_addref这个函数有问题吗，怎么一开始就是2起步

**Comment by kqbi** [comment]
我知道了，你test里用的智能指针会自动调用sip_uac_transaction_release(t); ，我没用智能指针也就是我需要手动调用下sip_uac_transaction_release(t);然后sip_uac_transaction才能正常清除
