### ISSUE TITLE
libsip服务设计问题

### ISSUE THREAD

**Issue by kqbi** [ireader/media-server#129]
大佬麻烦问下，如果用libsip写个服务端，对接上千个sip设备，是不是应该类似你的sip-agent-test一样一个设备一个sip_agent_t啊，性能这块你可测过

**Comment by ireader** [comment]
sip_agent_t用一个就行了。

**Comment by kqbi** [comment]
一个udp收发 一个sip_agent_t，感觉性能不太够
![图片](https://user-images.githubusercontent.com/40823194/110049943-cd1ca780-7d8d-11eb-8789-0804946c387d.png)
这块虽然在线程里边但是包含了回调触发和回复，不知道性能够不够，然后transaction 多了timer不知道可能处理过来

**Comment by ireader** [comment]
sip_agent_t只处理协议部分不会成为性能瓶颈。 

处理业务逻辑时，如果有阻塞需要异步处理，send如果是同步的需要改成异步；

timer本身可以开多个线程并发处理，内部支持多线程并发，可以根据你的业务需要启用多个线程；

**Comment by kqbi** [comment]
OK

**Comment by kqbi** [comment]
完全的异步好像会有问题哎，比如invite请求设备回复101 和200OK，然后异步处理，这个顺序就没办法保证了

**Comment by ireader** [comment]
每个transaction是独立的，异步处理记得要对transaction加减引用计数：addref/release
