### ISSUE TITLE
mpeg4-hevc.c mpeg4_hevc_decoder_configuration_record_load 解析错误

### ISSUE THREAD

**Issue by illuspas** [ireader/media-server#13]
mpeg4_hevc_t结构体里 nalu.data 固定256
但遇到libx265编码，Prefix SEI 大大超出这个值，1800多字节，这里解析就错误了
我暂时设置了个大值

**Comment by ireader** [comment]
256字节在某些情况下确实有点小，之前主要考虑把mpeg4_hevc_t做为stack变量用，不能占用空间太多。确实是设计时考虑不周。
