### ISSUE TITLE
关于rtsp服务器拉流

### ISSUE THREAD

**Issue by BestHelloWorld** [ireader/media-server#130]
现在参考了rtsp-push-server.cpp，服务器通过announce接受配置sdp数据，返回到客户端on_announce中。打算调用
`int rtsp_client_setup(struct rtsp_client_t* rtsp, const char* sdp)`
让服务器走setup，但是这个sdp怎么写？
有没有客户端推流的例子呢？

**Comment by ireader** [comment]
rtsp推流是，先调用客户端rtsp_client_announce函数，然后再setup。 

announce主要告诉服务端录像的音视频信息。

**Comment by BestHelloWorld** [comment]
好的，谢谢
