### ISSUE TITLE
rtcp解析出错

### ISSUE THREAD

**Issue by Leonard76152** [ireader/media-server#132]
你好，请问：rtcp解析时，长度判断是基于什么？
`static int rtcp_parse(struct rtp_context *ctx, const unsigned char* data, size_t bytes)
{
  ... ...
  if (header.length * 4 + 4 > bytes) {
    assert(0);
    return -1;
  }
  ... ...
}`
我看FFmpeg中解析是取的两者的最小值。现在的问题，获取部分摄像头的流是失败的，但是VLC是可以的。原因就是进入了这个判断里面。

**Comment by ireader** [comment]
rtcp长度计算方式在rfc3550中有明确定义。 如果出现了header.length * 4 + 4 > bytes的情况，可以确认下是不是rtcp包封装错误。

如果暂时解决不了，可以忽略掉rtcp的处理，注释assert，return 0。不影响基本功能。

**Comment by Leonard76152** [comment]
协议中确实有明确的规定，需要四字节对齐，不够需要填充。感谢！
