### ISSUE TITLE
libmov能用抽象io实现吗？

### ISSUE THREAD

**Issue by illuspas** [ireader/media-server#14]
目前fire-writer和fire-reader使用系统调用做io，能抽象成io接口由使用者决定使用何种io调用吗？
感觉mp4文件要回写数据，是不是很麻烦

**Comment by ireader** [comment]
正在考虑抽象出io接口，类似于ffmpeg的avio。

**Comment by illuspas** [comment]
目前您维护的sdk那个项目也非常好，学习了。不过可以考虑使用成熟的框架比如我会用libuv，然后这个项目专注于媒体库的实现。
您这个库真的写的很好，我在很多平台上都能直接使用，nodejs的c++扩展，最近用emscripten也是完美集成。

**Comment by notedit** [comment]
+1  抽象io接口,  开发者自己决定用哪种io调用   方便其他语言封装

**Comment by ireader** [comment]
新增mov_buffer_t接口，mp4读写demo已更新
