### ISSUE TITLE
当我使用一个大华摄像头传输GB的PS流时，首包出现type=0

### ISSUE THREAD

**Issue by programcj** [ireader/media-server#141]
建议在mpeg_packet_h264_h265中的开头增加    pkt->codecid = pes->codecid;

还有如果视频采用子码流的时候，可否不去等待 pes_packet_length 长度到达就输出数据?这样会更快的出流，只做H264/H265 的 NAL单元输出

**Comment by ireader** [comment]
只做ps demux？

**Comment by ireader** [comment]
> 建议在mpeg_packet_h264_h265中的开头增加 pkt->codecid = pes->codecid;

这个的目的是？

**Comment by programcj** [comment]
在我debug时， mpeg_packet_h264_h265 参数pkt的codecid 为0，在onpacket中的avtype就是0了，外面不知道这个pes的id

**Comment by programcj** [comment]
@ireader 
在我debug时， mpeg_packet_h264_h265 参数pkt的codecid 为0，在onpacket中的avtype就是0了，外面不知道这个pes的id

**Comment by ireader** [comment]
正常应该可以从psm中解析出codec值，不应该出现codecid为0的情况。

上传个ps文件或者rtp抓包文件，我分析下？

**Comment by programcj** [comment]
@ireader 文件怎么发？

**Comment by programcj** [comment]
[Uploading gb28181.rtpdump…]()

**Comment by programcj** [comment]
@ireader 不知道能不能让数据不用等pes_packet_length 个长度就输出视频，让视频在外面拼接NALU，这样输出，首播会更快一点

**Comment by ireader** [comment]
> Uploading gb28181.rtpdump…

这个没有上传成功

**Comment by programcj** [comment]
@ireader 有邮箱吗?qq邮箱发送不了

**Comment by ireader** [comment]
> 
> 
> @ireader 有邮箱吗?qq邮箱发送不了

加下这个qq群：579575545

**Comment by ireader** [comment]
问题已定位，预计周末修复。
