### ISSUE TITLE
请问rtsp server url从哪里获取?

### ISSUE THREAD

**Issue by kbore** [ireader/media-server#142]
test目录有两个例子: rtsp_example, rtsp_push_server.
如果我想测试 rtsp server 播放本地 h264 或 ps 文件, 应该用哪个例子? 客户端 vlc 打开的 rtsp url 是多少?

尝试过 rtsp://xxxx/void/v.264 这样的格式, 提示 rtsp_onerror code=104, rtsp=0x7f1a80001f70

**Comment by ireader** [comment]
1. 修改s_workdir变量，指向你本地的文件路径， 切记最后的斜杠不要丢, windows : \\, linux /
2. 播放url： rtsp://127.0.0.1/vod/v.h264 或者 rtsp://127.0.0.1/vod/v.ps

h264文件后缀xxx.h264, ps文件后缀: xxx.ps, 具体实现在rtsp_ondescribe函数

**Comment by kbore** [comment]
可以了, 感谢解答.
