### ISSUE TITLE
关于RTSP测试例子的使用问题

### ISSUE THREAD

**Issue by zhengqijun0121** [ireader/media-server#144]
1.修改 test/test.cpp 文件，在 `main` 函数中调用 rtsp_example
```c++
rtsp_example();
```

2.修改 librtsp/test/rtsp-server-test.cpp 中文件路径，测试文件在 /home/hello/Documents/Test/test.h264
```
static const char* s_workdir = "/home/hello/Documents/Test/";
```

3.使用 `make clean && make -j4 && make test -j4` 编译成功后，使用 `vlc` 进行连接 
```
rtsp://192.168.188.19/vod/test.h264  或者 rtsp://192.168.188.19/test.h264
```
都不能连接成功。

请问是什么问题？

**Comment by ireader** [comment]
端口554还是8554？

**Comment by zhengqijun0121** [comment]
> 端口554还是8554？

wireshark上看到的是554

**Comment by ireader** [comment]
rtsp_example 启动时指定的端口是554吗？ wireshark能抓包信息里能看到进行到哪一步了吗？

**Comment by zhengqijun0121** [comment]
```
rtsp://192.168.188.19:8554/vod/test.h264
```
我刚刚去看代码里面用的8554，访问的时候指定8554就可以了，vlc能够看到视频播放。
还想请问下uri中的vod和live有什么区别吗？还有如果测试RTSP客户端是不是就调用rtsp_client_test函数就可以了？

**Comment by ireader** [comment]
vod播本地文件
live播实时视频，一般是从摄像机取流。

客户端可以参考rtsp_client_test。

**Comment by zhengqijun0121** [comment]
好的，谢谢。

**Comment by zhengqijun0121** [comment]
```bash
ln -sf ../sdk/libaio/debug.linux/libaio.so . &&  ./test/debug.linux/test
test: ../librtsp/test/rtsp-client-test.c:183: rtsp_client_test: Assertion `socket_invalid != ctx.socket' failed.
Aborted (core dumped)
Makefile:41: recipe for target 'test' failed
make: *** [test] Error 134
```
执行 rtsp_client_test 有个问题

**Comment by ireader** [comment]
socket_invalid != ctx.socket  出现这个错误应该连接失败了， 确认下端口和ip地址有没有问题。

**Comment by zhengqijun0121** [comment]
```c++
rtsp_client_test("127.0.0.1", "vod/test.h264");
```

将IP设置为127.0.0.1，端口设置为8554是可以访问。为什么设置成本地IP(192.168.188.19)就会出现问题？

![mediaserver_cli_reply_bug1](https://user-images.githubusercontent.com/23567849/121474884-48c66a00-c9f7-11eb-91f5-6f40d58c8a4d.png)

在请求DESCRIBE的时候，wireshark中看到回复是这样显示的，请问有问题吗？

**Comment by ireader** [comment]
wireshark红色的只是显示不全，没有问题。 

192.168.188.19是本地地址， 本地有多块网卡吗？ rtsp listen时会绑定个本地地址，默认应该绑定在0.0.0.0地址上， 如果本地有ipv6地址，可能会绑定错误。

可以通过netstat -abn -t 看看8554绑定地址是哪个。
