### ISSUE TITLE
librtsp 无法解析的外部符号

### ISSUE THREAD

**Issue by czhj** [ireader/media-server#145]
编译环境：vs2019
链接库: libaio.lib librtsp.lib sdk.lib

编译错误：
main.obj:-1: error: LNK2019: 无法解析的外部符号 _rtsp_server_listen，该符号在函数 _main 中被引用
main.obj:-1: error: LNK2019: 无法解析的外部符号 _rtsp_server_unlisten，该符号在函数 _main 中被引用

编译的时候需要加入其他库还是 编译库的时候要加入其他编译命令？

测试代码：
```
  aio_worker_init(AIO_THREAD_NUM);

  struct aio_rtsp_handler_t handler;
  memset(&handler, 0, sizeof(handler));
  handler.base.ondescribe = rtsp_ondescribe;

  void *tcp = rtsp_server_listen(nullptr, 8544, &handler, nullptr);

  while (true) {}

  aio_worker_clean(AIO_THREAD_NUM);
  rtsp_server_unlisten(tcp);
```

**Comment by ireader** [comment]
rtsp_server_listen在librtsp\source\server\aio目录下

**Comment by ireader** [comment]
点错了

**Comment by czhj** [comment]
> rtsp_server_listen在librtsp\source\server\aio目录下

这个会编译进哪个lib里面？不在librtsp或libaio里面吗？

**Comment by ireader** [comment]
这些依赖网络或者现场库，跟rtsp协议本身没有关系， 所以都是作为单独代码模块。

在test/Makefile里有rtsp相关辅助代码的编译示例。

**Comment by czhj** [comment]
> 这些依赖网络或者线程库，跟rtsp协议本身没有关系， 所以都是作为单独代码模块。
> 
> 在test/Makefile里有rtsp相关辅助代码的编译示例。

好的，看到了
