### ISSUE TITLE
运行rtsp_example有崩溃

### ISSUE THREAD

**Issue by Dw9** [ireader/media-server#147]
老陈好：
最近在跑rtsp_example有点问题，详细情况如下：

1、复现步骤
a、修改s_workdir指定自己的目录
b、test.cpp中仅运行rtsp_example()
c、另一台电脑拉流 
d、有崩溃现象

2、崩溃堆栈
![image](https://user-images.githubusercontent.com/36155473/121765981-5c9dd780-cb81-11eb-9f22-568ce72cd8b8.png)

定位到rtp-sender.c  onpacket回调为null

3、代码版本
media-server 3cf0520792129a4abf5b750025bc7e8c51656e7b 
sdk                 3b44375b0cda9cebff7096ac0fa6ebe4d2458118
avcodec         d93510bea7a9d53fdd8412c87af1f8c392233ae8

**Comment by ireader** [comment]
看代码行数跟最新的版本有比较大的差别，能更新到最新的版本吗？

从堆栈看应该是有空指针，测试的mp4文件发给我看看？

**Comment by ireader** [comment]
fix commit 786d04da57e1a6a54bbaa61be8c2ecf63c4780d4

**Comment by Dw9** [comment]
陈老师好，昨晚搞太晚看出画面了就没来得及详细测试。 刚刚发现在流没播完的时候，ctrl+c结束拉流。由于没有收到teardown，tcp连接断了，但服务端仍旧在发送数据导致崩溃。
