### ISSUE TITLE
ts视频解析错误

### ISSUE THREAD

**Issue by alexliyu7352** [ireader/media-server#156]
附件中的zip请改为ts扩展名,因为ts没办法上传
这段视频是网上找的, 使用ts解析时候, ts_demuxer_notify返回的finish始终为false.
[t.zip](https://github.com/ireader/media-server/files/6750561/t.zip)

**Comment by ireader** [comment]
``` mpeg_ts_dec_test("t.ts"); ```

测试解析正常：
![image](https://user-images.githubusercontent.com/1535445/124209997-400c1400-db1d-11eb-9774-d159bde94b79.png)

**Comment by alexliyu7352** [comment]
stream 256, codecid: 27, finish: false

这个也算正常么?

**Comment by alexliyu7352** [comment]
抱歉....我理解错误...这是正常的
