### ISSUE TITLE
是否支持ac3,eac3

### ISSUE THREAD

**Issue by alexliyu7352** [ireader/media-server#159]
请问大神是否支持Ac3与eac3, 如果不支持能否增加?

**Comment by ireader** [comment]
哪个库？ 什么应用场景？

**Comment by alexliyu7352** [comment]
拉mpegts, 然后输出hls.
也就是用到libmpeg与libhls.
其中拉流中的音频编码是eac3

**Comment by ireader** [comment]
libmpeg支持Ac3/eac3，相关id定义在mpeg-ts-proto.h文件中

libhls也支持，只是默认添加的aac音频流，需要修改下hls_media_create函数实现。

**Comment by alexliyu7352** [comment]
感谢大神!看到了.抱歉回复的晚了!
您这个项目真的太棒了!
