### ISSUE TITLE
some sdp_option_xxx functions missing when linking

### ISSUE THREAD

**Issue by chenbd** [ireader/media-server#160]
hello,
> undefined reference to `sdp_option_setup_to'

> undefined reference to `sdp_option_media_from'

> undefined reference to `sdp_option_proto_from'

> undefined reference to `sdp_option_mode_to'

> undefined reference to `sdp_option_setup_from'

seems the source file is missing in git repository.
would you please check?

**Comment by ireader** [comment]
Maybe your Makefile miss sdp-options.c(librtsp/source/sdp-options.c)

**Comment by chenbd** [comment]
Got it!
Sorry for disturbing, thanks!
