### ISSUE TITLE
如何运行 librtsp 的测试？

### ISSUE THREAD

**Issue by TDA-2030** [ireader/media-server#161]
## 描述

我想移植rtsp到自己的嵌入式平台，想先跑一下librtsp，可是我在仓库里找不到文档告诉我该如何运行一个简单的测试程序。
希望能解释一下我该如何进行测试以及需要准备的东西 :grimacing:

**Comment by ireader** [comment]
librtsp/test目录下包含一个rtsp server demo程序，可以通过如下命令执行：
1,  make && make test 
2. ./debug.linux/test -c rtsp_example 

编译过程中可能会提示缺少文件，请从github上下载依赖项目:
1. https://github.com/ireader/sdk
2. https://github.com/ireader/3rd
3. https://github.com/ireader/avcodec

**Comment by TDA-2030** [comment]
我正常运行了这个`rtsp_example`，但是我不知道该用哪个url来访问这个server。琢磨了一下感觉似乎需要放个媒体文件在某个地方让它打开，需要再指导一下

**Comment by ireader** [comment]
rtsp://127.0.0.1:8554/vod/filename.mp4

其中vod是固定路径，filename.mp4是你的测试文件名。

在librtsp/test/rtsp-server-test.cpp文件中，修改第33行 s_workdir 变量值，改成你的视频文件所在路径。注意：路径最后的斜杠不要少！！！

同样8554端口可以改成其它端口。

**Comment by TDA-2030** [comment]
搞定了，感谢！

**Comment by wangwenqiangGitHub** [comment]
ffplay rtsp://127.0.0.1:8554/vod/11.mp4我用这个播放程序就挂掉了
