### ISSUE TITLE
rtsp-server的session超时timeout问题

### ISSUE THREAD

**Issue by czhj** [ireader/media-server#162]
我现在是用rtsp-server做服务端，需要一个心跳超时，但是看代码好像没提供拿到session.timeout这个值的接口，而且也没办法设置这个值。有什么办法拿到这个值吗？

**Comment by ireader** [comment]
确实缺少接口获取timeout值，可以增加一个接口，类似rtsp_server_get_session_info(rtsp, session)；

这周六我加上，着急的话你可以先加上。

**Comment by czhj** [comment]
> 确实缺少接口获取timeout值，可以增加一个接口，类似rtsp_server_get_session_info(rtsp, session)；
> 
> 这周六我加上，着急的话你可以先加上。

好的

**Comment by ireader** [comment]
重新查了下rtsp规范，server端的timeout本身就是由用户设置的，不需要增加获取的接口。
https://datatracker.ietf.org/doc/html/rfc2326#section-12.37
> The timeout parameter is only allowed in a response header. The 
> server uses it to indicate to the client how long the server is
> prepared to wait between RTSP commands before closing the session due
> to lack of activity (see Section A).

- rtsp服务端增加设置timeout接口 rtsp_server_set_session_timeout
- 客户端端setup回调，增加timeout参数。

**Comment by czhj** [comment]
> 重新查了下rtsp规范，server端的timeout本身就是由用户设置的，不需要增加获取的接口。
> https://datatracker.ietf.org/doc/html/rfc2326#section-12.37
> 
> > The timeout parameter is only allowed in a response header. The
> > server uses it to indicate to the client how long the server is
> > prepared to wait between RTSP commands before closing the session due
> > to lack of activity (see Section A).
> 
> * rtsp服务端增加设置timeout接口 rtsp_server_set_session_timeout
> * 客户端端setup回调，增加timeout参数。

这里面好像也没有设置的接口，所以我才想要一个设置或者获取的接口，我现在是自己加了一个设置和获取的接口。

**Comment by ireader** [comment]
对，之前缺少设置接口，刚提交的代码增加了个函数：rtsp_server_set_session_timeout，在setup reply之前调用
