### ISSUE TITLE
请教下rtsp-clent-test.c测试拉流时，卡一会然后退出

### ISSUE THREAD

**Issue by Jierui** [ireader/media-server#163]
sdp如下：
v=0
o=- 1001 1 IN IP4 192.168.20.100
s=VCP IPC Realtime stream
m=video 0 RTP/AVP 105
c=IN IP4 192.168.20.100
a=control:rtsp://192.168.20.100/media/video1/video
a=rtpmap:105 H264/90000
a=fmtp:105 profile-level-id=64002a; packetization-mode=1; sprop-parameter-sets=Z2QAKqwsaoHgCJ+WbgICAoAAAfQAADqYQg==,aO4xshs=
a=recvonly
m=application 0 RTP/AVP 107
c=IN IP4 192.168.20.100
a=control:rtsp://192.168.20.100/media/video1/metadata
a=rtpmap:107 vnd.onvif.metadata/90000
a=fmtp:107 DecoderTag=h3c-v3 RTCP=0
a=recvonly

当收到SETUP reply时
rtsp_client_setup_onreply 此函数
		if (rtsp->media_count == ++rtsp->progress)
		{
			assert(rtsp->media_count > 0);
			range = &rtsp->media[0].range;
			return rtsp->handler.onsetup(rtsp->param, RTSP_RANGE_TIME_NORMAL==range->from_value && RTSP_RANGE_TIME_NORMAL==range->to_value ? range->to - range->from : -1);
		}
		else
		{
			// setup next media
			return rtsp_client_media_setup(rtsp, rtsp->progress);
		}
会进入else里从新发起setup请求，然后一会程序退出
请问这里如何解决呢，退出原因我猜测是服务端没有回复超时所致
1.两个问题，为什么服务端不回复
2.抓包其他client拉去，sdp返回信息一致，而其他客户端只发一次setup,就能正常播放了， 请作者帮忙解答一下疑惑，我已经各种尝试，然后没有思路了，谢谢。

**Comment by ireader** [comment]
从onvif的流规范看，应该是宇视IPC处理有问题，正常来说setup是需要有应答的。
https://www.onvif.org/specs/stream/ONVIF-Streaming-Spec.pdf

为解决这个问题，修改了setup回调函数rtpport返回值定义，当rtpport返回0时rtsp client內部会忽略这路流。

参考代码如下：
![image](https://user-images.githubusercontent.com/1535445/131210786-47b48e92-4ccc-4fdb-855f-227a99899d55.png)

**Comment by Jierui** [comment]
之前Application没有回的原因应该是SETUP是没有带Session，现在我拉音频和视频，第二次SETUP时依旧卡主，对比了下VLC，VLC第二次SETUP时带了SESSION信息，请教下这里应该怎么改呢？

**Comment by ireader** [comment]
目前rtsp client策略是控制url相同时才加session header。

我这边没有环境，方便的话帮忙抓下vlc的包。
