### ISSUE TITLE
fmp4-writer-test2.cpp fmp4-writer-test.cpp 生成的mp4，duration:   0 (ms)

### ISSUE THREAD

**Issue by cfgrpg** [ireader/media-server#165]
File:
  major brand:      isom
  minor version:    1
  compatible brand: isom
  compatible brand: mp42
  compatible brand: avc1
  compatible brand: dash
  compatible brand: iso5
  fast start:       yes

Movie:
  duration:   0 (media timescale units)
  **duration:   0 (ms)**
  time scale: 1000
  fragments:  yes

Found 1 Tracks
Track 1:
  flags:        3 ENABLED IN-MOVIE
  id:           1
  type:         Video
  **duration: 0 ms**
  language: und
  media:
    sample count: 0
    timescale:    1000
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 809.950 Kbps
    sample count with fragments: 450
    duration with fragments:     29956
    duration with fragments:     29956 (ms)
  display width:  1920.000000
  display height: 1080.000000
  Sample Description 0
    Coding:       avc1 (H.264)
    Codec String: avc1.4D002A
    AVC Profile:          77 (Main)
    AVC Profile Compat:   0
    AVC Level:            42
    AVC NALU Length Size: 4
    AVC SPS: [674d002a963540f0044fcb3701010102]
    AVC PPS: [68ee31b2]
    Width:       1920
    Height:      1080
    Depth:       24

怎么加上这个呢？最新的代码 ce6f26a64c05f7050cbe29dc6b4e958712a0cbdb

**Comment by ireader** [comment]
fmp4是流式文件，文件中的duration字段写的0， duration值是读的时候计算的。

**Comment by cfgrpg** [comment]
> fmp4是流式文件，文件中的duration字段写的0， duration值是读的时候计算的。

但是这样win10 自带的播放器（电影和电视那个）都不能拖到播放！potpalyer倒是可以拖，希望能在fmp4_writer_destroy前手动调用一个函数，设置下duration吗？

**Comment by ireader** [comment]
如果保存文件可以考虑用mov_writer, 一般生成mp4文件用mov_writer_xxx接口。

**Comment by cfgrpg** [comment]
好的，谢谢！fmp4写占用资源少点，对磁盘友好点吧？本来是打算用fmp4。使用Bento4的工具转出来的fmp4 是有duration的！
File:
  major brand:      mp42
  minor version:    0
  compatible brand: mp42
  compatible brand: isom
  compatible brand: iso5
  fast start:       yes

Movie:
  duration:   29957 (media timescale units)
  duration:   29957 (ms)
  time scale: 1000
  fragments:  yes

Found 2 Tracks
Track 1:
  flags:        7 ENABLED IN-MOVIE IN-PREVIEW
  id:           1
  type:         Video
  duration: 29957 ms
  language: und
  media:
    sample count: 0
    timescale:    90000
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 809.923 Kbps
    sample count with fragments: 450
    duration with fragments:     2696129
    duration with fragments:     29957 (ms)
  display width:  1920.000000
  display height: 1080.000000
  Sample Description 0
    Coding:       avc1 (H.264)
    Codec String: avc1.4D002A
    AVC Profile:          77 (Main)
    AVC Profile Compat:   0
    AVC Level:            42
    AVC NALU Length Size: 4
    AVC SPS: [674d002a963540f0044fcb3701010102]
    AVC PPS: [68ee31b2]
    Width:       1920
    Height:      1080
    Depth:       24
Track 2:
  flags:        7 ENABLED IN-MOVIE IN-PREVIEW
  id:           2
  type:         Audio
  duration: 29888 ms
  language: und
  media:
    sample count: 0
    timescale:    8000
    duration:     0 (media timescale units)
    duration:     0 (ms)
    bitrate (computed): 47.229 Kbps
    sample count with fragments: 468
    duration with fragments:     239104
    duration with fragments:     29888 (ms)
  Sample Description 0
    Coding:       mp4a (MPEG-4 Audio)
    Codec String: mp4a.40.2
    Stream Type: Audio
    Object Type: MPEG-4 Audio
    Max Bitrate: -277040976
    Avg Bitrate: 47229
    Buffer Size: 489
    MPEG-4 Audio Object Type: 2 (AAC Low Complexity)
    MPEG-4 Audio Decoder Config:
      Sampling Frequency: 16000
      Channels: 1
    Sample Rate: 8000
    Sample Size: 16
    Channels:    2

**Comment by ireader** [comment]
- fmp4典型的场景是直播和安防，在这类场景下，文件时长是不可知的，甚至单个文件的duration意义不大。

- libmov 设计时考虑了磁盘性能，有专门的mov-buffer接口。

**Comment by cfgrpg** [comment]
好的，谢谢了，那换mov_writer！
