### ISSUE TITLE
RTP解包相关代码不太明白

### ISSUE THREAD

**Issue by Leonard76152** [ireader/media-server#166]
陈老师，你好。最近在研究RTP代码，看到有些代码不太明白，麻烦抽空帮忙解答一下吧。
1 rtp_packet_t结构体相关内容
顾名思义，这个结构体应该是用来描述RTP数据包的，通过反序列化接收到的原始RTP流得到。
疑问是：
	1.1 在申请的这段内存的前面加上cap和bytes的意义是什么？结构体中的cap和这儿的有什么区别？
	1.2 由于不理解它们的关系，所以对rtp_demuxer_freepkt函数中的比较条件释放内存这块也不明白。
	1.3 这个结构体，使用零长度数组是否可以满足要求。

2 RTP数据的处理：rtp_demuxer_input
	// 2.1 申请pkt内存并解析RTP包进行填充
	pkt = rtp_demuxer_alloc(rtp, data, bytes);
	
	// 2.2 包放入队列，同时进行排序
	r = rtp_queue_write(rtp->queue, pkt);
	
	// 2.3 循环读取包
	pkt = rtp_queue_read(rtp->queue);
	
	// 2.4 对该RTP数据所属的sender进行更新数据
	r = rtp_onreceived(rtp->rtp, pkt + 1, bytes);
	
	// 2.5 对RTP数据进行解码
	r = rtp_payload_decode_input(rtp->payload, pkt + 1, bytes);
	
疑问是：
	2.1 调用了rtp_packet_deserialize
	2.4 调用了rtp_packet_deserialize
	2.5 调用了rtp_packet_deserialize（我看的是h264_unpack）
	既然2.1解析出了pkt，为什么后面不直接传pkt，而是传原始包，然后再进行解析？

**Comment by ireader** [comment]
1. rtp_demuxer_alloc / rtp_demuxer_freepkt 这组函数主要用于减少内存分配，不丢包情况下，rtp_demuxer_input 输入一个包，马上就会回调出去，也就是rtp_demuxer_freepkt 释放的内存马上可以用于保存下一个rtp包，当下一次rtp_demuxer_input时，rtp_demuxer_alloc 通过**cap**判断内存是否足够（不排除某些rtp包会大于1500）。乐观状态下（不丢包）rtp_demuxer内部只需要分配一次内存。

2. rtp packet是一套很复杂的体系（参考webrtc应用场景），各种rtp header扩展五花八门，除非设计出一套很复杂的rtp_packet_t结构，否则没有一套通用的deserialize方案。 为了简化设计，传递原始数据是最通用的（解析本身不怎么耗cpu）。

**Comment by ireader** [comment]
rtp_demuxer_alloc 的核心就是分配一块内存区域，在这块内存的最前面记录这次分配的大小（**对应cap**）。

rtp_demuxer_freepkt 时，定位到内存的起始位置，读取cap值，用于下次alloc时判断内存是否足够。

一般情况下RTP包不会大于一个MTU，但是UDP本身其实也是可以分片的，如果应用层没有按照MTU拆包，接收到的RTP包是可以大于1500.（cap值用于应对这种j极端情况）

**Comment by Leonard76152** [comment]
大体明白了，理解如下：
rtp->cap、rtp->ptr：是用来描述当前可以使用的空闲内存
packet前面插入的那个cap仅仅是描述当前packet的内存大小
1 第一次进入rtp_demuxer_alloc
rtp->cap = 0;
rtp->ptr = NULL;
根据传入的data大小进行分配内存，刚分配的内存由rtp->cap/rtp->ptr描述，
即：
rtp->cap = r;
rtp->ptr = ptr;
而后通过rtp_packet_deserialize创建packet，packet创建成功，则该packet占用了该内存。
则该内存转由packet自身的cap及packet变量来描述。
空闲内存不再存在，即：
rtp->cap = 0; // need more memory
rtp->ptr = NULL;

2 第一次进入rtp_demuxer_freepkt
if(cap <= rtp->cap) // 由于rtp->cap = 0;所以不成立
if(rtp->cap > 0 && rtp->ptr) // 同样不成立
生效的代码只有：
rtp->cap = cap;
rtp->ptr = ptr;
即把刚才分给packet的内存回收，供后续packet使用

3 第二次进入rtp_demuxer_alloc
如果这次的data小于上次的，则不需要再分配内存，直接使用rtp->ptr指向的这片空闲内存即可。
如果大于上次的，则类似于第一次进入。

4 第二次进入rtp_demuxer_freepkt
可能是调用rtp_demuxer_alloc后进入，也可能是循环调用rtp_queue_read后进入。
无论什么情况，该函数条件比较的结果都是：
rtp->cap/rtp->ptr描述当前可用的内存，cap描述当前packet占用的内存。
比较两者内存大小，释放最小的内存，保存最大内存供后续使用，更新rtp->cap/rtp->ptr

5 最后
最后rtp->ptr指向的空闲内存，在rtp_demuxer_destroy中释放
if(rtp->ptr)
    free(rtp->ptr);
	
非常巧妙！
