### ISSUE TITLE
dependencies can't be build for VS 2015

### ISSUE THREAD

**Issue by sasmaster** [ireader/media-server#17]
Hi.So I spent whole evening to build this thing. Media-server lib I built ok. But the 'sdk' on which it depends is not in the operable state. It has a lot of WinAPI old and deprecated functionality which is not even possible to build using Windows 10 SDK. Also its VS solution is broken. At the end I had to manually pull sources and build them,but it didn't work at the end. Total mess. It would be great if you could supply those dependencies as pre-compiled libs, or at least some CMake scripts to builds those properly

**Comment by ireader** [comment]
Add test project(VS2017),   put sdk with media-server same directory.

define _HAVE_FFMPEG_ if you have ffmpeg binary files.

**Comment by ireader** [comment]
"_HAVE_FFMPEG_"

**Comment by sasmaster** [comment]
What version of winsdk do you use?

**Comment by ireader** [comment]
Visual Studio Community 2017
Windows SDK Version: 10.0.16299.0
Windows 10 (1709)
