### ISSUE TITLE
AAC打包MP4中pts部分的代码好像有bug

### ISSUE THREAD

**Issue by Sjianzhao** [ireader/media-server#175]
在  media-server/libmov/test/mov-writer-audio.cpp 文件中
aac_read_frame函数接口处；
每次读取一次音频文件ADTS的时候，在写入pts时，pts好像计算错误了

部分代码

samples += 1024;            // 和下面的 pts += samples * 1000 / rate; 
int framelen = mpeg4_aac_adts_frame_length(ptr, end - ptr);
mov_writer_write(mov, track, ptr + 7, framelen - 7, pts, pts, 0);
pts += samples * 1000 / rate;           // 和上面的  samples += 1024; 
ptr += framelen;

注： pts好像重复累加了

**Comment by ireader** [comment]
1024表示一帧的样本数，后面的1000是时间单位转换，1s = 1000ms

**Comment by Sjianzhao** [comment]
> 
> 
> 1024表示一帧的样本数，后面的1000是时间单位转换，1s = 1000ms

音频帧的播放时间=一个AAC帧对应的采样样本的个数/采样频率(单位为s)
假如现在是第十帧；
samples +=1024；你这里累加，计算之后，sample应该是 10240，代表着是前十帧的样本总和吧；
那么你第十帧的pts 不是应该是 pts = samples * 1000 / rate;  吗？（第十帧的播放时间 = 前十帧对应的采样样本总数 / 采样频率（单位为 S））
然后你这里的 pts += samples * 1000 / rate;   好像是在前面九帧的pts上，在加上前面十帧的dts了



ps:如果我的想法有错，感谢指正！！

**Comment by ireader** [comment]
你是对的
