### ISSUE TITLE
pes->pkt.size == pes->len错误

### ISSUE THREAD

**Issue by alexliyu7352** [ireader/media-server#180]
`Assertion failed: (pes->pkt.size == pes->len), function pes_packet, file /home/alex/CLionProjects/TvCloud/3rdpart/media-server/libmpeg/source/mpeg-packet.c, line 161.`

我是从zlm过来的, 我想请教下, 类似网络问题等导致了中间部分ts包丢失, 那么就会遇到这个断言失败.
往往是pkt.size会大大的超过pes-len.
这样错误发生, 我只有丢弃整个这部分数据么?还是您的库这里能做一些处理?

**Comment by ireader** [comment]
目前TS对丢包没有妥善处置，264、265数据是通过access unit判断帧边界，其它音视频数据就是按照pes->len长度组帧。

在丢包场景下，会有如下2种错误：
1. Assertion failed: (pes->pkt.size == pes->len)
2. H.264/265帧数据不全（或2帧合成了一帧）
