### ISSUE TITLE
如何做到只解ts流, 不管编码

### ISSUE THREAD

**Issue by alexliyu7352** [ireader/media-server#187]
大佬, 如何做到读写只使用ts流, 不管具体编码呢?
我的需求是hls转ts或者ts转hls.
本质上都是mpegts,
如何做到不用管具体的编码, 只是做解封装和封装呢?
因为有一些编码您这不支持, 有一些编码比如一些视频的adts头识别不出来, 但是ffmpeg可以正常播放或者转码.
所以干脆, 能否做到不用管具体的编码, 只是做输入的解封成ts流, 输出的在打包成mpegts流.
不用管ps, es之类的?
请大佬指点下, 应该如何做?

**Comment by ireader** [comment]
不支持的codec，ts解封装出来就是原始数据。 目前只对H.264/H.265有组帧操作，其它全部是按照原始内容输出，不做任何修改。

**Comment by alexliyu7352** [comment]
感谢大佬回复, 也就是说我不用管避免格式, 只要输出的时候原样写入进去就可以了?

**Comment by ireader** [comment]
是的，可以参考下 libmpeg/test/mpeg-ts-test.cpp

**Comment by alexliyu7352** [comment]
好的, 感谢大佬指点.
另外一个问题,

一些流, 采用ffmpeg转发rtmp过来, 参数已经使用了 -bsf:a aac_adtstoasc.
但是mpeg4_aac_adts_load(hex, length, &aac)总是失败怎么办?

**Comment by ireader** [comment]
asc已经没有adts头了，不能调用mpeg4_aac_adts_load

**Comment by alexliyu7352** [comment]
那怎么办?推流时候ffmpeg要求添加这个参数

Chen ***@***.***> 于2022年1月7日周五 11:50写道：

**Comment by alexliyu7352** [comment]
那我怎么生成adts头呢?

alex lee ***@***.***> 于2022年1月7日周五 12:45写道：

**Comment by ireader** [comment]
flv/mp4文件里的aac音频是不含adts头的。转换ts可以从libflv/libmov/lihls 这几个目录下找找使用例子。

**Comment by alexliyu7352** [comment]
大佬, 还有一个问题
我读取一个mpegts流,
static int on_ts_packet(void* ts, int program, int stream, int avtype, int
flags, int64_t pts, int64_t dts, const void* data, size_t bytes)
这里的flags一直等于0为什么?
这个参数表示的是关键帧吧?为何一直等于0?

Chen ***@***.***> 于2022年1月7日周五 14:13写道：

**Comment by ireader** [comment]
这个flags是从TS包里读的，并没有探测数据，如果写TS时没有设置关键帧标记，读出来就一直是0.

这个flags只能用来参考，不代表真实类型。

**Comment by alexliyu7352** [comment]
那如果这样, 直接读取, 然后在写入的时候就丢失了关键帧了?

Chen ***@***.***> 于2022年1月7日周五 14:45写道：
