### ISSUE TITLE
test编译错误

### ISSUE THREAD

**Issue by as346697981** [ireader/media-server#195]
1、分支:Master
2、运行环境：Ubuntu 16.04    gcc 5.4.0

> test.cpp:123:25: error: pasting "amf0_test" and "(" does not give a valid preprocessing token
 extern "C" DEF_FUN_VOID(amf0_test);
                         ^
test.cpp:44:41: note: in definition of macro ‘DEF_FUN_VOID2’
 #define DEF_FUN_VOID2(name, param) void name ## param; \
                                         ^
test.cpp:123:12: note: in expansion of macro ‘DEF_FUN_VOID’
 extern "C" DEF_FUN_VOID(amf0_test);
            ^
test.cpp:124:25: error: pasting "rtp_queue_test" and "(" does not give a valid preprocessing token
 extern "C" DEF_FUN_VOID(rtp_queue_test);
                         ^
test.cpp:44:41: note: in definition of macro ‘DEF_FUN_VOID2’
 #define DEF_FUN_VOID2(name, param) void name ## param; \
                                         ^
test.cpp:124:12: note: in expansion of macro ‘DEF_FUN_VOID’
 extern "C" DEF_FUN_VOID(rtp_queue_test);
            ^
test.cpp:125:25: error: pasting "mpeg4_aac_test" and "(" does not give a valid preprocessing token
 extern "C" DEF_FUN_VOID(mpeg4_aac_test);
                         ^
test.cpp:44:41: note: in definition of macro ‘DEF_FUN_VOID2’
 #define DEF_FUN_VOID2(name, param) void name ## param; \
                                         ^
test.cpp:125:12: note: in expansion of macro ‘DEF_FUN_VOID’
 extern "C" DEF_FUN_VOID(mpeg4_aac_test);
            ^
test.cpp:126:25: error: pasting "mpeg4_avc_test" and "(" does not give a valid preprocessing token
 extern "C" DEF_FUN_VOID(mpeg4_avc_test);
                         ^
test.cpp:44:41: note: in definition of macro ‘DEF_FUN_VOID2’
 #define DEF_FUN_VOID2(name, param) void name ## param; \
                                         ^
test.cpp:126:12: note: in expansion of macro ‘DEF_FUN_VOID’
 extern "C" DEF_FUN_VOID(mpeg4_avc_test);
            ^
test.cpp:127:25: error: pasting "mpeg4_hevc_test" and "(" does not give a valid preprocessing token
 extern "C" DEF_FUN_VOID(mpeg4_hevc_test);
                         ^
test.cpp:44:41: note: in definition of macro ‘DEF_FUN_VOID2’
 #define DEF_FUN_VOID2(name, param) void name ## param; \
                                         ^
test.cpp:127:12: note: in expansion of macro ‘DEF_FUN_VOID’
 extern "C" DEF_FUN_VOID(mpeg4_hevc_test);
            ^
test.cpp:128:25: error: pasting "mp3_header_test" and "(" does not give a valid preprocessing token
 extern "C" DEF_FUN_VOID(mp3_header_test);
                         ^
test.cpp:44:41: note: in definition of macro ‘DEF_FUN_VOID2’
 #define DEF_FUN_VOID2(name, param) void name ## param; \
                                         ^
test.cpp:128:12: note: in expansion of macro ‘DEF_FUN_VOID’
 extern "C" DEF_FUN_VOID(mp3_header_test);
            ^
test.cpp:129:25: error: pasting "sdp_a_fmtp_test" and "(" does not give a valid preprocessing token
 extern "C" DEF_FUN_VOID(sdp_a_fmtp_test);
                         ^
test.cpp:44:41: note: in definition of macro ‘DEF_FUN_VOID2’
 #define DEF_FUN_VOID2(name, param) void name ## param; \
                                         ^
test.cpp:129:12: note: in expansion of macro ‘DEF_FUN_VOID’
 extern "C" DEF_FUN_VOID(sdp_a_fmtp_test);
            ^
test.cpp:130:25: error: pasting "sdp_a_rtpmap_test" and "(" does not give a valid preprocessing token
 extern "C" DEF_FUN_VOID(sdp_a_rtpmap_test);
                         ^

**Comment by Dw9** [comment]
hi @as346697981 
test.cpp全局替换一下 name ##  --> name 
上次提交不完全
