### ISSUE TITLE
hls_playlist_parse崩溃

### ISSUE THREAD

**Issue by Wesley329** [ireader/media-server#198]
解析https://v8.dious.cc/20210429/PQW7vQ1G/index.m3u8文件时候，重复调用hls_playlist_parse接口，发现linux下崩溃不多，windows下崩溃频繁，但也是随机的，而且崩溃问题都出现在对key结构访问的时候，是不是hls_playlist_t中segments的key结构读写有问题？？？
直接调用hls_parser_test也能复现这个问题，代码如下：
    for(int i = 0; i < 1000; i++)
    {
        hls_parser_test(“test.m3u8”);
        printf("loop count %d\n", i + 1);
    }
    
[test.zip](https://github.com/ireader/media-server/files/7962923/test.zip)

**Comment by ireader** [comment]
本地循环执行hls_parser_test 1w次，未复现你的问题。  

贴下崩溃堆栈？

**Comment by Wesley329** [comment]
测试发现应该是我本地环境调用引发的偶发性崩溃问题，感谢回复！
