### ISSUE TITLE
libhls 按照说明编译demo编译不了

### ISSUE THREAD

**Issue by jingith** [ireader/media-server#20]
make -C sdk/libaio && make -C sdk/libhttp && make -C media-server/libmpeg && make -C media-server/libflv && make -C media-server/libhls

gcc -I. -I./include -I../include -DOS_LINUX -DDEBUG -D_DEBUG -Wall -fPIC -g -Wall -fvisibility=hidden -fvisibility=default -c -MMD -MP -MF debug.linux/aio-connect.d -o src/aio-connect.o src/aio-connect.c
In file included from ../include/sockutil.h:4:0,
                 from src/aio-connect.c:6:
../include/sys/sock.h: 在函数‘socket_select_read’中:
../include/sys/sock.h:427:16: 错误：‘fds’的存储大小未知
  struct pollfd fds;
                ^
../include/sys/sock.h:430:15: 错误：‘POLLIN’未声明(在此函数内第一次使用)
  fds.events = POLLIN;
               ^
../include/sys/sock.h:430:15: 附注：每个未声明的标识符在其出现的函数内只报告一次
../include/sys/sock.h:433:2: 警告：隐式声明函数‘poll’ [-Wimplicit-function-declaration]
  r = poll(&fds, 1, timeout);
  ^
../include/sys/sock.h:427:16: 警告：未使用的变量‘fds’ [-Wunused-variable]
  struct pollfd fds;
                ^
../include/sys/sock.h: 在函数‘socket_select_write’中:
../include/sys/sock.h:456:16: 错误：‘fds’的存储大小未知
  struct pollfd fds;
                ^
../include/sys/sock.h:459:15: 错误：‘POLLOUT’未声明(在此函数内第一次使用)
  fds.events = POLLOUT;
               ^
../include/sys/sock.h:456:16: 警告：未使用的变量‘fds’ [-Wunused-variable]
  struct pollfd fds;
                ^
../include/sys/sock.h: 在函数‘socket_addr_compare’中:
../include/sys/sock.h:984:45: 错误：invalid application of ‘sizeof’ to incomplete type ‘struct sockaddr_un’
  case AF_UNIX: return memcmp(sa, sb, sizeof(struct sockaddr_un));
                                             ^

**Comment by ireader** [comment]
在windows上编译的？

**Comment by jingith** [comment]
centos 7

**Comment by ireader** [comment]
改了些编译错误问题，更新 media-server & sdk 项目

**Comment by jingith** [comment]
make -C sdk/libaio && make -C sdk/libhttp && make -C media-server/libmpeg && make -C media-server/libflv && make -C media-server/libhls
gcc -I. -I./include -I../include -DOS_LINUX -DDEBUG -D_DEBUG -Wall -fPIC -g -Wall -fvisibility=hidden -fvisibility=default -c -MMD -MP -MF debug.linux/aio-accept.d -o src/aio-accept.o src/aio-accept.c
In file included from src/aio-accept.c:2:
../include/sys/locker.h:39:35: error: use of undeclared identifier 'PTHREAD_MUTEX_RECURSIVE_NP'
        pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE_NP);
                                         ^
1 error generated.

**Comment by jingith** [comment]
1. 从github下载依赖的sdk目录，与media-server平级
   git clone https://github.com/ireader/sdk sdk

2. 分别编译libaio/libhttp/libmpeg/libflv/libhls
   make -C sdk/libaio && make -C sdk/libhttp && make -C media-server/libmpeg && make -C media-server/libflv && make -C media-server/libhls

3. cd media-server/libhls/test目录下执行make

4. ./debug.linux/hls-server
====================================
第三部没有测试代码， 请作者提供一份，cd media-server/libhls/test
