### ISSUE TITLE
又要请求大佬了, 为何输出的ts流没有sps,pps.

### ISSUE THREAD

**Issue by alexliyu7352** [ireader/media-server#201]
不好意思, 又要麻烦大佬指点一下了.
我是从hls转ts流.不想解析ps流, 只是想要在ts层重新打包.
测试流是网上随便找的一个m3u8直播流
http://39.135.138.59:18890/PLTV/88888910/224/3221225633/index.m3u8

当我通过http获取每个分片ts数据后, 大概通过如下流程来使用.

```
ts_demuxer_input(_demuxer_ctx, (uint8_t *) data, bytes);

_demuxer_ctx = ts_demuxer_create([](void* param, int program, int stream, int codecid, int flags, int64_t pts, int64_t dts, const void* data, size_t bytes){
        TSDecoder *thiz = (TSDecoder*)param;
        if(thiz->_on_decode){
            if(flags != MPEG_FLAG_PACKET_CORRUPT) {
                thiz->_on_decode(stream, codecid, flags, pts, dts, data, bytes);
            }
        }
        return 0;
    },this);

    ts_demuxer_notify_t notify = {
            [](void *param, int stream, int codecid, const void *extra, int bytes, int finish) {
                TSDecoder *thiz = (TSDecoder *) param;
                if (thiz->_on_stream) {
                    thiz->_on_stream(stream, codecid, extra, bytes, finish);
                }
            }
    };
    ts_demuxer_set_notify((struct ts_demuxer_t *) _demuxer_ctx, &notify, this);
```

然后回调_on_decode与_on_stream来产生视频和音频的tracker与frame.

onDecode(int stream,int codecid,int flags,int64_t pts,int64_t dts,const void *data,size_t bytes) 
这里每次回调都会生成一个frame, 包含有参数的这些数据.
这里我发现flags不会返回1, 也就是只是在ts层没办法确定关键帧.

然后调用
mpeg_muxer_input(_context, track_id, _key_pos ? 0x0001 : 0, pts64 * 90LL,dts64 * 90LL, frame->data(), frame->size());
得到packet包, 最终输出.

最终输出的ts流, ffplay播放时, 会间歇性花屏, 而且音频不同步.
是否是我哪里做错了?还是只是对ts层解复用, 不能做到hls转ts输出?

请求大佬指教

**Comment by ireader** [comment]
1. flags是根据ts内部data_alignment_indicator值获取的，不能用来判断是否关键帧，只能用作参考。
``` pes->flags |= pes->data_alignment_indicator ? MPEG_FLAG_IDR_FRAME : 0; ```

2. ts_demuxer_create回调的音视频时间戳要除90才是原始时间戳。 花屏和不同步问题可以把时间戳输出看看，确认时间戳是否连续。

**Comment by alexliyu7352** [comment]
已经有除以90的, 只是代码没贴.

大佬也就是说我这个流程是没问题的是吧?

**Comment by alexliyu7352** [comment]
在不做ps流的解复用, 也就是涉及264,265编码之类的.
仅仅只是对ts流解复用, 应该就可以转封装了吧?

**Comment by ireader** [comment]
流程看上去没有问题，麻烦上传原ts文件和生成的ps文件

**Comment by alexliyu7352** [comment]
源文件就是这个地址
http://39.135.138.59:18890/PLTV/88888910/224/3221225633/index.m3u8

生成的文件我邮件发给您

**Comment by alexliyu7352** [comment]
大佬, 不用麻烦了, 解决了.
使用了您的avtimeline就好了, 应该是时间戳重复了.

再次给大佬点赞!!!!

Chen ***@***.***> 于2022年2月21日周一 16:56写道：

**Comment by alexliyu7352** [comment]
另外请教下, 
现在我是使用了avtimeline保证写入的ts都是正确的dts.
是否我可以使用avdtsinfer.h在ts_demuxer_create的回调中.
是否效果比写入时使用avtimeline要好?

**Comment by ireader** [comment]
avdtsinfer.h 是根据pts重新计算dts。 avtimeline是时间戳映射，本质是时间戳加偏移量。 你的场景下应该不需要计算dts？

**Comment by alexliyu7352** [comment]
理论上应该不需要, 但是输出的流中会有dts重复, 音频我看打印的会有出现回退

Chen ***@***.***> 于2022年2月21日周一 19:13写道：

**Comment by alexliyu7352** [comment]
```
2022-02-24 02:36:39.540 W  [video]pts-->8143402    dts-->8143402  size:1090
2022-02-24 02:36:39.540 E  [video new]pts-->334    dts-->334  size:1090
2022-02-24 02:36:39.691 W  [video]pts-->8143436    dts-->8143436  size:819
2022-02-24 02:36:39.691 E  [video new]pts-->334    dts-->334  size:819
2022-02-24 02:36:39.691 W  [video]pts-->8143669    dts-->8143569  size:12483
2022-02-24 02:36:39.691 E  [video new]pts-->534    dts-->434  size:12483
2022-02-24 02:36:39.691 W  [video]pts-->8143502    dts-->8143502  size:694
2022-02-24 02:36:39.691 E  [video new]pts-->434    dts-->434  size:694
2022-02-24 02:36:39.840 W  [video]pts-->8143536    dts-->8143536  size:855
2022-02-24 02:36:39.840 E  [video new]pts-->434    dts-->434  size:855
2022-02-24 02:36:39.841 W  [video]pts-->8143769    dts-->8143669  size:3694
2022-02-24 02:36:39.841 E  [video new]pts-->634    dts-->534  size:3694
2022-02-24 02:36:39.841 W  [video]pts-->8143602    dts-->8143602  size:395
2022-02-24 02:36:39.841 E  [video new]pts-->534    dts-->534  size:395
2022-02-24 02:36:39.941 W  [video]pts-->8143636    dts-->8143636  size:410
2022-02-24 02:36:39.941 E  [video new]pts-->534    dts-->534  size:410
2022-02-24 02:36:39.941 W  [video]pts-->8143869    dts-->8143769  size:12404
2022-02-24 02:36:39.941 E  [video new]pts-->734    dts-->634  size:12404
```

大佬请看上面打印的日志
我遇到的这个视频会有dts回退的情况.
比如这个
[video]pts-->8143669    dts-->8143569  size:12483
下面的dts就回退了
[video]pts-->8143502    dts-->8143502  size:694

因此我使用您的avtimeline_input32输出的dts并没有单调递增了, 变成了重复的
2022-02-24 02:36:39.691 E  [video new]pts-->534    dts-->434  size:12483
2022-02-24 02:36:39.691 E  [video new]pts-->434    dts-->434  size:694

根据您的代码如果我把avtimeline_init(_timeline, 5000, 0);中的gap设置为0到是可以保证视频的dts都是单调递增的.
但是输出的音频就不同步了, 而且也不能单调递增.

我应该怎么做才能让乱序的dts源输出ts的时候dts是会镇正确单调递增.


我的代码

 ```
auto cts32 = (int32_t)(pts - dts);
int64_t dts64 = avtimeline_input32(_timeline, 0, dts, &vd);
int64_t pts64 = dts64 + cts32;
_timestamp = dts64;
ErrorL << "[video new]pts-->" << pts64 << "    dts-->" << dts64 << "  size:" << buffer->size();
mpeg_muxer_input(_context, track_id, have_idr ? 0x0001 : 0, pts64 * 90LL,dts64 * 90LL, buffer->data(), buffer->size());
```

**Comment by ireader** [comment]
```
2022-02-24 02:36:39.540 W  [video]pts-->8143402    dts-->8143402  size:1090
** 2022-02-24 02:36:39.540 E  [video new]pts-->334    dts-->334  size:1090 **
2022-02-24 02:36:39.691 W  [video]pts-->8143436    dts-->8143436  size:819
** 2022-02-24 02:36:39.691 E  [video new]pts-->334    dts-->334  size:819 **
```

在输入dts不重复的情况下，输出dts-->334重复了，这个结果不符合预期。
``` int64_t dts64 = avtimeline_input32(_timeline, 0, dts, &vd);```
这个timeline只用于视频吗？ 看你第二个参数直接写死的0，音频时间戳没有处理？

音视频同时基于timeline用法：
``` 
int64_t dts64 = avtimeline_input32(_timeline, 0, video_dts, &vd);
int64_t dts64 = avtimeline_input32(_timeline, 1, audio_dts, &ad);
```

另外其它输出的值也不太符合预期，一般情况下不要调用avtimeline_init、avtimeline_reset。

**Comment by alexliyu7352** [comment]
不, 音频也有处理的.timeline肯定是音频视频一起用的. 抱歉,我代码没有贴全.
第二个参数写死, 是因为音频视频是分开处理的, 所以一个是0, 一个是1

视频的
```
auto cts32 = (int32_t)(frame->pts() - frame->dts());
int64_t dts64 = avtimeline_input32(_timeline, 0, frame->dts(), &vd);
int64_t pts64 = dts64 + cts32;
_timestamp = dts64;
mpeg_muxer_input((::mpeg_muxer_t *)_context, track_id, _key_pos ? 0x0001 : 0, pts64 * 90LL,dts64 * 90LL, frame->data(), frame->size());
```


音频的
```

auto cts32 = (int32_t)(frame->pts() - frame->dts());
  int64_t dts64 = avtimeline_input32(_timeline, 1, frame->dts(), &ad);
  int64_t pts64 = dts64 + cts32;

  _max_cache_size = 512 + 1.2 * frame->size();
  mpeg_muxer_input((::mpeg_muxer_t *)_context, track_id, frame->keyFrame() ? 0x0001 : 0, pts64 * 90LL, dts64 * 90LL, frame->data(), frame->size());
```

avtimeline_init只调用一次, 然后就再也没有调用了

```
if(_timeline==nullptr){
            _timeline = (avtimeline_t *) malloc(sizeof(avtimeline_t));
            avtimeline_init(_timeline, 5000, 0);
        }
```

**Comment by alexliyu7352** [comment]
> ```
> 2022-02-24 02:36:39.540 W  [video]pts-->8143402    dts-->8143402  size:1090
> ** 2022-02-24 02:36:39.540 E  [video new]pts-->334    dts-->334  size:1090 **
> 2022-02-24 02:36:39.691 W  [video]pts-->8143436    dts-->8143436  size:819
> ** 2022-02-24 02:36:39.691 E  [video new]pts-->334    dts-->334  size:819 **
> ```
> 
> 在输入dts不重复的情况下，输出dts-->334重复了，这个结果不符合预期。 ` int64_t dts64 = avtimeline_input32(_timeline, 0, dts, &vd);` 这个timeline只用于视频吗？ 看你第二个参数直接写死的0，音频时间戳没有处理？
> 
> 音视频同时基于timeline用法：
> 
> ```
> int64_t dts64 = avtimeline_input32(_timeline, 0, video_dts, &vd);
> int64_t dts64 = avtimeline_input32(_timeline, 1, audio_dts, &ad);
> ```
> 
> 另外其它输出的值也不太符合预期，一般情况下不要调用avtimeline_init、avtimeline_reset。

我看您的代码中avtimeline_input32具体实现逻辑里面有判断, 回退时会返回上一次的dts.所以输出的会有重复的dts.
因为这个流的视频的时间戳会回退.
但是在使用ffplay播放或者ffmpeg转码都是没问题的.
只是会提示Non-increasing DTS in stream 1

**Comment by ireader** [comment]
avtimeline没有考虑dts revert的情况，可以修改代码试试：

```
diff --git "a/avcodec/source/avtimeline.c" "b/avcodec/source/avtimeline.c"
index ec8f613..ae20324 100644
--- "a/avcodec/source/avtimeline.c"
+++ "b/avcodec/source/avtimeline.c"
@@ -114,7 +114,7 @@ int64_t avtimeline_input32(struct avtimeline_t* t, int stream, uint32_t dts, int
 
 	t->streams[stream].t = timestamp;
 
-	t->streams[stream].repeat = (0 == diff && init) ? t->streams[stream].repeat + 1 : 0;
+	t->streams[stream].repeat = (0 == *discontinuity && diff <= 0 && init) ? t->streams[stream].repeat + 1 : 0;
 	timestamp += t->streams[stream].repeat; // monotone increasing timestamp
 	return timestamp;
 }
@@ -172,7 +172,7 @@ int64_t avtimeline_input64(struct avtimeline_t* t, int stream, int64_t dts, int*
 
 	t->streams[stream].t = timestamp;
 
-	t->streams[stream].repeat = (0 == diff && init) ? t->streams[stream].repeat + 1 : 0;
+	t->streams[stream].repeat = (0 == *discontinuity && diff <= 0 && init) ? t->streams[stream].repeat + 1 : 0;
 	timestamp += t->streams[stream].repeat; // monotone increasing timestamp
 	return timestamp;
 }
@@ -313,6 +313,20 @@ static void avtimeline_monotone_increment_test(void)
 	assert(timestamp + 10 == avtimeline_input32(&line, 0, dts+10, &discontinuity));
 }
```

**Comment by alexliyu7352** [comment]
您觉得我是在出书ts时候使用avtimeline_input32重新生成dts还是在ts_demuxer_create回调时直接重新生成dts?

Chen ***@***.***> 于2022年2月24日周四 13:22写道：

**Comment by ireader** [comment]
http://39.135.138.59:18890/PLTV/88888910/224/3221225633/index.m3u8
这个源不是每个ts文件时间戳都有回退吧，上传一个有时间戳回退的ts文件，我分析分析。

**Comment by alexliyu7352** [comment]
不是, 是偶然会出现的.

Chen ***@***.***> 于2022年2月24日周四 20:51写道：

**Comment by alexliyu7352** [comment]
那我找找, 一般都是偶然会遇到这样的流.


alex lee ***@***.***> 于2022年2月24日周四 21:02写道：

**Comment by alexliyu7352** [comment]
我测试的源失效了, 等等我找到了在跟您反馈.
因为测试的源都是网络上找到的

**Comment by alexliyu7352** [comment]
avtimeline
发现一个问题, 有时会造成输出的音视频不同步.

**Comment by ireader** [comment]
音视频时间戳相差多少， 有没有对应的时间戳调整日志？

avtimeline 5月28号有个更新，不再强制音视频从0开始，可以更新这个版本试试。
