### ISSUE TITLE
h264裸数据保存ts文件，vlc不能播放，ffplay可以，也汇报一些错误

### ISSUE THREAD

**Issue by LiuAriel** [ireader/media-server#203]
目前现象vlc不能播放，查看媒体信息，没有任何信息
ffplay可以播放，也有媒体信，但是还是有问题，日志如下：
[mpegts @ 000002baa932c340] start time for stream 0 is not set in estimate_timings_from_pts
[mpegts @ 000002baa932c340] Could not find codec parameters for stream 0 (Video: mpeg2video ([1][0][0][0] / 0x0001), none(tv)): unspecified size
Consider increasing the value for the 'analyzeduration' and 'probesize' options
Input #0, mpegts, from 'C:\Users\anker\Desktop\test.ts.ts':
  Duration: 00:00:18.85, start: 0.000000, bitrate: 171 kb/s
  Program 1
    Metadata:
      service_name    : ireader/media-server
      service_provider: encoder
    Stream #0:0[0x101]: Video: mpeg2video ([1][0][0][0] / 0x0001), none(tv), 90k tbr, 90k tbn, 90k tbc
    Stream #0:1[0x102]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn, 180k tbc
[swscaler @ 000002bab1dd49c0] deprecated pixel format used, make sure you did set range correctly
  12.41 M-V:  0.001 fd=   0 aq=    0KB vq=   45KB sq=    0B f=0/0

调用逻辑：
1、mpeg_ts_create创建成功
2、mpeg_ts_add_stream
3、mpeg_ts_write，pts、dts都是第一帧开始递增*90，并得到第一个IDR视频数据才写数据
4、mpeg_ts_destroy目前调用会crash，不知道是不是与这个有关系

文件如下，上传限制，请下载后修改后缀名：
[test.ts.txt](https://github.com/ireader/media-server/files/8161460/test.ts.txt)

**Comment by ireader** [comment]
感谢反馈！

从test.ts文件读取的PMT包含2个流，也就是ffmpeg打印的如下信息：
Stream #0:0[0x101]: Video: mpeg2video ([1][0][0][0] / 0x0001), none(tv), 90k tbr, 90k tbn, 90k tbc
Stream #0:1[0x102]: Video: h264 (High) ([27][0][0][0] / 0x001B), yuvj420p(pc, bt709, progressive), 1920x1080, 15 fps, 15 tbr, 90k tbn, 180k tbc

vlc可以选择track2播放
![image](https://user-images.githubusercontent.com/1535445/156168096-c5ec176c-f865-47f9-86a6-6bd72a5648da.png)


请确认是否调用了2次mpeg_ts_add_stream。

**Comment by LiuAriel** [comment]
确实多调用了mpeg_ts_add_stream， 但是现在mpeg_ts_destroy目前调用会crash！  请问释放的时候，必须保证mpeg_ts_write没有被用才可以？

**Comment by ireader** [comment]
涉及到多线程使用，需要加锁，保证mpeg_ts_destroy后不再调用其它接口。

**Comment by LiuAriel** [comment]
我也刚想到枷锁，非常感谢！
