### ISSUE TITLE
rtsp_client_play 拼接 Speed字段时，会丢失\r\n

### ISSUE THREAD

**Issue by yplypl** [ireader/media-server#208]
rtsp client里面的char speed[16] 字段只有16位长，
![image](https://user-images.githubusercontent.com/6971032/160345406-5661fcf0-c537-41c6-888b-42ebdef17a96.png)

我在windows下看会显示小数点后面6位，因此/r/n就不见了引起rtsp头格式错误。

![image](https://user-images.githubusercontent.com/6971032/160345093-2d2669fc-352f-486d-b045-ce85364bca79.png)

**Comment by ireader** [comment]
感谢！

可以限定speed精度：
r = speed ? snprintf(rtsp->speed, sizeof(rtsp->speed), "Speed: %.2f\r\n", *speed) : 0;

**Comment by ireader** [comment]
rtsp->range有判断snprintf的返回值，漏掉了speed的判断。

**Comment by yplypl** [comment]
> 感谢！
> 
> 可以限定speed精度： r = speed ? snprintf(rtsp->speed, sizeof(rtsp->speed), "Speed: %.2f\r\n", *speed) : 0;

哈哈，我也是先这样修改的。
