### ISSUE TITLE
ts文件视频时长出现问题

### ISSUE THREAD

**Issue by hany-dev** [ireader/media-server#212]
感谢大佬的项目，真的很厉害，
问题：运行zlmediakit时，生成了一个hls文件，文件的最后一个ts文件的时长为9秒，但是在使用vlc播放时，却显示51分钟。在播放到第9秒后，直接跳到了末尾，采用potplayer播放时，可以正确解析出视频长度，采用ffmpeg对视频包进行分析，发现最后有两个packet出现了错误，现将截图和视频文件上传到文末
请教大佬这个视频存在什么问题？烦请大佬有空的时候，看一下这个视频文件，帮忙解答一下，十分感谢
![图片](https://user-images.githubusercontent.com/39269298/162410348-22e53aaf-c398-4e14-9bc5-11e2cd54f72b.png)
[01-44_479.zip](https://github.com/ireader/media-server/files/8450689/01-44_479.zip)

**Comment by ireader** [comment]
从时间戳没有发现异常，但是这个文件后面数据出现了错误：
![image](https://user-images.githubusercontent.com/1535445/162451567-abb27464-fd0c-4fcd-845f-1eaa8670eefa.png)

不能排查错误数据导致vlc解析时间长度异常。
