### ISSUE TITLE
rtcp 抓包发现一个sdes的包长度为15，lenght为3的时候，asssert报告异常。

### ISSUE THREAD

**Issue by yplypl** [ireader/media-server#216]
抓包截图：
![image](https://user-images.githubusercontent.com/6971032/166098769-d00a9a24-71ce-4eb7-9c95-28ffab0dbe0a.png)
rtcp.c的136行，我先把这个长度检查的注释掉了，程序正常。
![image](https://user-images.githubusercontent.com/6971032/166098862-f662a294-3013-402b-9446-431f59aa7490.png)

对于rtcp不是特别熟悉，不清楚到底是对方的包不符合标准，还是我们程序检测逻辑有问题，还请大佬分析下具体情况。

**Comment by yplypl** [comment]
附：抓包 [mse程序点播失败抓包.zip](https://github.com/ireader/media-server/files/8596487/mse.zip)

**Comment by ireader** [comment]
从抓包数据看，对方少发了一个字节

**Comment by ireader** [comment]
从抓包数据看，对方少发了一个字节
