### ISSUE TITLE
link error 

### ISSUE THREAD

**Issue by xiaozhang8tuo** [ireader/media-server#227]
g++ -o debug.linux/test -Wl,-rpath
/../../sdk/libhttp/test/http-list-dir.cpp:32: undefined reference to `dir_list'
报错丢失引用

g++ -o debug.linux/test -Wl,-rpath .  debug.linux/objs/./BinaryDiff.o debug.linux/objs/./test.o debug.linux/objs/../../sdk/libhttp/test/http-client-test.o debug.linux/objs/../../sdk/libhttp/test/http-list-dir.o debug.linux/objs/../../sdk/libhttp/test/http-client-test2.o debug.linux/objs/../../sdk/libhttp/test/http-server-test.o debug.linux/objs/../../sdk/libhttp/test/http-client-test3.o debug.linux/objs/../libmpeg/test/mpeg-ps-test.o debug.linux/objs/../libmpeg/test/mpeg-ps-dec-test.o debug.linux/objs/../libmpeg/test/mpeg-ts-encrypt-test.o debug.linux/objs/../libmpeg/test/mpeg-ts-test.o debug.linux/objs/../libmpeg/test/mpeg-ts-dec-test.o debug.linux/objs/../libmpeg/test/flv-2-mpeg-ps-test.o debug.linux/objs/../libmpeg/test/mpeg-ts-multi-program-test.o debug.linux/objs/../libhls/demo/hls-segmenter-mp4.o debug.linux/objs/../libhls/demo/hls-server.o debug.linux/objs/../libhls/demo/hls-segmenter-flv.o debug.linux/objs/../libdash/test/dash-dynamic-test.o debug.linux/objs/../libdash/test/dash-static-test.o debug.linux/objs/../libmov/test/mov-reader-test.o debug.linux/objs/../libmov/test/mov-writer-av1.o debug.linux/objs/../libmov/test/mov-writer-h264.o debug.linux/objs/../libmov/test/mov-2-flv.o debug.linux/objs/../libmov/test/mov-writer-audio.o debug.linux/objs/../libmov/test/mov-writer-h265.o debug.linux/objs/../libmov/test/fmp4-writer-test.o debug.linux/objs/../libmov/test/mov-writer-subtitle.o debug.linux/objs/../libmov/test/mov-writer-adts.o debug.linux/objs/../libmov/test/mov-writer-test.o debug.linux/objs/../libmov/test/fmp4-writer-test2.o debug.linux/objs/../libflv/test/h265-flv-test.o debug.linux/objs/../libflv/test/flv2ts-test.o debug.linux/objs/../libflv/test/flv-parser-test.o debug.linux/objs/../libflv/test/av1-flv-test.o debug.linux/objs/../libflv/test/ts2flv-test.o debug.linux/objs/../libflv/test/flv-reader-test.o debug.linux/objs/../libflv/test/http-flv-live.o debug.linux/objs/../libflv/test/h264-flv-test.o debug.linux/objs/../libflv/test/flv-read-write-test.o debug.linux/objs/../librtmp/test/rtmp-server-publish-benchmark.o debug.linux/objs/../librtmp/test/rtmp-play-test.o debug.linux/objs/../librtmp/test/rtmp-server-publish-test.o debug.linux/objs/../librtmp/test/rtmp-server-input-test.o debug.linux/objs/../librtmp/test/rtmp-chunk-test.o debug.linux/objs/../librtmp/test/rtmp-server-vod-test.o debug.linux/objs/../librtmp/test/rtmp-play-aio-test.o debug.linux/objs/../librtmp/test/rtmp-server-publish-aio-test.o debug.linux/objs/../librtmp/test/rtmp-publish-test.o debug.linux/objs/../librtmp/test/rtmp-input-test.o debug.linux/objs/../librtmp/test/rtmp-server-vod-aio-test.o debug.linux/objs/../librtmp/test/rtmp-publish-aio-test.o debug.linux/objs/../librtmp/test/rtmp-server-forward-aio-test.o debug.linux/objs/../librtp/test/rtp-payload-test.o debug.linux/objs/../librtp/test/mov-rtp-test.o debug.linux/objs/../librtp/test/av1-rtp-test.o debug.linux/objs/../librtp/test/rtp-queue-test.o debug.linux/objs/../librtp/test/rtp-dump-replay.o debug.linux/objs/../librtp/test/rtp-dump-test.o debug.linux/objs/../librtp/test/rtp-sender-test.o debug.linux/objs/../librtsp/test/sdp-receiver-test.o debug.linux/objs/../librtsp/test/sdp-test.o debug.linux/objs/../librtsp/test/rtsp-push-server.o debug.linux/objs/../librtsp/test/rtp-streaming-test.o debug.linux/objs/../librtsp/test/rtp-udp-transport.o debug.linux/objs/../librtsp/test/rtsp-client-push-test.o debug.linux/objs/../librtsp/test/rtsp-server-test.o debug.linux/objs/../librtsp/test/rtsp-client-input-test.o debug.linux/objs/../librtsp/test/rtsp-demuxer-test.o debug.linux/objs/../librtsp/test/media/ps-file-source.o debug.linux/objs/../librtsp/test/media/h264-file-source.o debug.linux/objs/../librtsp/test/media/vod-file-source.o debug.linux/objs/../librtsp/test/media/mp4-file-source.o debug.linux/objs/../librtsp/test/media/h265-file-source.o debug.linux/objs/../librtsp/test/media/avpacket-queue.o debug.linux/objs/../librtsp/test/media/h264-file-reader.o debug.linux/objs/../librtsp/test/media/mp4-file-reader.o debug.linux/objs/../librtsp/test/media/pcm-file-source.o debug.linux/objs/../librtsp/test/media/ffmpeg-file-source.o debug.linux/objs/../librtsp/test/media/ffmpeg-live-source.o debug.linux/objs/../librtsp/test/media/h265-file-reader.o debug.linux/objs/../libsip/test/sip-uas-message-test.o debug.linux/objs/../libsip/test/sip-uac-message-test.o debug.linux/objs/../libsip/test/sip-uac-test.o debug.linux/objs/../libsip/test/sip-message-test.o debug.linux/objs/../libsip/test/sip-agent-test.o debug.linux/objs/../libsip/test/sip-uas-test.o debug.linux/objs/../libsip/test/sip-uas-test2.o debug.linux/objs/../libsip/test/sip-uac-test2.o debug.linux/objs/../../sdk/source/digest/sha384-512.o debug.linux/objs/../../sdk/source/digest/sha1.o debug.linux/objs/../../sdk/source/digest/crc32.o debug.linux/objs/../../sdk/source/digest/sha224-256.o debug.linux/objs/../../sdk/source/digest/hmac.o debug.linux/objs/../../sdk/source/digest/sha.o debug.linux/objs/../../sdk/source/digest/md5.o debug.linux/objs/../../sdk/source/digest/hkdf.o debug.linux/objs/../../sdk/libhttp/test/benchmark.o debug.linux/objs/../../sdk/libhttp/test/http-download.o debug.linux/objs/../../sdk/libhttp/test/http-parser-test.o debug.linux/objs/../libmov/test/mov-file-buffer.o debug.linux/objs/../libflv/test/amf0-test.o debug.linux/objs/../librtmp/aio/aio-rtmp-client.o debug.linux/objs/../librtmp/aio/aio-rtmp-transport.o debug.linux/objs/../librtmp/aio/aio-rtmp-server.o debug.linux/objs/../librtp/test/rtp-dump.o debug.linux/objs/../librtp/test/rtp-receiver-test.o debug.linux/objs/../librtsp/source/server/aio/rtsp-server-listen.o debug.linux/objs/../librtsp/source/server/aio/rtsp-server-udp.o debug.linux/objs/../librtsp/source/server/aio/rtsp-server-tcp.o debug.linux/objs/../librtsp/test/rtsp-client-test.o debug.linux/objs/../libsip/test/sip-header-test.o debug.linux/objs/../libsip/test/sip-timer.o debug.linux/objs/../libsip/test/transport-udp.o debug.linux/objs/../libsip/test/transport-tcp.o debug.linux/objs/../../sdk/source/uri-parse.o debug.linux/objs/../../sdk/source/urlcodec.o debug.linux/objs/../../sdk/source/ntp-time.o debug.linux/objs/../../sdk/source/time64.o debug.linux/objs/../../sdk/source/base64.o debug.linux/objs/../../sdk/source/unicode.o debug.linux/objs/../../sdk/source/thread-pool.o debug.linux/objs/../../sdk/source/app-log.o debug.linux/objs/../../sdk/source/port/ip-route.o debug.linux/objs/../../sdk/source/sockpair.o debug.linux/objs/../../sdk/source/darray.o debug.linux/objs/../../sdk/source/channel.o debug.linux/objs/../../sdk/source/uuid.o debug.linux/objs/../../sdk/source/random.o debug.linux/objs/../../sdk/source/port/sysnetconfig.o debug.linux/objs/../../sdk/libice/test/ice-transport.o debug.linux/objs/../../sdk/deprecated/tools.o ../libdash/debug.linux/libdash.a ../libflv/debug.linux/libflv.a ../libhls/debug.linux/libhls.a ../libmov/debug.linux/libmov.a ../libmpeg/debug.linux/libmpeg.a ../librtmp/debug.linux/librtmp.a ../librtsp/debug.linux/librtsp.a ../librtp/debug.linux/librtp.a ../libsip/debug.linux/libsip.a ../../sdk/libhttp/debug.linux/libhttp.a ../../sdk/libice/debug.linux/libice.a ../../avcodec/avbsf/debug.linux/libavbsf.a ../../avcodec/avcodec/debug.linux/libavcodec.a ../../avcodec/h264/debug.linux/libh264.a ../../avcodec/h265/debug.linux/libh265.a -L../../sdk/libaio/debug.linux -lrt -lpthread -ldl -laio -lssl -lcrypt
/usr/bin/ld: debug.linux/objs/../../sdk/libhttp/test/http-list-dir.o: in function `http_list_dir':
/home/zyx/media-server-test/media-server/test/../../sdk/libhttp/test/http-list-dir.cpp:32: undefined reference to `dir_list'
collect2: error: ld returned 1 exit status
make: *** [../../sdk/gcc.mk:88: debug.linux/test] Error 1

**Comment by xiaozhang8tuo** [comment]
编译不通过

**Comment by ireader** [comment]
是不是sdk/source/port/sysdirlist.c这个文件没有编译？

**Comment by xiaozhang8tuo** [comment]
谢谢。 libhttp 的makefile 下添加了 SOURCE_FILES += $(ROOT)/source/port/sysdirlist.c，编译通过。感谢。
