### ISSUE TITLE
在android上使用mpeg-ts-enc.c中的mpeg_ts_write函数，将h264的ES打包成ts流，保存成本地文件，vlc无法播放

### ISSUE THREAD

**Issue by saisaixv** [ireader/media-server#23]
EasyICE查看文件显示的信息：
     CRC 错误,共 2 次.
	    其中:
     CRC 错误出现在 PAT 表中,有 2 次.
     CRC 错误出现在 CAT 表中,有 0 次.
     CRC 错误出现在 PMT 表中,有 0 次.
     CRC 错误出现在 NIT 表中,有 0 次.
     CRC 错误出现在 SDT 表中,有 0 次.
     CRC 错误出现在 BAT 表中,有 0 次.
     CRC 错误出现在 TOT 表中,有 0 次.
     CRC 错误出现在 EIT 表中,有 0 次.

调用的源码：

    struct mpeg_ts_func_t h;
    h.alloc=mpegalloc;
    h.free=mpegfree;
    h.write=mpegwrite;

    void* param;

    ts=mpeg_ts_create(&h,param);

    const char* cpath=(*env)->GetStringUTFChars(env,path,0);

    file=open(cpath,O_RDWR|O_CREAT);

    if(ts==NULL){
        LOGE("ts==NULL");
        return -1;
    }
    int stream_type;
    if(codecID==0){//0表示 video
        stream_type=PSI_STREAM_H264;
    }else{
        stream_type=PSI_STREAM_AAC;
    }

    jbyte *Src_data=(*env)->GetByteArrayElements(env,data,NULL);

    int result=mpeg_ts_write(ts,stream_type,pts,dts,(void*)Src_data,(size_t)bytes);

void mpegwrite(void* param, const void* packet, size_t bytes){

    write(file,packet,bytes);
}

这是ts文件
[main.zip](https://github.com/ireader/media-server/files/2102022/main.zip)

**Comment by saisaixv** [comment]
这是保存的ts文件
[main.zip](https://github.com/ireader/media-server/files/2101839/main.zip)

**Comment by MyNameIsKai** [comment]
mpeg_ts_create 创建的ts 有没有额外的初始化?
而且mpeg_ts_write()这个函数好像是有7个参数的
int mpeg_ts_write(void* ts, int pid, int flags, int64_t pts, int64_t dts, const void* data, size_t bytes);


我是读h264文件保存的 ts不清楚还要做什么额外的初始化 
我是这样调用的
mpeg_ts_write(ts_ctx, PSI_STREAM_H264, 1, 900000, 900000, buf, buf_len);
buf保存的是SPS或者PPS或者SEI或者I帧或者P帧
而且在使用测试例子的时候 使用00 00 00 01 65 这种起始码转的ts文件 解复用 直接到assert了

**Comment by MyNameIsKai** [comment]
mpeg_ts_create 创建的ts 有没有额外的初始化?
而且mpeg_ts_write()这个函数好像是有7个参数的
int mpeg_ts_write(void* ts, int pid, int flags, int64_t pts, int64_t dts, const void* data, size_t bytes);

我是读h264文件保存的 ts不清楚还要做什么额外的初始化
我是这样调用的
mpeg_ts_write(ts_ctx, PSI_STREAM_H264, 1, 900000, 900000, buf, buf_len);
buf保存的是SPS或者PPS或者SEI或者I帧或者P帧
而且在使用测试例子的时候 使用00 00 00 01 65 这种起始码转的ts文件 解复用 直接到assert了

作者能否提供raw+aac保存到ts的测试案例 这里有测试文件
[test.zip](https://github.com/ireader/media-server/files/2105088/test.zip)

**Comment by saisaixv** [comment]
刚刚重新查看了源码，发现接口有了改动，我使用的是之前的代码，我是直接将 ES 调用mpeg_ts_write()写入的，ES可能是I帧也可能是P和B，我在每个I帧前面都会插入sps和pps，我最后生成的ts文件vlc放不了

**Comment by ireader** [comment]
@MyNameIsKai 对TS而言，大部分音视频（包括H.264/H.265/AAC），在mpeg_ts_add_stream时extradata可以是空值，也就是就不需要特殊的初始化参数。

在调用mpeg_ts_write时，flags用于表示是否视频I帧（音频总是0），PTS/DTS是音视频时间戳，单位: ms * 90, data/bytes表示音视频数据，代码中的注释稍后更新。

一般来说每次调用mpeg_ts_write时，应该是完整的一帧(包括SPS/PPS/SEI + I/P/B帧)，按照惯例每次在TS中写入I帧时，会把H.264的SPS、PPS一起写入(H.265的VSP、SPS、PPS).

您提供的test.zip文件中是264的裸流，需要先分帧，然后再写入。我这边没有h.264文件写ts文件的例子，在media-server/libflv/test目录下有h264-flv-test.cpp和flv2ts-test.cpp两个demo供您参考。特别说明demo中的h.264分帧不够准确，仅仅只用于参考。

**Comment by ireader** [comment]
@saisaixv vlc提示PAT/PMT crc32校验错误。

main.ts文件中的crc校验码确实比较奇怪，不知道是怎么生成的，需要再确认下。

**Comment by ireader** [comment]
crc文件链接错误，正确方式是使用sdk/source/digest/crc32.c文件
