### ISSUE TITLE
关于发送invite包是否存在bug?

### ISSUE THREAD

**Issue by ruanryq421** [ireader/media-server#231]
![image](https://user-images.githubusercontent.com/105113972/179272970-d479154e-81fb-4868-9d50-38655b731cd4.png)这个地方如果按照我个人的理解，30秒内，应该需要发送7次才对，也就是以500ms的成倍增加发包（没有收到回应的时候，返回408），但实际情况是只发了4次，应该MIN的函数那儿又重新++,导致计数不对。改成如下：
![image](https://user-images.githubusercontent.com/105113972/179274135-db615b21-4039-4a8d-b9e9-e26bc9bb647d.png)
达到个人理解的效果!谢谢，不知道是否作者就是这样设计？

**Comment by ireader** [comment]
感谢指正, 这里确实是个错误. retries在MIN宏重复计算. 

VC暂时还不支持gcc  ({statement list})方式,  使用MIN/MAX之类的宏坑比较多。

**Comment by ireader** [comment]
感谢指正, 这里确实是个错误. retries在MIN宏重复计算. 

VC暂时还不支持gcc  ({statement list})方式,  使用MIN/MAX之类的宏坑比较多。

**Comment by ruanryq421** [comment]
不客气，感谢作者辛苦付出，另外，我好像没有发现如果处于30s的invite中，主动退出这个流程的函数，因为如果是处于ip直呼的情况下，并没有代理服务器的时候，或者代理服务器突然异常退出的情况下，应用层上来讲如果没有函数直接退出，那么需要等30s异常退出才能发起下一次呼叫

**Comment by ireader** [comment]
确实没有提供transaction取消接口, 主要是因为sip本身提供了cancel和bye接口, transaction的cancel语义不明确.

**Comment by ruanryq421** [comment]
嗯，是的，做应用基本都会优先考虑这个问题，我也正在看，好像并没有找到合适的地方修改



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2022年7月17日(周日) 晚上8:42
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [ireader/media-server] 关于发送invite包是否存在bug? (Issue #231)




 
确实没有提供transaction取消接口, 主要是因为sip本身提供了cancel和bye接口, transaction的cancel语义不明确.
