### ISSUE TITLE
rtsp_client_options函数bug

### ISSUE THREAD

**Issue by zhangjp0405** [ireader/media-server#238]
我在调试librtsp库的test例子时发现一个bug，我在执行assert(0 == rtsp_client_options(ctx.rtsp, NULL));这条语句时，在MSVC Debug X64环境下会崩溃，通过进入rtsp_client_options函数里调试，发现是char require[128]和char session[128]没有赋值为0，即改为char require[128] = {0};和char session[128] = {0};就能解决这个bug。换句话说就是没有给require[128]和session[128]赋值为0，rtsp->req的值里就会缺少"User-Agent: %s\r\n"和末尾的"\r\n"，导致librtsp服务端在解析OPTIONS格式文本的时候会奔溃。
![1660447591479](https://user-images.githubusercontent.com/48978473/184521163-2fe18acb-df4d-47a2-8a84-6992d70d9583.png)

**Comment by ireader** [comment]
确实是未初始化错误，非常感谢！

**Comment by zhangjp0405** [comment]
作者不用客气，能学习和使用你的开源库应该是我感谢才对
