### ISSUE TITLE
mpeg4_h264_annexb_nalu内断言问题

### ISSUE THREAD

**Issue by Wahitler** [ireader/media-server#239]
libflv库里的mpeg4_h264_annexb_nalu在不丢包的情况下是正常的，如果有丢包会导致触发断言，程序停止
![clipboard](https://user-images.githubusercontent.com/12858618/185015040-ec14616c-9f06-41dd-951e-5e39b13cb3ed.png)
![image](https://user-images.githubusercontent.com/12858618/185015783-89e87a14-e374-473b-9381-ac30387edae5.png)
![image](https://user-images.githubusercontent.com/12858618/185016109-e841ba69-4735-4a61-a014-dbcee20eec89.png)

无法保证源不丢包的情况下我应该怎么做呀 我现在用的是debug，编一个release的么

**Comment by Wahitler** [comment]
> 

有点不太确定是不是因为丢包引起的这个断言

**Comment by ireader** [comment]
触发这个assert是因为nalu长度为0，如果不处理会导致ffmpeg解码报错。

一般应该在收包环节做处理，发现丢包后直接丢弃。 如果无法判断视频帧之间的依赖性，可能需要丢整个gop。

**Comment by Wahitler** [comment]
如果是作为一个流媒体平台，在收包环节发现了丢包，应该也不丢弃吧，应该是播放端做丢弃这些处理吧，我打算编个release的，集成一下
