### ISSUE TITLE
mac build err

### ISSUE THREAD

**Issue by KouChongYang** [ireader/media-server#24]
When I do make on the MAC，have a err !
make -C sdk/libaio && make -C sdk/libhttp && make -C media-server/libmpeg && make -C media-server/libflv && make -C media-server/libhls
gcc -I. -I./include -I../include -DOS_LINUX -DDEBUG -D_DEBUG -Wall -fPIC -g -Wall -fvisibility=hidden -fvisibility=default -c -MMD -MP -MF debug.linux/aio-accept.d -o src/aio-accept.o src/aio-accept.c
In file included from src/aio-accept.c:2:
../include/sys/locker.h:39:35: error: use of undeclared identifier 'PTHREAD_MUTEX_RECURSIVE_NP'
        pthread_mutexattr_settype(&attr, PTHREAD_MUTEX_RECURSIVE_NP);

 error: use of undeclared identifier 'PTHREAD_MUTEX_RECURSIVE_NP'

**Comment by ireader** [comment]
add xcode project files
