### ISSUE TITLE
PS解封无法输出帧类型

### ISSUE THREAD

**Issue by swq123459** [ireader/media-server#244]
ps_demuxer_t 输出回调的flags字段没有变化

**Comment by swq123459** [comment]
参考[mpeg-ps-dec-test.cpp](https://github.com/ireader/media-server/blob/master/libmpeg/test/mpeg-ps-dec-test.cpp)

**Comment by ireader** [comment]
flags直接用的pes header中data_alignment_indicator字段. 可能是ps封装时没有修改这个值.

周末有时间可以更新一版, 直接根据h.264/265 nalu type判断帧类型.

**Comment by swq123459** [comment]
好的感谢大佬，顺便问问宽高信息输出有策略建议吗

**Comment by ireader** [comment]
获取h264、h265宽高信息可以参考 avcodec/h264 parser.c

**Comment by ireader** [comment]
commit: fc7e636ca19b60faeefbbc26d14c8000fc6af2d1
