### ISSUE TITLE
多路client拉流时报错问题

### ISSUE THREAD

**Issue by zero-zhaowei** [ireader/media-server#248]
![Snipaste_2022-11-18_18-22-11](https://user-images.githubusercontent.com/45255778/202679701-f48a968e-5516-495e-8199-e53120aad849.png)

**Comment by ireader** [comment]
帮忙用wireshark抓包看看?

**Comment by zero-zhaowei** [comment]
在同一块板卡上跑server和client，创建了两路server，vlc拉流正常，但是client第二路时就会报错，一路是正常的

**Comment by ireader** [comment]
本地暂未复现，你那边在windows上运行过吗？

**Comment by zero-zhaowei** [comment]
没有，在嵌入式linux开发板上跑的，不过是在同一块板子上跑的server和client

**Comment by zero-zhaowei** [comment]
> 本地暂未复现，你那边在windows上运行过吗？

是在linux开发板上跑的，另外两个client是在同一个进程中初始化的，初始化步骤参考了rtsp-client-test.c，server参考的rtsp-server-test.c

**Comment by ireader** [comment]
从现象看，可能是网络接收的数据有错误，不排除是多线程问题。

麻烦在调用rtp_client_input前，先把输入的数据保存一份到文件。每个client对象对应一个单独的文件。

**Comment by zero-zhaowei** [comment]
两个文件保存的sdp信息如下
[RTSP/1.0 200 OK
CSeq: 1
Date: Sun, 04 Jan 1970 19:16:25 GMT
Content-Type: application/sdp
Content-Length: 220

v=0
o=- 9488945915716620064 9488945915716624359 IN IP4 0.0.0.0
s=rtsp://10.0.2.17:8555/live/chn1
c=IN IP4 0.0.0.0
t=0 0
a=range:npt=0-72057594037927.9
a=recvonly
a=control:*
m=video 0 RTP/AVP 100
a=rtpmap:100 H265/90000
],byte is [337]

client: test/rtsp-client-test.cpp:245: void* rtsp_clientInitPthread(void*): Assertion `0 == rtsp_client_input((rtsp_client_t*)ctx.rtsp, packet, r)' failed.
]

data is [RTSP/1.0 200 OK
CSeq: 1
Date: Sun, 04 Jan 1970 19:16:25 GMT
Content-Type: application/sdp
Content-Length: 46

m=video 0 RTP/AVP 100
a=rtpmap:100 H265/90000
59 IN IP4 0.0.0.0
s=rtsp://10.0.2.17:8555/live/chn1
c=IN IP4 0.0.0.0
t=0 0
a=range:npt=0-72057594037927.9
a=recvonly
a=control:*
m=video 0 RTP/AVP 100
a=rtpmap:100 H265/90000
],byte is [162]

**Comment by zero-zhaowei** [comment]
> 



> 从现象看，可能是网络接收的数据有错误，不排除是多线程问题。
> 
> 麻烦在调用rtp_client_input前，先把输入的数据保存一份到文件。每个client对象对应一个单独的文件。

你好，问题解决了，是rtp-recviver-test.c中的 rtp_receiver_tcp_test函数中没有支持到多线程的问题，这个函数在client-test中调用到了
