### ISSUE TITLE
使用rtsp-client-test时遇到疑惑

### ISSUE THREAD

**Issue by lcgsglance** [ireader/media-server#249]
使用rtsp-client-test.c进行测试，抓包显示拉流正常，音视频各有一个track，但打印media_count的值发现为0
`	printf("media_count=%d\n", rtsp_client_media_count(ctx.rtsp));
`
因此rtsp_client_get_media_type返回-1，rtsp_client_teardown会触发断言，以下为抓包文件，rtsp server端口为555

[rtsp-port555.zip](https://github.com/ireader/media-server/files/10073696/rtsp-port555.zip)

**Comment by ireader** [comment]
265文件播放可以用ffplay.

play/pause/teardown, 直接调相应接口就行， 例如：rtsp_client_play， 相关参数可以看头文件说明。
需要注意的时线程安全问题， 如果需要多线程调用，需要加锁。
