### ISSUE TITLE
fmp4

### ISSUE THREAD

**Issue by tablife** [ireader/media-server#25]
fmp4_writer_test fmp4 aac audio play no voice

 fmp4_writer_test 320x240 run fail

**Comment by ireader** [comment]
把测试的flv文件发一下？

**Comment by tablife** [comment]
[4.zip](https://github.com/ireader/media-server/files/2487727/4.zip)
4.flv 转出 fMP4 用vlc播放有声音，发送到手机上播放没有声音

**Comment by tablife** [comment]
你好，请问int fmp4_writer_add_video(struct fmp4_writer_t* writer, uint8_t object, int width, int height, const void* extra_data, size_t extra_data_size)这个方法extra_data的数据要求，传入1.sps，2.sps+pps,3,sps+pps+frame，哪种才是对的

int fmp4_writer_write(struct fmp4_writer_t* writer, int idx, const void* data, size_t bytes, int64_t pts, int64_t dts, int flags)这个方法data数据要求不清楚，sps ,pps是否也要调用这个方法，每次都调用，还是只有头部写入之后就不用写了呢。

**Comment by ireader** [comment]
fmp4-writer.h头文件中描述了参数格式。

fmp4_writer_add_audio/video的extra_data参数要传入AudioSpecificConfig/AVCDecoderConfigurationRecord/HEVCDecoderConfigurationRecord结构的数据

fmp4_writer_write的data要求使用mp4 bitstream

**Comment by tablife** [comment]
AVCDecoderConfigurationRecord 用下边的数据合成的视频有问题，能帮忙看下吗 感谢
01 4D 40 15 FF E1 00 13 00 00 00 01 67 42 00 29 8D 8D 40 F0 28 D0 0F 08 84 53 80 01 00 08 00 00 00 01 68 CA 43 C8
[m2.zip](https://github.com/ireader/media-server/files/2494389/m2.zip)

**Comment by ireader** [comment]
AVCDecoderConfigurationRecord里的sps、pps不需要00 00 00 01起始码

**Comment by tablife** [comment]
mov_buffer_t 不写文件输出到内存中如何实现，合成的fmp4通过websocket传输

**Comment by tablife** [comment]
我想以流形式输出fmp4, 不叠加缓存 ，下边的代码有问题，帮忙看看 
#include "mov-buffer.h"
#include <stdio.h>

#if defined(_WIN32) || defined(_WIN64)
#define fseek64 _fseeki64
#define ftell64 _ftelli64
#else
#define fseek64 fseek
#define ftell64 ftell
#endif

#define N_SEGMENT (1 * 1024 * 1024)

#define FRAME_BUFFER_LEN 32

char file[100];

struct buffer {
	uint8_t* ptr;
	size_t bytes;
	size_t capacity;
	size_t offset;
	size_t position;
	int	index;
};

const struct buffer* data_buffer(void)
{
	static struct buffer buffer = {
		NULL,
		0,
		0,
		0,
		0,
		0,
	};
	return &buffer;
}

static int mov_data_read(void* fp, void* data, uint64_t bytes)
{
	return -1;
}

static int mov_data_write(void* param, const void* data, uint64_t bytes)
{
	void* ptr;
	size_t capacity;
	struct buffer* buf;
	buf = (struct buffer*)param;

	if (buf->offset + (size_t)bytes > buf->capacity)
	{
		capacity = buf->offset + (size_t)bytes + N_SEGMENT;
		ptr = realloc(buf->ptr, capacity);
		buf->ptr = (uint8_t*)ptr;
		buf->capacity = capacity;
	}

	memcpy(buf->ptr + buf->offset, data, bytes);
	buf->offset += (size_t)bytes;
	if (buf->offset > buf->bytes) {
		buf->bytes = buf->offset;
	}

	return 0;

	//return bytes == fwrite(data, 1, bytes, (FILE*)fp) ? 0 : ferror((FILE*)fp);
}

static int mov_data_seek(void* param, uint64_t offset)
{
	//return fseek64((FILE*)fp, offset, SEEK_SET);
	struct buffer* buf;
	buf = (struct buffer*)param;
	buf->offset = (size_t)offset;
	return 0;
	//return -1;
}

static uint64_t mov_data_tell(void* param)
{
	//return ftell64((FILE*)fp);
	struct buffer* buf;
	buf = (struct buffer*)param;

	if (buf->index < 10) {
		buf->index++;
		sprintf(file, "D://developer//temp//temp//temp%d", buf->index);
		FILE* fpFile = fopen(file, "wb+");
		fwrite(buf->ptr, 1, buf->offset, fpFile);
		fclose(fpFile);
	}

	buf->offset = 0;
	buf->bytes -= buf->offset;
	return buf->offset;
	//return 0;
}

const struct mov_buffer_t* mov_data_buffer(void)
{
	static struct mov_buffer_t s_io = {
		mov_data_read,
		mov_data_write,
		mov_data_seek,
		mov_data_tell,
	};
	return &s_io;
}

**Comment by ireader** [comment]
写内存可以参考libdash\src\dash-mpd.c
