### ISSUE TITLE
ios rtsp 在关闭服务器调用aio-socket-kqueue::aio_socket_release 计数器ctx->ref 不对 导致close(sock)没执行

### ISSUE THREAD

**Issue by pdyw** [ireader/media-server#250]
<img width="713" alt="截屏2022-11-30 17 35 09" src="https://user-images.githubusercontent.com/17918462/204760373-edf1d964-cee9-47f7-8102-b25c31133ab4.png">

KQueueRead,KQueueWrite 方法返回计数器没有减少
<img width="793" alt="截屏2022-11-30 17 38 27" src="https://user-images.githubusercontent.com/17918462/204761033-55746654-10f9-4c3f-a28c-21d3651735ad.png">
目前我在退出时强制设置ref=1 测试下来没有发现异常，这样做有什么隐藏的问题吗？
<img width="954" alt="截屏2022-11-30 17 39 59" src="https://user-images.githubusercontent.com/17918462/204761442-47f51b3f-18ac-4571-93b6-de0b0f6d471d.png">

**Comment by ireader** [comment]
aio_socket_destroy函数内只会调用shutdown关闭socket读写能力，并不会立即触发socket_close。

引用计算不为0，可能是因为read/write回调没有完成。

这个问题周末我排查下，感谢！

**Comment by ireader** [comment]
本地测试验证rtsp_example程序可以正常调用到aio_socket_release close(ctx->socket)逻辑。

**Comment by WangKunKun** [comment]
@pdyw 大佬你好，请问iOS能运行的Demo 可以参考一下吗 有偿。 如果感兴趣，请加我qq 357863248 感谢
