### ISSUE TITLE
MAC 上编译报错

### ISSUE THREAD

**Issue by jesse881025** [ireader/media-server#251]
您好，clone 后，MAC 上编译报错， 不知道怎么联系你，可以加我微信(522684802)吗？有些问题想向你请教一下。 建议您可以建一个群，供大家一起讨论
![1669862529469](https://user-images.githubusercontent.com/24264672/204953344-3585e6fc-efed-4d84-bf6f-750ff9cdacef.jpg)

**Comment by Dw9** [comment]
作者主页写着的，  qq群号： 579575545。

**Comment by ireader** [comment]
抱歉，mac xcode项目没有更新。
1. 在test中增加定义： __ERROR__=(00 * 10000000 + __LINE__ * 1000)
2. libsip中sip-uac-refer.c文件已删除，从xcode项目中删除即可

**Comment by ireader** [comment]
已更新xcode工程文件
