### ISSUE TITLE
GB28181 Muxer 定码率花屏

### ISSUE THREAD

**Issue by xcccya** [ireader/media-server#260]
mpegps muxer 复用流的时候，如果摄像头的流是定码率，则出现花屏卡屏情况（国标28181 tcp 模式，网络良好不丢包），摄像头编码切换成变码率，画面显示正常，请问下这个是哪里出现了问题？

**Comment by ireader** [comment]
wireshark抓包分析下

**Comment by xcccya** [comment]
font{
        line-height: 1.6;
    }
    ul,ol{
        padding-left: 20px;
        list-style-position: inside;
    }


    
    
        你好，我把协议切换到UDP抓了下包，麻烦师傅有空时候分析分析（邮箱附件太大发不出，我把wireshark放百度云盘上了）链接：https://pan.baidu.com/s/1LgQaDCkmkx4BcffgUbc1gw 
        
    提取码：vicm
    
        
            
        
    
    
     
    
        
                    ***@***.***
        
    
 

  
    ---- 回复的原邮件 ----
  
  
    
      
        
         发件人 
        
        
            ***@***.***>
            
        
      
      
        
         发送日期 
        
        
        2023年2月2日 13:57
        
      
      
        
         收件人 
        
        
         
          
            ***@***.***>
            
          
        
      
      
        
         抄送人 
        
        
          
            ***@***.***>
            ,
          
          
            ***@***.***>
            
          
        
      
      
        
         主题 
        
        
              Re: [ireader/media-server] GB28181 Muxer 定码率花屏 (Issue #260)
        
      
    
  
  

wireshark抓包分析下

**Comment by ireader** [comment]
从wireshark导出数据解析播放正常？

加两行代码试试：
```
n = mpeg_bits_read16(reader);
mpeg_bits_seek(reader, off + n + 6);
```

![image](https://user-images.githubusercontent.com/1535445/216312547-fa18952a-480b-45f3-9b24-67c3b0ee648a.png)

**Comment by xcccya** [comment]
首先是我把在muxerr的回调里把ps 流保存到文件，用播放器播放也是花屏的。但是demuxer是没问题的（海康私有流000001bd直接忽略也是不会影响播放的），我是demuxer海康ps流后，再重新muxer，然后播放（摄像头是定码率的情况）就花屏了，摄像头如果设置成编码率，又播放正常！因为编码率和定码率的ps打包格式不会变化，我想是不是ps的某些参数设置的不对，比如program_mux_rate？

**Comment by ireader** [comment]
用你提供的抓包文件，ps demuxer后重新muxer，ffplay播放正常。

可以用libmpeg/test/mpeg-ps-test.cpp的mpeg_ps_test函数验证下:
mpeg_ps_test("x.ps");

如果出现assert，需要忽略codecid == 0的情况
![image](https://user-images.githubusercontent.com/1535445/216513965-7cb3e94f-f697-4735-b684-8540adcce314.png)

**Comment by xcccya** [comment]
我muxer后的ps流用vlc和ffplay播放器播放也是正常的，但是海康NVR播放就花屏了(和H264BSAnalyzer播放器差不多是一样的，https://github.com/latelee/H264BSAnalyzer）（muxer的流在宇视和大华上也是正常，就是在海康上面出现了花屏现象）

**Comment by ireader** [comment]
什么表现？ 只有开始花屏，还是一直花屏？

**Comment by ireader** [comment]
更新下再试试

**Comment by xcccya** [comment]
一直花屏，下半部分花屏严重，更新了最新的代码这个问题依旧存在

**Comment by ireader** [comment]
麻烦抓个完整包, 包含从IPC接收的PS流, 以及发送给海康NVR的花屏PS流.

**Comment by xcccya** [comment]
我直接把接收到的ps和muxer后的ps数据都保存了下来。 （发现原始的ps流数据其实用H264BSAnalyzer播放也花屏，但是两个ps文件vlc和ffplay播放都是正常的）
链接：https://pan.baidu.com/s/1vtL2uXVEEIBom6YYxni9iw 
提取码：cetv

**Comment by ireader** [comment]
发送到HIK NVR时， sdp协商的是PS还是H265？  看看RTP PayloadType值对应的哪个Codec. 

可以把如下信息打印出来：
1. SDP offer/answer
2. 发送到HIK NVR时 RTP包的PayloadType值

**Comment by ireader** [comment]
另外可以尝试下， 调用ps_muxer_input函数是，flags参数加上**MPEG_FLAG_H264_H265_WITH_AUD**标记.

ps_muxer_input(ps, streamid, flags | MPEG_FLAG_H264_H265_WITH_AUD, pts, dts, data, bytes)

**Comment by xcccya** [comment]
![invite](https://user-images.githubusercontent.com/124228262/216802118-5bfd5cb8-54d5-4c39-8f99-9b1956b71c79.png)
![invite 200ok](https://user-images.githubusercontent.com/124228262/216802124-e29fe3b5-e283-4d87-9c04-976d48d851d2.png)
MPEG_FLAG_H264_H265_WITH_AUD加上了，没有效果（海康自己的ps流也是不携带AUD的）
SDP协商是没问题的，问题还是出现在ps封装，也不知道海康NVR内部解析到底是哪里出了问题现在。

**Comment by xcccya** [comment]
![invite](https://user-images.githubusercontent.com/124228262/216802413-45ced123-29b8-4122-8b3c-4d49d8a7647f.png)
![invite 200ok](https://user-images.githubusercontent.com/124228262/216802414-4a7994ba-3988-44c1-9b01-3c98be065b4e.png)
SDP协商过程是没问题的。

MPEG_FLAG_H264_H265_WITH_AUD参数加上了，没有效果，而且海康自家摄像头的ps也是没有AUD标记的

**Comment by ireader** [comment]
直接把接收的HIK ps流转发给HIK NVR有花屏现象吗？

**Comment by xcccya** [comment]
直接把接收的HIK ps流转发给HIK NVR 播放是正常的，摄像头的编码切换**变码率**时，使用libmpegps muxer的ps流也是可以正常播放的

**Comment by ireader** [comment]
把变码率的ps流也上传一下。

另外摄像头设置为固定码率时，试试把码率调到很低，比如为400k，观察下是否会花屏。

**Comment by xcccya** [comment]
经测试定码率很低的时候（512K），播放是不花屏的

**Comment by ireader** [comment]
可能是固定码率时视频关键帧超过一个ps包导致。

参照下面图片修改一行代码再试试： 
![image](https://user-images.githubusercontent.com/1535445/216961493-bfc5af0f-54c7-45c6-a68c-008af60412de.png)

**Comment by xcccya** [comment]
这是是变码率下的ps流（摄像机原始ps流和demuer+muxer的ps流）
    链接：https://pan.baidu.com/s/14k9uDuQG9mk3p3To0YFAfA
    提取码：9te2

    data_alignment_indicator 置零也没有效果。

**Comment by ireader** [comment]
加下这个qq：579575545，方便沟通。

**Comment by xcccya** [comment]
qq：579575545 是个群，已经加了，同意一下
