### ISSUE TITLE
ubuntu 16.04 build has demo fail

### ISSUE THREAD

**Issue by ubia** [ireader/media-server#27]
ubuntu@ip-172-31-93-66:~/media-server-build/media-server/libhls/demo$ make
/bin/sh: bc: command not found
g++ -I. -I../include -I../../libmpeg/include -I../../libflv/include -I../../../sdk/include -I../../../sdk/libhttp/include -I../../../sdk/libaio/include -D_HLS_SERVER_TEST_ -DOS_LINUX -DDEBUG -D_DEBUG -Wall -Wall -fPIC -g -Wall -fvisibility=hidden -c -MMD -MP -MF debug.linux/hls-server.d -o hls-server.o hls-server.cpp
hls-server.cpp:31:10: error: ‘atomic’ in namespace ‘std’ does not name a template type
     std::atomic<int> ref;
          ^
hls-server.cpp: In function ‘int hls_handler(void*, const void*, size_t, int64_t, int64_t, int64_t)’:
hls-server.cpp:72:6: error: ‘struct hls_ts_t’ has no member named ‘ref’
  ts->ref = 1;
      ^
hls-server.cpp:84:18: error: ‘atomic_fetch_sub’ is not a member of ‘std’
         if (0 == std::atomic_fetch_sub(&ts->ref, 1) - 1)
                  ^
hls-server.cpp:84:45: error: ‘struct hls_ts_t’ has no member named ‘ref’
         if (0 == std::atomic_fetch_sub(&ts->ref, 1) - 1)
                                             ^
hls-server.cpp: In function ‘int hls_server_ts_onsend(void*, int, size_t)’:
hls-server.cpp:178:14: error: ‘atomic_fetch_sub’ is not a member of ‘std’
     if (0 == std::atomic_fetch_sub(&ts->ref, 1) - 1)
              ^
hls-server.cpp:178:41: error: ‘struct hls_ts_t’ has no member named ‘ref’
     if (0 == std::atomic_fetch_sub(&ts->ref, 1) - 1)
                                         ^
hls-server.cpp: In function ‘int hls_server_ts(http_session_t*, const string&, const string&)’:
hls-server.cpp:198:13: error: ‘atomic_fetch_add’ is not a member of ‘std’
             std::atomic_fetch_add(&ts->ref, 1);
             ^
hls-server.cpp:198:40: error: ‘struct hls_ts_t’ has no member named ‘ref’
             std::atomic_fetch_add(&ts->ref, 1);
                                        ^
../../gcc.mk:86: recipe for target 'hls-server.o' failed
make: *** [hls-server.o] Error 1

**Comment by ireader** [comment]
#include <atomic>
