### ISSUE TITLE
Write MPEG-TS

### ISSUE THREAD

**Issue by TheMadius** [ireader/media-server#282]
The question about the implementation of mpeg-ts recording, I noticed in the code that a number is written in the header of the ts packet to the pcr fragment, but before passing it to the function, it is multiplied by 300, and then divided by 300 in it, why is this done?

If in order to store the numbers in the first 33 bits, I don't understand why, if it can be obtained using this conversion anyway, without multiplying by 300

media-server/libmpeg/source/mpeg-ts-etc.c:183

**Comment by ireader** [comment]
```
pcr_write(data + 6, (pcr - PCR_DELAY) * 300)
```

yes, this code for convert pcr timebase from 90kHz to 27MHz.

what is about conversion way?

**Comment by TheMadius** [comment]
Thanks, I found information about it.
```
The first 33 bits are based on a 90 kHz clock
```
