### ISSUE TITLE
想请教下为什么Rtmp的chunk size为什么不一致

### ISSUE THREAD

**Issue by jo-qzy** [ireader/media-server#289]
rtmp_client.c中，chunk size为4000:
#define RTMP_PUBLISH_CHUNK_SIZE 4000
rtmp_server.c中，chunk size为4096:
#define RTMP_OUTPUT_CHUNK_SIZE	4096

想请教下这两个值为什么设置的不一样，是有特殊原因，还是没啥原因，只是刚好写的4000，这里比较疑惑，提前感谢大佬解答

**Comment by ireader** [comment]
4000和4096都是来源于nginx rtmp module。 

大多数推流配置4000。

**Comment by jo-qzy** [comment]
明白了，谢谢陈老师
