### ISSUE TITLE
rtmp server seems not usable

### ISSUE THREAD

**Issue by xsw9527** [ireader/media-server#29]
Code is as below:
int main(int argc, char* argv[])
{
	socket_init();
	rtmp_server_forward_aio_test("192.168.0.73", 1935);
	socket_cleanup();
	return 0;
}
I use rtmp client to push to rtmp://192.168.0.73/live/test, seems ok
But I failed to play rtmp://192.168.0.73/live/test using another rtmp flash player.
and the program run-into Assert usually.

**Comment by ireader** [comment]
问题原因：
1. 上周新增的getduration回调返回值错误，导致rtmp play错误
2. libaio中的引用计数错误，导致内存被多次删除

请更新代码后再次验证，需更新media-server和sdk (依赖了libaio）

**Comment by ireader** [comment]
另外，如果用flash播放器，需要在librtmp编译时定义_FLASH_HANDSHAKE_，否则只有声音，没有画面。

原因是flash的握手协议使用了hash加密。

**Comment by xsw9527** [comment]
目前环境是在Windows 下，
 如果定义_FLASH_HANDSHAKE_ 会导致rtmp-handshake.c 85行 HMACContext 未定义。
进一步定义_IETF_HMAC_的话，错误更多了。

**Comment by ireader** [comment]
定义_IETF_HMAC_即可，不用定义_FLASH_HANDSHAKE_ ,可以在librtmp工程文件中定义，也可以直接在rtmp-handshake.c文件最顶部定义.
#define _IETF_HMAC_

**Comment by xsw9527** [comment]
Windows visual studio
不定义_FLASH_HANDSHAKE_
rtmp-handshake.c 第7行添加
#define _IETF_HMAC_
编译通过，测试rtmp（h264/AAC）推流正常
flash player 拉流播放正常
ffplay 拉流正常
