### ISSUE TITLE
咨询av1的ts封装

### ISSUE THREAD

**Issue by zhouxiaojun2008** [ireader/media-server#294]
大佬，用您的libmpeg库封装264，265 over ts很强大。最近我想用libmpeg封装av1 over mpegts，我注意到您的定义了PSI_STREAM_AV1，我知道0x80后的都是私有的格式，这样虽然封装出来后，经过srt服务器的转发，在播放端通过ffmpeg 拉流就遇到问题了，因为属于自定义的stream_type，ffmpeg肯定解析不出来codec，因为传输是在有损网络，所有av1目前已经支持的比如mkv,mp4就不能使用的，有损网络下只有rtp和mpegts能有同步恢复的机制，就是拉流端能基于ffmpeg demuxer来实现吗？当然还有一种方案是，不用ffmpeg拉流，srt api拉流，然后再调用libmpeg demux出来也是一种办法，大佬有啥建议吗？

**Comment by ireader** [comment]
ffmpeg ts暂不支持av1，基于ffmpeg的demuxer不确认是否可行， 目前可以考虑先用libmpeg demuxer。 遇到问题时再讨论具体方案。

**Comment by zhouxiaojun2008** [comment]
嗯 只能这样了

**Comment by zhouxiaojun2008** [comment]
忘记关了，我用了libmpeg封装av1，直接用的PSI_STREAM_AV1这个类型，然后推出去，经过srt服务器转发，在播放端，可以用libmpeg解封装，也可以用ff解封装，ff的mpegdumxer遇到这种私有的解封装，需要手动设置下codectype，是可以跑通的。这样也利用了ff的mpegdemuxer他可以检测到丢包的情况。当然libmpeg也可以检测到。

**Comment by ireader** [comment]
这个方案很赞！
