### ISSUE TITLE
librtsp库提供了头文件rtsp-server-aio.h,但是为什么没有将其实现编译在librstp库中

### ISSUE THREAD

**Issue by dingfulai** [ireader/media-server#298]
包括四个接口：
rtsp_server_listen
rtsp_server_unlisten
rtsp_transport_udp_create
rtsp_transport_udp_destroy

但是它们的实现在librtsp/source/server/aio目录下，librtsp的Makefile中并未指定该目录为源码目录，这个是遗漏了还是故意为之？

Makefile中SOURCE_PATHS如下：
`
SOURCE_PATHS = source source/client source/server source/utils source/sdp
SOURCE_FILES = $(foreach dir,$(SOURCE_PATHS),$(wildcard $(dir)/*.cpp))
SOURCE_FILES += $(foreach dir,$(SOURCE_PATHS),$(wildcard $(dir)/*.c))

SOURCE_FILES += $(ROOT)/source/digest/md5.c
SOURCE_FILES += $(ROOT)/source/base64.c
`

**Comment by Dw9** [comment]
估计作者本来就是这样设计模块的； rtsp是rtsp, aio 是aio 协议和网络分开 你可以用sdk里面的libaio 也可以自己实现  方便接入

**Comment by dingfulai** [comment]
> 

我看到已经关闭的issue中提到了，确实是为了模块独立性，但是这个头文件确实有点迷惑性，个人感觉放到test中作为参考实现会更好些。
