### ISSUE TITLE
libmov库使用咨询

### ISSUE THREAD

**Issue by lcgsglance** [ireader/media-server#302]
已经用`mov-writer-h265.cpp`中的`h265_write`完成实时h265流封装mp4文件，正常播放，请问
1.怎么才能将实时的aac音频流（不是文件），也同时封装到上述mp4文件中；
2.停止封装时调用了`mp4_writer_destroy(ctx.mov);`和`free(fp);`，但是几秒后文件的大小才不再是0，是我调用有错漏，还是机器io性能有问题呢？

**Comment by ireader** [comment]
1. 首先调用AddAudioTrack接口添加aac音轨，然后根据时间戳排序交叉写入h265和aac帧即可；
2. 文件系统缓存问题；
