### ISSUE TITLE
how to work with rtmp_input_test

### ISSUE THREAD

**Issue by zhenlei** [ireader/media-server#307]
Try it with flv file using below command, but failed.
`test -c rtmp_input_test "/tmp/out.flv"`

It seems it does not support flv format. what should be the input file?

**Comment by ireader** [comment]
rtmp_input_test input with wireshark dump raw data:
1. wireshark capture whole rtmp interactive;
2. wireshark follow tcp connection;
3. choose server -> client side;
4. save raw data;
