### ISSUE TITLE
rtsp-muxer中rtsp_muxer_getinfo使用段错误

### ISSUE THREAD

**Issue by Pluto-kk** [ireader/media-server#308]
你好， 我在使用rtsp-muxer中rtsp_muxer_getinfo函数，运行提示段错误的问题，定位在
  `rtp_payload_encode_getinfo(pt->rtp.rtp, seq, timestamp);`
将其改为pt->rtp.encoder后正常
`rtp_payload_encode_getinfo(pt->rtp.encoder, seq, timestamp);`
![微信图片_20230830094205](https://github.com/ireader/media-server/assets/55232131/b76e8563-2558-428a-8720-30b02b890a8f)
![微信图片_20230830094614](https://github.com/ireader/media-server/assets/55232131/6b98bed3-6e76-4761-954e-96a7c3cdaffb)
![微信图片_20230830093901](https://github.com/ireader/media-server/assets/55232131/d38e17a1-4345-4207-a308-57eaf5ec78a6)

**Comment by ireader** [comment]
感谢， 有空的话帮忙提个PR!
