### ISSUE TITLE
mpeg-ts muxer 多线程模式mux 只有一个mux能工作

### ISSUE THREAD

**Issue by xsw9527** [ireader/media-server#31]
代码如下：
struct mpeg_ts_func_t tshandler[VENC_CHANNEL_NUM];
int chn[VENC_CHANNEL_NUM];
tshandler[i].alloc = ts_alloc;
tshandler[i].write = ts_write;
tshandler[i].free = ts_free;
void* ts = mpeg_ts_create(tshandler + i, chn + i);

mpeg_ts_write(ts, ts_stream(ts, STREAM_VIDEO_H264),isKeyFrame, cts , cts , pPacket->GetBuffer(), pPacket->GetLength());

只有一个mux能出数据。
调试了挺久，感觉和/proc/cpu/alignment这个有点关系 但是不太确定。

mpeg-ts-proto.h这个文件里的结构体定义有点怪怪的

struct ts_adaptation_field_t
{
	unsigned int adaptation_field_length : 8;
	unsigned int discontinuity_indicator : 1;
	unsigned int random_access_indicator : 1;
	unsigned int elementary_stream_priority_indicator : 1;
	unsigned int PCR_flag : 1;
	unsigned int OPCR_flag : 1;
	unsigned int splicing_point_flag : 1;
	unsigned int transport_private_data_flag : 1;
	unsigned int adaptation_field_extension_flag : 1;

	int64_t program_clock_reference_base; // 33-bits
	unsigned int program_clock_reference_extension; // 9-bits

	int64_t original_program_clock_reference_base; // 33-bits
	unsigned int original_program_clock_reference_extension; // 9-bits

	unsigned int splice_countdown : 8;

	unsigned int transport_private_data_length : 8;

	unsigned int adaptation_field_extension_length : 8;
	unsigned int ltw_flag : 1;
	unsigned int piecewise_rate_flag : 1;
	unsigned int seamless_splice_flag : 1;

	unsigned int ltw_valid_flag : 1;
	unsigned int ltw_offset : 15;

	unsigned int piecewise_rate : 22;

	unsigned int Splice_type : 4;
	int64_t DTS_next_AU;
};

**Comment by ireader** [comment]
多线程是同时有多路音视频流需要mux吗？
1. 如果是多路音视频，需要创建多个mpeg_ts_t对象；
2. 如果一个mpeg_ts_t需要在多个线程中使用，需要在调用相关接口前加锁。

**Comment by xsw9527** [comment]
是有多个音视频流需要mux
1.的确是通过 void* ts = mpeg_ts_create(tshandler + i, chn + i); 创建了多个对象

**Comment by xsw9527** [comment]
根据你的提示，找到问题了
static int ts_stream(void* ts, int codecid)
{
    static std::map<int, int> streams;
    std::map<int, int>::const_iterator it = streams.find(codecid);
    if (streams.end() != it)
        return it->second;

    int i = mpeg_ts_add_stream(ts, codecid, NULL, 0);
    streams[codecid] = i;
    return i;
}
该函数里有一个static变量。改为与mpeg_ts_create出来的ts一一对应 就ok了
感谢！
