### ISSUE TITLE
使用本库文件接收摄像头H265视频流报错问题的咨询。

### ISSUE THREAD

**Issue by aidelingyu** [ireader/media-server#321]
大神你好，我使用zlmediakit流媒体时，发现接收摄像头H265视频流时，流媒体会报错。报错日志如下：
![报错](https://github.com/ireader/media-server/assets/23529219/1f9ad25f-ffb6-4d88-863f-29caf7de5159)
根据日志内容，发现流媒体调用了本项目中libmpeg模块下的mpeg-psm.c文件中的psm_read方法，该方法中有一个assert校验代码（mpeg-psm.c文件中的112行）`assert(mpeg_bits_tell(reader) == off + element_stream_info_length);`报错就是因为这个判断触发的，我尝试把这个校验注释并重新编译流媒体源码，就可以正常接收摄像头推送的H265视频流了。想咨询一下，去掉这个校验会有什么影响吗？

**Comment by ireader** [comment]
没有影响, 这个assert只是提示性的, 可能是psm里description解析失败了, 不影响正常使用.

**Comment by aidelingyu** [comment]
@ireader 好的。感谢大神
