### ISSUE TITLE
H264+G711a封装TS，播放没有音频

### ISSUE THREAD

**Issue by SaidInk** [ireader/media-server#328]
参考了示例代码，将H264+G711a封装到TS，然而播放时有视频没音频。使用ffprobe查看，音频为mp3?
![image](https://github.com/ireader/media-server/assets/17247866/5a5fe5d5-5fed-4892-bb87-fa082a989aa9)

**Comment by ireader** [comment]
g711封装到ps/ts 是非标的,  ffmpeg只支持hik私有扩展的g711音频.

**Comment by SaidInk** [comment]
好。明白了，感谢！
