### ISSUE TITLE
How to compile RTSP test?

### ISSUE THREAD

**Issue by yaoyecaizi** [ireader/media-server#33]
I want to use rtsp server,but i don't know how to use the librtsp,can you help me?thanks!

**Comment by yaoyecaizi** [comment]
Aha,i know how to compile in ubuntu16.04-64:1、git clone media-server,git clone sdk,put them in the same folder;2、in sdk:'make'、‘‘make test’;3、in media-server:'make'、‘make test’.
But i maybe find a new problem:when i 'make test' in media-server,it shows:'media-server/test/../librtsp/test/rtp-udp-transport.cpp:30：对‘ip_route_get’未定义的引用
collect2: error: ld returned 1 exit status',i commented it and it compiled, but there was a segment error at runtime.

**Comment by yaoyecaizi** [comment]
Follow your instructions,‘make test’ is OK，but the problem:'test: source/client/rtsp-client-auth.c:263: rtsp_client_auth_test: Assertion `strstr(rtsp.req, "response=\"6629fae49393a05397450978507c4ef1\"")' failed.
Makefile:37: recipe for target 'test' failed
make: *** [test] ...' still exist.

**Comment by ireader** [comment]
MD5错误，先注释这条测试，我查一下原因。

**Comment by yaoyecaizi** [comment]
Ok,i try again floow your instruction,'make test' success.
When you find the reason,please tell me,thanks!

**Comment by yaoyecaizi** [comment]
Yeah,it's ok,thanks again!

**Comment by GanKanTechnology** [comment]
@yaoyecaizi @ireader 请问一下你是如何做的啊？我在最后一步交叉编译的时候没有成功，总提示找不到命令，平台是CentOS

**Comment by ireader** [comment]
在centos上编译，还是在centos平台上交叉编译arm程序？ 
看你在其它问题上的提问，应该是不需要交叉编译，centos上直接make即可。
依赖库：github.com/ireader/sdk
