### ISSUE TITLE
flv支持seek操作

### ISSUE THREAD

**Issue by yigu-cao** [ireader/media-server#334]
flv 只有read write，如何实现seek，可以帮忙给个思路么

**Comment by ireader** [comment]
csdn有flv seek方案, 可以参考去实现.

**Comment by yigu-cao** [comment]
https://blog.csdn.net/u010868213/article/details/120712887?utm_medium=distribute.pc_relevant.none-task-blog-2~default~baidujs_utm_term~default-0-120712887-blog-96176742.235^v43^pc_blog_bottom_relevance_base1&spm=1001.2101.3001.4242.1&utm_relevant_index=3
找到链接，感谢
