### ISSUE TITLE
大文件probe时间较长，如何优化

### ISSUE THREAD

**Issue by yigu-cao** [ireader/media-server#335]
超过2G的大文件，probe阶段时间过长，大于一分钟，probe阶段只需获取媒体基本信息，可以提供优化思路么

**Comment by ireader** [comment]
请详细描述下问题, 包括文件格式, 音视频详情, probe方式等.

**Comment by ireader** [comment]
mkv_reader_read会把整个文件全部读一遍， 所以打开比较慢。 

可以尝试下mkv_reader_read2函数， 编译时加上MKV_LIVE_STREAMING宏。

**Comment by yigu-cao** [comment]
格式： MP4
Size: 2.2G
流程：mov_reader_create--->mov_reader_getinfo
现象：媒体信息解析失败，大文件均解析失败，是哪里判断有问题么
![image](https://github.com/ireader/media-server/assets/125543905/8d811a8b-4dbb-43b3-96e7-da9f15daeac8)

**Comment by yigu-cao** [comment]
加打印试下，分析哪些字段判断问题
