### ISSUE TITLE
这个是用在什么平台上的啊？

### ISSUE THREAD

**Issue by GanKanTechnology** [ireader/media-server#36]
可以用在Linux上做rstp服务器吗？
CentOS上如何编译运行呢？

arm-hisiv100nptl-linux-ar: Command not found

**Comment by yapingcat** [comment]
跨平台的

发自我的 iPhone

**Comment by yapingcat** [comment]
Centos  windows 都可以用 我试过
arm平台没试过

发自我的 iPhone

**Comment by GanKanTechnology** [comment]
@yapingcat 你好，感谢回复，我是想在CentOS上搭建一个能支持hls、rstp的服务器，看了他这个感觉应该比较好，但是没有明白该如何搭建这个服务器以及如何去使用，可以分享一下您在CentOS上是如何做的吗？谢谢

**Comment by ireader** [comment]
1. centos编译直接make即可（先下载依赖的github.com/ireader/sdk），arm-hisiv100nptl-linux-ar是arm平台的编译方式。
2. 目前只提供了hls、rtsp开发库，需要集成开发后才能完整提供HLS、RTSP服务。如果只想搭建服务，可以考虑使用nginx with rtmp module， live555等开源服务。

**Comment by GanKanTechnology** [comment]
好的，了解，非常感谢两位的解答.
