### ISSUE TITLE
代码问题反馈

### ISSUE THREAD

**Issue by HuntCode** [ireader/media-server#361]
大佬，这个地方的移位操作是8位吧？看上去应该跟上一个PCR字段类似
![image](https://github.com/user-attachments/assets/8f5baec0-e9c2-43ec-b239-f4b2acf0eac4)

**Comment by ireader** [comment]
感谢反馈，确实是有问题

**Comment by HuntCode** [comment]
大佬，请教一下问题

最近在处理TS数据（封装在RTP中），只关注H264，场景中RTP会丢包，目前没有支持RTCP处理重传，所以TS数据一定有CC不连续的情况，这种情况下，mpeg-ts相关代码中应该是通过payload_unit_start_indicator和新的H264 access unit进行判断，然后触发回调

比如中间乱序，flag应该是MPEG_FLAG_PACKET_CORRUPT | MPEG_FLAG_PACKET_LOST，这时的PES数据可能上一包缺少尾部，后一包缺少头部，PES头指定的数据长度假如是5000字节，pkt缓存的实际长度可能是6000字节，紧接着再来一个PES头，就会将数据上报，这时的数据不能用，只能判断flag是不是MPEG_FLAG_PACKET_CORRUPT，如果下一次中途没有出错，应该就是上报MPEG_FLAG_PACKET_LOST，再一次没有出错，才会不上报错误标志，是这样吗？当然，中间能判断上报数据包是否为I帧

接收端这边通过MPEG_FLAG_PACKET_CORRUPT丢包标志，会向发送端请求IDR帧

在这种丢包场景下，必然会花屏，因为我不熟悉H264底层的一些内容，只了解有GOP的概念，不知道在TS解析过程中，能不能判断出这种GOP的数据组，达到虽然画面卡一下，但是不花屏的效果？

希望能解惑，谢谢！

**Comment by ireader** [comment]
丢包不太好处理，花屏很难避免，通常是从2个层面来解决：
1. rtp丢包可以通过rtp flag的lost判断， rtp判断丢包时，可以把数据丢弃，上层程序设置丢包等待关键帧标记wait_for_keyframe，然后向发送端请求IDR帧；
2. mpeg-ts回调时，如果出现来说MPEG_FLAG_PACKET_CORRUPT，同样如上处理；
3. 上层程序判断wait_for_keyframe是否为true，等于true时，数据全部丢弃，直到收到关键帧，并且没有MPEG_FLAG_PACKET_CORRUPT标记时，wait_for_keyframe=false，数据送到解码器播放

**Comment by HuntCode** [comment]
> 丢包不太好处理，花屏很难避免，通常是从2个层面来解决：
> 
> 1. rtp丢包可以通过rtp flag的lost判断， rtp判断丢包时，可以把数据丢弃，上层程序设置丢包等待关键帧标记wait_for_keyframe，然后向发送端请求IDR帧；
> 
> 2. mpeg-ts回调时，如果出现MPEG_FLAG_PACKET_CORRUPT，同样如上处理；
> 
> 3. 上层程序判断wait_for_keyframe是否为true，等于true时，数据全部丢弃，直到收到关键帧，并且没有MPEG_FLAG_PACKET_CORRUPT标记时，wait_for_keyframe=false，数据送到解码器播放

好的，谢谢，后续应该还是得加上rtcp

**Comment by HuntCode** [comment]
![image](https://github.com/user-attachments/assets/a26723a8-120e-4907-8a65-f3dfa432659f)
这是手机端发送的TS数据包，像这样长度为0的PES数据，是不是大概率说明手机端系统处理有问题，这种0长度的数据包，看数据内容应该是P帧，但是这种数据就比较麻烦，占用缓存队列不说，数据相当于强制缺少了一部分，必花屏，另外很可能把后面有长度的PES数据也搞得有问题，因为我处理队列时，超出限制长度，会快速跟进队列头的RTP序列号，中间还是会算成丢包（CC不连续），相对来说Windows系统发送的TS数据就会相对稳定的多
![image](https://github.com/user-attachments/assets/e960ef31-517c-4bf4-b821-016a93421499)

**Comment by ireader** [comment]
长度为0是正常情况，超过64k，单个ps包无法表示时，这个长度值就会设置成0
