### ISSUE TITLE
libflv/test/h265-flv-test.cpp 跑不通，h265_annexbtomp4一直返回0

### ISSUE THREAD

**Issue by KkemChen** [ireader/media-server#364]
如题，我使用ffmpeg读取了一个h265的mp4，然后参考`libflv/test/h265-flv-test.cpp` 尝试写到一个flv中，但是h265_annexbtomp4一直返回0  无法正常写入文件

**Comment by ireader** [comment]
h265-flv-test.cpp 要求读入的h265文件码流格式是annex-b的。

可以按照如下方式验证：
1. 生成265流文件：ffmpeg -i test.mp4 -c:v copy -an test.h265

2. 转换成FLV文件: hevc2flv_test("test.h265", "test.h265.flv");

**Comment by KkemChen** [comment]
> h265-flv-test.cpp 要求读入的h265文件码流格式是annex-b的。
> 
> 可以按照如下方式验证：
> 
> 1. 生成265流文件：ffmpeg -i test.mp4 -c:v copy -an test.h265
> 2. 转换成FLV文件: hevc2flv_test("test.h265", "test.h265.flv");

嗯嗯，用h265裸流是能跑通的。

我今天上午发现 应该是对`ctx.ptr = buffer;`的赋值不对。 我代码里是`av_read_frame`后每次都把`ctx.ptr `赋值为 `pkt->data`, 导致后续出现问题。

后面我改为直接在`av_read_frame`后就调用
`flv_muxer_hevc(flv, pkt->data, pkt->size, pkt->pts, pkt-->dts);`
好像就可以正常写入flv文件了，而且也可以进行播放。 就是不知道这样有没有问题。

我用flvanalyer 查看生成的flv文件，会有这样的报错，不知道有没有影响
![image](https://github.com/user-attachments/assets/877a0dc1-e0f9-447f-982f-d8a2399be127)

**Comment by ireader** [comment]
![image](https://github.com/user-attachments/assets/29b5b7e9-8c29-4b17-99eb-3431060e0b29)
看着这个位置时间戳和数据有问题，可以确认下位置是不是文件末尾

**Comment by KkemChen** [comment]
是的，这个位置 写入了Hevc sequence end

**Comment by KkemChen** [comment]
用potplayer 能正常播放， 但是放服务器上，然后用网页播放器 mpegts.js 就播不了😂。

>网页播放器日志
![image](https://github.com/user-attachments/assets/601e4458-0a7a-4336-b40e-ad82b3afa6c1)


 用ffmpeg6.1之后的版本，对这个录像文件再导出一下`ffmpeg -i .\20241206_145055_test_43008104701.flv -c:v copy -an -f flv output.flv`,然后 网页播放器就也能播了。
我对比了一下两个文件的二进制，好像就多了一个VideoInfo/Command frame 其他都没变

![image](https://github.com/user-attachments/assets/7ff44276-0376-46ba-9810-c3126d7587a6)
