### ISSUE TITLE
rtp_mpeg4_generic_pack_input函数分包的size写入不正确的bug

### ISSUE THREAD

**Issue by Mangomm** [ireader/media-server#367]
## 现象描述
https://gitee.com/ireader/media-server子模块的librtp库，在rtp_mpeg4_generic_pack_input()函数分包时出现错误，分包时，au headers应该写入的是分包时的大小，而不是写入整个包的大小。 否则在解包时，会进入rtp_decode_mpeg4_generic()函数的断言assert(0);：

## 如何复现
1. 设置rtp_packet_setsize是512(内部的最小值被我改了512)，创建"mpeg4-generic"的编码解码结构；
2. 打开一个time.aac文件，每次将一帧aac数据(包含7个字节adts头)，通过rtp_paylpad_encode_input()送进编码，然后再回调函数立马送去解码;
3. 解码会在rtp_decode_mpeg4_generic()的for (i = 0; i < au_numbers; i++)中的assert(0);触发断言；

## 相关截图
![image](https://github.com/user-attachments/assets/016a3186-1d22-4383-a4c2-2d52024bb32c)

修改后可以正常解包的截图：
![image](https://github.com/user-attachments/assets/a0106b7b-a2d4-4ff2-96af-a1283ba5e450)

**Comment by ireader** [comment]
感谢反馈，问题出在解包rtp_decode_mpeg4_generic，这里的assert有问题，周末fix下这块代码
