### ISSUE TITLE
Just a question

### ISSUE THREAD

**Issue by rcvangemert** [ireader/media-server#4]
hi ireader, I am testing suitablity of your mpeg ts code in my android app and I like what I see!

Just wondering why you cue the audio samples in mpeg_ts_test.cpp and then output them when a video packet is detected?

static void ts_packet(void* param, int avtype, int64_t pts, int64_t dts, void* data, size_t bytes)
{
	struct mpeg_ts_test_t* ctx = (struct mpeg_ts_test_t*)param;
	char s_char[] = { ' ', 'A', 'V', 'a', 'v' };
	printf("[%c] pts: %08lu, dts: %08lu\n", s_char[avtype], (unsigned long)pts, (unsigned long)dts);

	if (PSI_STREAM_AAC == avtype)
	{
		std::auto_ptr<char> ptr(new char[bytes]);
		memcpy(ptr.get(), data, bytes);
		ctx->audios.push_back(mpeg_ts_test_t::audio(ptr, bytes, pts, dts));
	}
	else if (PSI_STREAM_H264 == avtype)
	{
		while (!ctx->audios.empty())
		{
			const mpeg_ts_test_t::audio& audio = ctx->audios.front();
			if (audio.dts > dts)
				break;

			mpeg_ts_write(ctx->ts, PSI_STREAM_AAC, audio.pts, audio.dts, audio.data.get(), audio.bytes);
			ctx->audios.pop_front();
		}

		mpeg_ts_write(ctx->ts, avtype, pts, dts, data, bytes);
	}
	else
	{
		assert(0);
	}
}

**Comment by ireader** [comment]
just reorder audio/video frame, don't need anymore.

I have update this file:

static void ts_packet(void* ts, int avtype, int64_t pts, int64_t dts, void* data, size_t bytes)
{
	printf("[%s] pts: %08lu, dts: %08lu\n", ts_type(avtype), (unsigned long)pts, (unsigned long)dts);

	mpeg_ts_write(ts, avtype, pts, dts, data, bytes);
}

**Comment by rcvangemert** [comment]
android ndk did not support the <LIST> so I tested as per your mod and the re-encode works well. Exoplayer replayes the re encoded file ok.  Thanks.
