### ISSUE TITLE
Compile failed with media-server.xcworkspace in macos 10.14.4

### ISSUE THREAD

**Issue by xsw9527** [ireader/media-server#40]
Showing All Errors Only
 Undefined symbol: _rtsp_server_get_parameter

 Undefined symbol: _rtsp_server_reply_get_parameter

Undefined symbol: _rtsp_server_reply_set_parameter

Undefined symbol: _rtsp_server_set_parameter

**Comment by ireader** [comment]
抱歉xcode项目文件没有及时更新，链接失败的这个几个函数实现在librtsp\source\server\rtsp-server-parameter.c，将这个文件添加到项目中即可。

本地的xcode更改较多，暂时不方面更新，抱歉。
