### ISSUE TITLE
在test目录下make会出现以下错误，请问这是什么原因？

### ISSUE THREAD

**Issue by ZSC714725** [ireader/media-server#45]
在test目录下执行make clean;make后存在以下问题：
../../sdk/libhttp/debug.linux/libhttp.a(http-cookie.o)：在函数‘http_cookie_parse_test’中：
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:251：对‘__asan_handle_no_return’未定义的引用
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:252：对‘__asan_handle_no_return’未定义的引用
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:257：对‘__asan_handle_no_return’未定义的引用
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:258：对‘__asan_handle_no_return’未定义的引用
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:263：对‘__asan_handle_no_return’未定义的引用
../../sdk/libhttp/debug.linux/libhttp.a(http-cookie.o):/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:264: 跟着更多未定义的参考到 __asan_handle_no_return
../../sdk/libhttp/debug.linux/libhttp.a(http-cookie.o)：在函数‘http_cookie_create_test’中：
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:287：对‘__asan_option_detect_stack_use_after_return’未定义的引用
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:287：对‘__asan_stack_malloc_2’未定义的引用
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:289：对‘__asan_handle_no_return’未定义的引用
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:290：对‘__asan_handle_no_return’未定义的引用
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:291：对‘__asan_handle_no_return’未定义的引用
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:292：对‘__asan_handle_no_return’未定义的引用
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:293：对‘__asan_handle_no_return’未定义的引用
../../sdk/libhttp/debug.linux/libhttp.a(http-cookie.o):/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:294: 跟着更多未定义的参考到 __asan_handle_no_return
../../sdk/libhttp/debug.linux/libhttp.a(http-cookie.o)：在函数‘_GLOBAL__sub_D_00099_0_http_cookie.c’中：
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:309：对‘__asan_unregister_globals’未定义的引用
../../sdk/libhttp/debug.linux/libhttp.a(http-cookie.o)：在函数‘_GLOBAL__sub_I_00099_1_http_cookie.c’中：
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:309：对‘__asan_init_v4’未定义的引用
/home/zang/rtspserver/sdk/libhttp/source/http-cookie.c:309：对‘__asan_register_globals’未定义的引用

**Comment by yapingcat** [comment]
这个估计和gcc版本有关系 我记得在gcc4.8之前没有集成libasan.so库存
如果低于这个版本需要手动下载libasan.so库

**Comment by yapingcat** [comment]
可以yum安装

**Comment by ZSC714725** [comment]
> 可以yum安装

我的gcc版本是gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3) ，
而且我的gcc下面有libasan.so
./usr/lib/gcc/x86_64-linux-gnu/7/libasan.so

**Comment by ZSC714725** [comment]
> 可以yum安装
我的gcc版本要高于4.8，gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3) 
而且我gcc目录下有libasan.so

**Comment by ZSC714725** [comment]
> > 可以yum安装
> > 我的gcc版本要高于4.8，gcc version 7.3.0 (Ubuntu 7.3.0-16ubuntu3)
> > 而且我gcc目录下有libasan.so

我的编译顺序如下：现在sdk目录下执行make clean;make
再进入media-server目录执行make clean;make；接着在test目录下执行make clean;make，就会出现以下错误

**Comment by ireader** [comment]
可以去掉media-server/gcc.mk和sdk/gcc.mk文件中-fsanitize=address参数
CFLAGS += -g -Wall -fsanitize=address
改成
CFLAGS += -g -Wall
