### ISSUE TITLE
libmpeg  psm 函数有问题

### ISSUE THREAD

**Issue by aimybbe** [ireader/media-server#47]
size_t psm_write(const struct psm_t *psm, uint8_t *data)
{
。。。。。。

	// elementary_stream_map_length 16-bits  
      //  elementary_stream_map_length    not include  CRC32
    // nbo_w16(data+10, (uint16_t)(j-12+4));    
       nbo_w16(data+10, (uint16_t)(j-12)) ;
	// program_stream_map_length:16
	nbo_w16(data+4, (uint16_t)(j-6+4)); // 4-bytes crc32

	// crc32
	crc = mpeg_crc32(0xffffffff, data, (uint32_t)j);
	data[j+3] = (uint8_t)((crc >> 24) & 0xFF);
	data[j+2] = (uint8_t)((crc >> 16) & 0xFF);
	data[j+1] = (uint8_t)((crc >> 8) & 0xFF);
	data[j+0] = (uint8_t)(crc & 0xFF);

	return j+4;
}

**Comment by ireader** [comment]
非常感谢!
