### ISSUE TITLE
rtmp_packet_parse函数无法正确解析RTMP_CHUNK_TYPE_2，RTMP_CHUNK_TYPE_3的chunk

### ISSUE THREAD

**Issue by zentelfong** [ireader/media-server#49]
服务器使用srs

**Comment by ireader** [comment]
无法复现你的问题，能提供dump出来的rtmp数据吗？

librtmp/test目录下的rtmp-input-test.cpp文件可以直接解析原始rtmp包，可以用这个文件中的rtmp_input_test测试。

或者提供一份原始的rtmp dump数据。
