### ISSUE TITLE
pts和dts时间戳是毫秒单位吗？如果是30帧，pts和dts是33.3，但这里填整数

### ISSUE THREAD

**Issue by ht101996** [ireader/media-server#51]
pts和dts时间戳是毫秒单位吗？如果是30帧，pts和dts是33.3，但这里填整数，要怎么处理？

flv_muxer_h264_nalu(m, nalu, next - nalu, pts, dts);
uint8_t type = *nalu & 0x1f;
if (type > 0 && type < 6)
{
	pts += 40;
	dts += 40;
}

**Comment by ht101996** [comment]
我搞错了

**Comment by ireader** [comment]
因264文件里没有时间戳，需要根据外部信息生成pts、dts。
如果帧率是30fps，可以填33,33,34，循环
