### ISSUE TITLE
fmp4

### ISSUE THREAD

**Issue by vinnitu** [ireader/media-server#54]
Hello!

Before I'll continue previous question, I want to know how to properly get fmp4 with your library.
So I expect get something like this

![image](https://user-images.githubusercontent.com/432168/60884801-8c862700-a256-11e9-9aea-6925b7ec9cc7.png)

check [here](http://mp4parser.com/) 

Can you show code example?

Thx.

**Comment by ireader** [comment]
I'm sorry it's too late.  

libmov/test/fmp4-writer-test.cpp is a example to generate a fmp4 file.

**Comment by vinnitu** [comment]
how do you compile it? where is main() function?

**Comment by ireader** [comment]
in media-server/test/test.cpp
![image](https://user-images.githubusercontent.com/1535445/61626094-ed7a1a00-acae-11e9-9b44-908b5ca93cd9.png)
uncomment fmp4_writer_test, replace with 
fmp4_writer_test(960, 400, "oceans.mp4.flv", "oceans.frag.mp4");

download [oceans.mp4.flv](https://1drv.ms/u/s!Al78HXIbHIOGgVAeawfrSN4KJ4aF?e=Qs2E6P)

compile: 
1. clone https://github.com/ireader/media-server
2. clone https://github.com/ireader/sdk
3. cd media-server
4. make && make test
