### ISSUE TITLE
How to run RTSP server main loop?

### ISSUE THREAD

**Issue by VasyaSmolyar** [ireader/media-server#56]
I've tried to write a simple test RTSP server that should only respond to option requests. But I can't find a way to start the created server. I've found only the AIO function listen in the source code of the tests. Here is my code:
```C++
#include <iostream>

#include <cstring>
#include <rtsp-server.h>

using namespace std;

int options(void* ptr, rtsp_server_t* rtsp, const char* uri) {
  return rtsp_server_reply_options(rtsp, 200);
}

int main() {
  char buf1[1024], buf2[1024];
  rtsp_handler_t handler;
  rtsp_server_t* rtsp;
  memset(&handler, 0, sizeof(handler));
  handler.onoptions = &options;
  rtsp = rtsp_server_create(NULL, 8000, &handler, (void*)buf1, (void*)buf2);
  if(rtsp == nullptr) {
    cerr << "Error!" << endl;
    return 1;
  }
  //int ret = rtsp_server_input(rtsp, )
  while(1) {

  }
  cout << "Hello world! " << rtsp_server_destroy(rtsp) << endl;
}
```
Here is part of source rtsp-server-test.cpp with the listen function:
```C++
#define N_AIO_THREAD 4
extern "C" void rtsp_example()
{
	aio_worker_init(N_AIO_THREAD);

	struct aio_rtsp_handler_t handler;
	memset(&handler, 0, sizeof(handler));
	handler.base.ondescribe = rtsp_ondescribe;
    handler.base.onsetup = rtsp_onsetup;
    handler.base.onplay = rtsp_onplay;
    handler.base.onpause = rtsp_onpause;
    handler.base.onteardown = rtsp_onteardown;
	handler.base.close = rtsp_onclose;
    handler.base.onannounce = rtsp_onannounce;
    handler.base.onrecord = rtsp_onrecord;
	handler.base.onoptions = rtsp_onoptions;
	handler.base.ongetparameter = rtsp_ongetparameter;
	handler.base.onsetparameter = rtsp_onsetparameter;
//	handler.base.send; // ignore
	handler.onerror = rtsp_onerror;
    
	void* tcp = rtsp_server_listen(NULL, 554, &handler, NULL); assert(tcp);
//	void* udp = rtsp_transport_udp_create(NULL, 554, &handler, NULL); assert(udp);

	// test only
    while(1)
    {
		system_sleep(5);

		TSessions::iterator it;
		AutoThreadLocker locker(s_locker);
		for(it = s_sessions.begin(); it != s_sessions.end(); ++it)
		{
			rtsp_media_t &session = it->second;
			if(1 == session.status)
				session.media->Play();
		}

		// TODO: check rtsp session activity
    }

	aio_worker_clean(N_AIO_THREAD);
	rtsp_server_unlisten(tcp);
//	rtsp_transport_udp_destroy(udp);
}
#endif
``` 
How to run my simple test server?

**Comment by ireader** [comment]
Every rtsp_server_t represent a rtsp session in a tcp connection.

static int rtsp_send(void* ptr, const void* data, size_t bytes)
{
	rtsp_context_t* ctx = (rtsp_context_t*)param;
	return bytes == socket_send(ctx->conn, data, bytes, 0) ? 0 : -1;
}

static int options(void* ptr, rtsp_server_t* rtsp, const char* uri) {
  return rtsp_server_reply_options(rtsp, 200);
}

int thread_entry(void* param)
{
    char buf1[1024], buf2[1024];
    rtsp_context_t* ctx = (rtsp_context_t*)param;

     rtsp_handler_t handler;
     rtsp_server_t* rtsp;
     memset(&handler, 0, sizeof(handler));
     handler.onoptions = options;
     handler.send = rtsp_send;
     rtsp = rtsp_server_create(NULL, 8000, &handler, (void*)ptr1, ctx);

    while(1)
    {
// select + read rtsp request
            socket_select(ctx->conn);
            socket_recv(ctx->conn, buffer, buffersize);
 
// same as rtsp_session_onrecv (rtsp-server-tcp.c)
            remain = buffersize;
            rtsp_server_input(ctx, buffer, &remain);
    }

    rtsp_server_destroy(rtsp);
    return 0;
}

int main() {
  socket_t tcp = socket_tcp_listen(ip, (u_short)port, SOMAXCONN);
  while(1)
  {
      socket conn = socket_accept(tcp, &addr, &addrlen);
      rtsp_context_t* ctx = new rtsp_context(conn, &addr, &addrlen);
      thread_start(ctx);

      // wait for another rtsp connection
  }

    // wait for all thread/connection close
   return 0;
}

**Comment by VasyaSmolyar** [comment]
Thanks
