### ISSUE TITLE
mpeg库解析ps包问题

### ISSUE THREAD

**Issue by ht101996** [ireader/media-server#59]
![image](https://user-images.githubusercontent.com/2375504/62913089-5855d700-bdbd-11e9-9b59-d709767a0115.png)

mpeg-packet.c 文件，在解析包含h264的ps包的时候，开始一会儿还正常，过了一会儿后就一直报need more data，无法正常恢复了  请问大神这是什么原因造成的？有什么办法简单规避一下吗

**Comment by ireader** [comment]
提供下有问题的ps文件？

**Comment by ht101996** [comment]
[test.ps.zip](https://github.com/ireader/media-server/files/3496078/test.ps.zip)

**Comment by ht101996** [comment]
test.ps.zip 麻烦大神帮忙看看这个ps，vlc可以播 只是会跳帧  但是mpeg库没法做解析 麻烦大神帮忙分析一下

**Comment by ht101996** [comment]
麻烦大神帮忙看看这个ps，vlc可以播 只是会跳帧 但是mpeg库没法做解析 麻烦大神帮忙分析一下 https://pan.baidu.com/s/1mjE_MRhohBHH30QjCUJZyQ

**Comment by ireader** [comment]
ps数据包本身有问题，可以尝试兼容，但是建议应该从正确生成ps文件着手。

**Comment by ht101996** [comment]
test.ps.zip
ps 文件是用的media-server 的rtp库解包出来的，数据本身是有点问题，就是希望看能不能兼容一下，要求上游系统改的可能性不大

**Comment by ht101996** [comment]
ps 文件是用的media-server 的rtp库解包出来的，数据本身是有点问题，就是希望看能不能兼容一下，要求上游系统改的可能性不大，无助中  😂
[test.ps.zip](https://github.com/ireader/media-server/files/3499916/test.ps.zip)

**Comment by ireader** [comment]
![image](https://user-images.githubusercontent.com/1535445/63081280-ca711c00-bf75-11e9-90a2-1fdf9ee87a23.png)
如图所示ps文件有问题，可能是接收rtp包时有丢包。 可以尝试下把socket接收buffer调大。setsockopt(SOL_SOCKET, SO_RCVBUF)

**Comment by ht101996** [comment]
那就是上游ps的问题了，我这边暂时也没什么太好的办法，做了简单的包过滤，不过还是会有花屏的问题

**Comment by ireader** [comment]
> ![image](https://user-images.githubusercontent.com/2375504/62913089-5855d700-bdbd-11e9-9b59-d709767a0115.png)
> 
> mpeg-packet.c 文件，在解析包含h264的ps包的时候，开始一会儿还正常，过了一会儿后就一直报need more data，无法正常恢复了 请问大神这是什么原因造成的？有什么办法简单规避一下吗

这个问题能复现吗？ 目前提供的ps测试文件没有复现这个问题。

**Comment by ireader** [comment]
ps应用场景是可靠传输，如果确实无法避免丢包情况，可以使用如下代码：
size_t ps_demuxer_input(struct ps_demuxer_t* ps, const uint8_t* data, size_t bytes)
{
	size_t i, n;

	do
	{
		for (i = 0; i + 3 < bytes && 0x00 == data[i] && 0x00 == data[i + 1] && 0x01 == data[i + 2]; )
		{
			if (PES_SID_START == data[i + 3])
			{
				i += pack_header_read(&ps->pkhd, data + i, bytes - i);
			}
			else if (PES_SID_SYS == data[i + 3])
			{
				i += system_header_read(&ps->system, data + i, bytes - i);
			}
			else if (PES_SID_END == data[i + 3])
			{
				i += 4;
			}
			else
			{
				n = pes_packet_read(ps, data + i, bytes - i);
				i += n;

				if (0 == n)
					break;
			}
		}

		while (i + 5 < bytes)
		{
			if (0x00 == data[i] && 0x00 == data[i + 1] && 0x01 == data[i + 2])
				break;
			i++;
		}
	} while (i + 5 < bytes);

	return i;
}

**Comment by ht101996** [comment]
> > ![image](https://user-images.githubusercontent.com/2375504/62913089-5855d700-bdbd-11e9-9b59-d709767a0115.png)
> > mpeg-packet.c 文件，在解析包含h264的ps包的时候，开始一会儿还正常，过了一会儿后就一直报need more data，无法正常恢复了 请问大神这是什么原因造成的？有什么办法简单规避一下吗
> 
> 这个问题能复现吗？ 目前提供的ps测试文件没有复现这个问题。

好像保存文件没法复现，但是实时流就会有这种情况

**Comment by ht101996** [comment]
> ps应用场景是可靠传输，如果确实无法避免丢包情况，可以使用如下代码：
> size_t ps_demuxer_input(struct ps_demuxer_t* ps, const uint8_t* data, size_t bytes)
> {
> size_t i, n;
> 
> ```
> do
> {
> 	for (i = 0; i + 3 < bytes && 0x00 == data[i] && 0x00 == data[i + 1] && 0x01 == data[i + 2]; )
> 	{
> 		if (PES_SID_START == data[i + 3])
> 		{
> 			i += pack_header_read(&ps->pkhd, data + i, bytes - i);
> 		}
> 		else if (PES_SID_SYS == data[i + 3])
> 		{
> 			i += system_header_read(&ps->system, data + i, bytes - i);
> 		}
> 		else if (PES_SID_END == data[i + 3])
> 		{
> 			i += 4;
> 		}
> 		else
> 		{
> 			n = pes_packet_read(ps, data + i, bytes - i);
> 			i += n;
> 
> 			if (0 == n)
> 				break;
> 		}
> 	}
> 
> 	while (i + 5 < bytes)
> 	{
> 		if (0x00 == data[i] && 0x00 == data[i + 1] && 0x01 == data[i + 2])
> 			break;
> 		i++;
> 	}
> } while (i + 5 < bytes);
> 
> return i;
> ```
> 
> }

好的，我试试效果

**Comment by ireader** [comment]
> 那就是上游ps的问题了，我这边暂时也没什么太好的办法，做了简单的包过滤，不过还是会有花屏的问题

上游ps格式是不太标准，但是大致封装没问题，应该是rtp接收有丢包。

如果是高清视频源，得看看本地socket接收buffer是否足够，否则可能传输过程中没有丢包，但是本地buffer满导致丢包。

**Comment by ht101996** [comment]
> > 那就是上游ps的问题了，我这边暂时也没什么太好的办法，做了简单的包过滤，不过还是会有花屏的问题
> 
> 上游ps格式是不太标准，但是大致封装没问题，应该是rtp接收有丢包。
> 
> 如果是高清视频源，得看看本地socket接收buffer是否足够，否则可能传输过程中没有丢包，但是本地buffer满导致丢包。

Tcp 不太可能丢，我与上游之间有一部分是源是4K有线设备的，也没有什么问题。但就是那种移动设备传上来的720p视频就丢包比较严重

**Comment by ireader** [comment]
rtp over tcp？ 中间传输环境全部是tcp吗？

**Comment by ht101996** [comment]
> rtp over tcp？ 中间传输环境全部是tcp吗？

是的

**Comment by ht101996** [comment]
> ps应用场景是可靠传输，如果确实无法避免丢包情况，可以使用如下代码：
> size_t ps_demuxer_input(struct ps_demuxer_t* ps, const uint8_t* data, size_t bytes)
> {
> size_t i, n;
> 
> ```
> do
> {
> 	for (i = 0; i + 3 < bytes && 0x00 == data[i] && 0x00 == data[i + 1] && 0x01 == data[i + 2]; )
> 	{
> 		if (PES_SID_START == data[i + 3])
> 		{
> 			i += pack_header_read(&ps->pkhd, data + i, bytes - i);
> 		}
> 		else if (PES_SID_SYS == data[i + 3])
> 		{
> 			i += system_header_read(&ps->system, data + i, bytes - i);
> 		}
> 		else if (PES_SID_END == data[i + 3])
> 		{
> 			i += 4;
> 		}
> 		else
> 		{
> 			n = pes_packet_read(ps, data + i, bytes - i);
> 			i += n;
> 
> 			if (0 == n)
> 				break;
> 		}
> 	}
> 
> 	while (i + 5 < bytes)
> 	{
> 		if (0x00 == data[i] && 0x00 == data[i + 1] && 0x01 == data[i + 2])
> 			break;
> 		i++;
> 	}
> } while (i + 5 < bytes);
> 
> return i;
> ```
> 
> }

增加了这段代码后，会导致正常ps包也解析不了
