### ISSUE TITLE
How it work?

### ISSUE THREAD

**Issue by friman** [ireader/media-server#6]
Hello there,
Can you tell me how can it run on windows?

Regards

**Comment by ireader** [comment]
Create an exe project, implement main function, use API in main function, or you can call test function in libxxx/test directory.

e.g.:
1. add librtmp/test/rtmp-publish-test.cpp to your EXE project
2. add dependence/reference librtmp & libflv project
3. declare void rtmp_publish_test(const char* host, const char* app, const char* stream, const char* flv);
4. call rtmp_publish_test in your main function.

**Comment by friman** [comment]
Thanks for your reply!
I will try follow your suggestion

**Comment by ireader** [comment]
if you have any question, please reopen this issue.
