### ISSUE TITLE
flv 支持g711

### ISSUE THREAD

**Issue by ht101996** [ireader/media-server#60]
flv 打包能支持一下g711吗？

**Comment by ireader** [comment]
flv里有g711，直接用即可

**Comment by ht101996** [comment]
![image](https://user-images.githubusercontent.com/2375504/63080823-afea7300-bf74-11e9-879a-c389f4bd2b9b.png) 
目前flv muxer只支持aac、mp3、avc(264)、hevc 不是吗？g711的话用哪个呢？请大神明鉴

**Comment by hujixiang** [comment]
我理解g711 应该不在flv标准内的吧。至少g711的采用率 8K 16K都无法通过flv表述。

2019-08-15 15:53 GMT+08:00, ht101996 <notifications@github.com>:

**Comment by ht101996** [comment]
> 我理解g711 应该不在flv标准内的吧。至少g711的采用率 8K 16K都无法通过flv表述。 2019-08-15 15:53 GMT+08:00, ht101996 <notifications@github.com>:
> […](#)
> ![image](https://user-images.githubusercontent.com/2375504/63080823-afea7300-bf74-11e9-879a-c389f4bd2b9b.png) 目前flv muxer只支持aac、mp3、avc(264)、hevc 不是吗？g711的话用哪个呢？请大神明鉴 -- You are receiving this because you are subscribed to this thread. Reply to this email directly or view it on GitHub: [#60 (comment)](https://github.com/ireader/media-server/issues/60#issuecomment-521551215)

之前只试过aac推到rtmp，没调研过g711，看网上有一些人推过g711到rtmp  如果不行，就只能转aac了

**Comment by ireader** [comment]
![image](https://user-images.githubusercontent.com/1535445/63082664-651f2a00-bf79-11e9-9944-e548e2c105f0.png)
能不能播得看服务器端和播放端，但是flv是支持g711的。
