### ISSUE TITLE
flv文件，转成m3u8之后，ubuntu上播放没问题，mac上播放报错

### ISSUE THREAD

**Issue by OceanW** [ireader/media-server#61]
flv格式的格式如下
Stream #0:0: Video: h264 (Main), yuv420p(progressive), 640x360 [SAR 1:1 DAR 16:9], 25 fps, 25 tbr, 1k tbn, 50 tbc
Stream #0:1: Audio: aac (LC), 48000 Hz, mono, fltp

mac上ffplay报错如下
PES packet size mismatch

**Comment by ireader** [comment]
未复现你的问题，可以提供HLS播放地址吗？ 或者提供FLV文件？

**Comment by OceanW** [comment]
flv的地址 http://47.95.14.10/abc.flv

**Comment by ireader** [comment]
![image](https://user-images.githubusercontent.com/1535445/63747830-9df4c280-c8da-11e9-84a0-4ec1bd143a4d.png)

这是N卡硬编的视频流？如上图所示，视频流中每帧都是AUD开头，在调用mpeg_ts_write时，flags参数需要 |0x8000，避免函数内部重复添加AUD。
如：mpeg_ts_write(ts, STREAM_VIDEO_H264, 0x8000 | (KEYFRAME & flags ? 1 : 0), pts * 90, dts * 90, data, bytes);

另一个办法是过滤掉00 00 00 01 09 50这个nalu。

**Comment by ireader** [comment]
![image](https://user-images.githubusercontent.com/1535445/63748260-98e44300-c8db-11e9-9b8d-7a76030a9322.png)

**Comment by OceanW** [comment]
可以正常播放了，谢谢
