### ISSUE TITLE
how can I push h.264 using rtsp protocol?

### ISSUE THREAD

**Issue by o-u-p** [ireader/media-server#65]
I found many method not implement, like onplay, onsend, so can I make rtsp live stream?

**Comment by ireader** [comment]
rtsp client push live stream:
1. rtsp_client_announce with live stream sdp
2. rtsp_client_setup interactive negotiation udp/tcp transport ip/port
3. rtsp_client_record start push stream
4. send rtp/rtcp packets with udp/tcp transport

implement rtsp_client_handler_t example: librtsp/test/rtsp-client-test.c

**Comment by ireader** [comment]
see more: [RFC 2326 14.6 Recording](https://www.rfc-editor.org/rfc/rfc2326.html#page-71)
