### ISSUE TITLE
Can I just segment h264 to hls?

### ISSUE THREAD

**Issue by o-u-p** [ireader/media-server#67]
I see the solution of segment of flv, so  can I just segment h264 to m3u8?

**Comment by ireader** [comment]
you can use any video codec if ts support, by apple hls specification only support h.264/h.265, and h.265 must be fMP4 container.
see: https://developer.apple.com/documentation/http_live_streaming/hls_authoring_specification_for_apple_devices

**Comment by ireader** [comment]
1. Video encoding requirements
1.1. All video MUST be encoded using H.264/AVC or HEVC/H.265.
1.5. The container format for HEVC video MUST be fMP4.

**Comment by o-u-p** [comment]
大神， 我我根据您的代码， 写了一份h264转m3u8的代码， 这边出现了花屏， 您有空的话， 能稍微花点时间帮忙看下么？



[hls_server.zip](https://github.com/ireader/media-server/files/3796872/hls_server.zip)

**Comment by ireader** [comment]
读h264文件不对，每次应该读一个nalu，可以参考 libmov/test/mov-writer-h264.c 或者librtsp/test/media/h264-file-reader.cpp

**Comment by o-u-p** [comment]
好的， 我看到了，谢谢， 其他地方应该不用改吧。

**Comment by ireader** [comment]
编译时静态链接libmpeg和libhls，不用把代码全部集成到一起。

**Comment by o-u-p** [comment]
好的， 这是测试代码， 后续要优化的，谢谢您！

**Comment by o-u-p** [comment]
看上去m3u8里的duration信息并不影响， 分片几个， 每个ts文件多大也不影响， 都放在一个ts文件里也行吧...
