### ISSUE TITLE
Subsequent SPS & PPS are forgotten, thereby crippling playback

### ISSUE THREAD

**Issue by debiandebiandebian** [ireader/media-server#68]
I have this regular `video.264` stream with two consecutive IDR frames at the start:

![](https://user-images.githubusercontent.com/53786979/68748248-6ecf3100-063f-11ea-8bc8-62337ca7e7b0.png)

Above, you can see that the second PPS was properly indexed as 1.

However, once I `libflv` this into `video.flv`, the second SPS & PPS are lost. I can confirm it by feeding it to `ffprobe`, or

![](https://user-images.githubusercontent.com/53786979/68750032-92e04180-0642-11ea-857e-bfe3a38a0557.png)

unpacking & checking it again leads to the same conclusion:

![](https://user-images.githubusercontent.com/53786979/68750628-84def080-0643-11ea-8b9e-76b5a19bd1cc.png)

This is problematic since the subsequent frames are referring to the recent `SPS` & `PPS`, and it cripples playback henceforth.

Correct me if I'm wrong, but `libflv` seemingly keeps track of [only 1 SPS & PPS at a time](https://github.com/ireader/media-server/blob/master/libflv/source/flv-muxer.c#L168), and that might be the issue here.

**Comment by ireader** [comment]
The problem is sps/pps 1 should be write with sps/pps 0。

Please try to comment "0 == flv->avc_sequence_header", like this:
![image](https://user-images.githubusercontent.com/1535445/68756214-b906e100-0644-11ea-9beb-c574fb126a60.png)

same as flv_muxer_h265.

**Comment by debiandebiandebian** [comment]
@ireader It's now playable, thanks. Yet, `pic_parameter_set_id` is still 0, and the error doesn't go away. I'll dig further.

**Comment by ireader** [comment]
2 avc sequence header should be ok for ffmpeg decoder.  Could you upload a test file?

**Comment by debiandebiandebian** [comment]
@ireader I'll elaborate further. The error message is still the same, but I can `now` play the file at least. `In short, playback is no longer a problem.`

The `only` thing I'm concerned with is that the second `pic_parameter_set_id` is still indexed as `0`, and the later frames references `1`. So, it's a `dangling` reference, but the decoder `somehow` makes its way to the right `SPS` & `PPS`.

I'm no expert, but shouldn't the second `SPS` & `PPS` should be spelled out as `1`, rather than `0`? As you can see in the very `first` screenshot, it's originally indexed as `1`.

**Comment by ireader** [comment]
[update libflv with sps/pps merge.](https://github.com/ireader/media-server/commit/620d04221f20208bad8b0c154c9a1ccc7f808a40)   please try again.

**Comment by debiandebiandebian** [comment]
@ireader Hey, I just found the cause. Check my [PR](https://github.com/ireader/media-server/pull/70).

**Comment by ireader** [comment]
Thank you very much!

**Comment by debiandebiandebian** [comment]
@ireader I really appreciate this repository. Thank you for making it public. =D
