### ISSUE TITLE
libmov合成的视频用ffplay播放不正常

### ISSUE THREAD

**Issue by zhaotao6584851** [ireader/media-server#69]
libmov muxer 用ffplay播放不正常，vlc是可以的

**Comment by ireader** [comment]
什么格式的视频源？ 能上传测试文件吗？贴下测试代码？

**Comment by zhaotao6584851** [comment]
用你的demo就是remuxer或者muxer的mp4视频，用ffplay或者ijk播放就是一直快进

**Comment by zhaotao6584851** [comment]
就是用的的demo出来的mp4合成的，ffplay播放就不行

**Comment by ireader** [comment]
用libmov/test/mov_reader_test.cpp中的mov_reader_test读一下mp4文件试试，方便的话，把输出信息帖出来行吗？

**Comment by zhaotao6584851** [comment]
demo里面有个列子，合成后为out.mp4,用ffplay播放是快进，用vlc播放正常


------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午4:33
收件人:&nbsp;"ireader/media-server"<media-server@noreply.github.com&gt;;
抄送:&nbsp;"djuie flif"<244054934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ireader/media-server] libmov合成的视频用ffplay播放不正常 (#69)




用libmov/test/mov_reader_test.cpp中的mov_reader_test读一下mp4文件试试，方便的话，把输出信息帖出来行吗？
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

demo.7z (72.83M, 2020年01月04日 19:36 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=053435661da546c9afcfbe684265061d0c50565e0752520114075404064800035a5218045006051f0901015255030c015b000603646234565c595a48531f340f&t=exs_ftn_download&code=945fde42

**Comment by zhaotao6584851** [comment]
这几天没看邮件
用ijkplay 播放也是一样快进播放



------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年11月18日(星期一) 下午4:33
收件人:&nbsp;"ireader/media-server"<media-server@noreply.github.com&gt;;
抄送:&nbsp;"djuie flif"<244054934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ireader/media-server] libmov合成的视频用ffplay播放不正常 (#69)




用libmov/test/mov_reader_test.cpp中的mov_reader_test读一下mp4文件试试，方便的话，把输出信息帖出来行吗？

**Comment by ireader** [comment]
用libmov/test/mov_reader_test.cpp中的mov_reader_test输出下mp4文件的时间戳？

**Comment by ireader** [comment]
方便的话可以上传下测试的视频源，确保生成mp4时间戳是正确的。

**Comment by zhaotao6584851** [comment]
我压缩包里有视频源，out.mp4就是合成输出的
用vlc播放是正常，用ffmpeg里的ffplay不行，ijkplayer播放也是快进播放




------------------&nbsp;原始邮件&nbsp;------------------
发件人:&nbsp;"Chen"<notifications@github.com&gt;;
发送时间:&nbsp;2019年12月5日(星期四) 晚上8:39
收件人:&nbsp;"ireader/media-server"<media-server@noreply.github.com&gt;;
抄送:&nbsp;"djuie flif"<244054934@qq.com&gt;;"Author"<author@noreply.github.com&gt;;
主题:&nbsp;Re: [ireader/media-server] libmov合成的视频用ffplay播放不正常 (#69)




方便的话可以上传下测试的视频源，确保生成mp4时间戳是正确的。
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.


从QQ邮箱发来的超大附件

demo.7z (72.83M, 2020年01月05日 10:01 到期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=0f3136384ef2149ea5cabd361132544a0503020f560556551e010f5a541f525c03541b5a520352480055575e525655550500060c37356601565c591600486658&t=exs_ftn_download&code=316872fe




out.mp4 (39.02M, 无限期)进入下载页面：http://mail.qq.com/cgi-bin/ftnExs_download?k=09383939be84bdcba3c3b23745360019060e085f52505053180d0c08051b0652030a140155050a1b060c005c02535605055b5d5c63313259404c17541302320b&t=exs_ftn_download&code=5899c626

**Comment by ireader** [comment]
非常感谢， 测试视频已收到，正在分析中。

**Comment by ireader** [comment]
2017/10/17 Dale Curtis SHA-1: a5fd8aa45b11c10613e6e576033a6b5a16b9cbb9
ffmpeg(libavformat/mov.c)更新了trun box中时间生成方式，对多个trun box的dts/pts计算有问题，
解决办法：fmp4只生成一个trun，以保证兼容ffmpeg及其衍生的媒体库。

**Comment by zhaotao6584851** [comment]
嗯嗯 我把ffmpeg修改了 &nbsp;也可以了 &nbsp; 只是一直没有看邮件 &nbsp;今天看到你有回复 &nbsp;大神👍🏻



------------------ 原始邮件 ------------------
发件人: Chen <notifications@github.com&gt;
发送时间: 2019年12月6日 13:32
收件人: ireader/media-server <media-server@noreply.github.com&gt;
抄送: zhaotao6584851 <244054934@qq.com&gt;, Author <author@noreply.github.com&gt;
主题: 回复：[ireader/media-server] libmov合成的视频用ffplay播放不正常 (#69)




2017/10/17 Dale Curtis SHA-1: a5fd8aa45b11c10613e6e576033a6b5a16b9cbb9
 ffmpeg(libavformat/mov.c)更新了trun box中时间生成方式，对多个trun box的dts/pts计算有问题，
 解决办法：fmp4只生成一个trun，以保证兼容ffmpeg及其衍生的媒体库。
