### ISSUE TITLE
How to use this code for sending H.264 file through RTP over UDP?

### ISSUE THREAD

**Issue by RashmiAD** [ireader/media-server#72]
Hello,

It would be great if you would let me know how to use this library to send H.264 file through RTP over UDP. 
I have checked the rtp-payload-test.cpp file which calls the function
 rtp_payload_test(96, "H264", 12686, 1957754144, "E:\\video\\rtp\\live555-test.h264.rtp", "E:\\video\\rtp\\live555-test.h264");

What does "live555-test.h264.rtp" file mean?
What should be the data for rtpfile?

Hoping for quick response.

Regards,
Rashmi Pulgam

**Comment by ireader** [comment]
rtp_payload_test just use to check librtp generate same rtp packet as live555.  
The input is live555 rtp packet with 2-bytes length prefix, and output is librtp's rtp packet, then binary compare this two file content.
live555-test.h264.rtp: live555 rtp packet file(each packet prefix with 2-bytes length)
live555-test.h264:  h264 nalus decode by librtp

H.264 usage:
- librtsp/test/media/h264-file-source.cpp
- libsip/test/sip-uac-test2.cpp

**Comment by RashmiAD** [comment]
Thank you for the response.
I'm trying with h264-file-source.cpp in my project in the following ways:
    H264FileSource obj_h264filesource = H264FileSource("sample.h264");
    obj_h264filesource.Play();

But the above function call doesn't give the result. As I keep adding the logs I figured out that m_rtp_clock is always 0 and the condition if(m_rtp_clock + 40 < clock) is never true. 
Please let me know where I'm going wrong.

Regards,
Rashmi

**Comment by ireader** [comment]
h264-file-source.cpp is used by rtsp-server-test.cpp(dir: librtsp/test), you can compile and run rtsp_example(). 

set rtsp-server-test.cpp:30  **s_workdir = "/path/to/sample.h264"**

vlc play url: **rtsp://localhost/vod/sample.264**

**Comment by RashmiAD** [comment]
Hi,

Could you please let me know instead of VLC how can I send it to nginx server or Janus(WebRTC) gateway?
Because the rtsp-server-test starts executing when vlc is played but I don't want to use VLC.
Rather I would like to send the packetized H.264 RTP streams to the specified IP address and port through UDP. How can I achieve this?

**Comment by ireader** [comment]
**1. Init h264 rtp encoder:**
```
const char* ip = "peer udp address";
unsigned short port[2] = { peer rtp port, peer rtcp port };
std::shared_ptr<RTPUdpTransport> udp = std::make_shared<RTPUdpTransport>();
int r = udp->Init(ip, port);

H264FileSource* src = new H264FileSource("/path/to/sample.h264");
src->SetTransport("", udp);
```


**2. send rtp packet**
```
while(1)
{
    sleep(5);
    src->Play();
}
```

**Comment by RashmiAD** [comment]
Hi,

Thank you for the response.
I tried the above code and it compiles successfully, but I got the following error

**> test: ../librtsp/test/media/h264-file-source.cpp:209: static void H264FileSource::RTPPacket(void*, const void*, int, uint32_t, int): Assertion `r == (int)bytes' failed.
> Aborted**

Could you please let me know how to resolve it?

**Comment by ireader** [comment]
if r != bytes, that RTPUdpTransport::Send error, make sure udp destination address is correct.

please check RTPUdpTransport::Init function, make sure init return ok.

**Comment by RashmiAD** [comment]
RTPUdpTransport::Init is returning  value -1. 
I have sent the correct IP address as
const char* ip = "10.0.0.9";
unsigned short port[2] = { 8004, 0 };

**Comment by ireader** [comment]
RTPUdpTransport::Init function create & bind socket,  -1 cann't location error reason. 

You can debug it or add printf per line.  

(On Windows should do socket_init() before use any win socket API).

**Comment by RashmiAD** [comment]
I'm working on linux - debian system and trying to make it work on debian stretch flavor.

**Comment by ireader** [comment]
gdb debug program,
break RTPUdpTransport::Init
and step by step, location which line return error

**Comment by RashmiAD** [comment]
![image](https://user-images.githubusercontent.com/31985052/70232334-358f6a00-1782-11ea-99bf-770e6349d4f9.png)

The problem seems to be a sockpair_create(0==r1 ? local : NULL, m_socket, port)
In file sdk/source/sockpair.c:
if (0 != socket_addr_from(&ss, &len, ip, 0 /* placeholder */ ))
		return -1;

It's returning -1 at above point

**Comment by ireader** [comment]
variable ip value seem to be error. 
type: "p ipv4_or_ipv6_or_dns" to see ip value

**Comment by RashmiAD** [comment]
[gdb_librtp_h264_file_through_rtp_over_udp.zip](https://github.com/ireader/media-server/files/3926785/gdb_librtp_h264_file_through_rtp_over_udp.zip)

Please find the above folder which includes the images of gdb.

**Comment by ireader** [comment]
Thank you very much! Base on your screen snapshots,  the problem is ip_route_get in RTPUdpTransport::Init, ip_route_get don't return valid local ip address. 

We can skip ip_route_get function, bind any local address. 
Change code as:
return sockpair_create(0==r1 ? local : NULL, m_socket, port);
==> return sockpair_create(NULL, m_socket, port);

**Comment by RashmiAD** [comment]
I'm getting the same error again.

![image](https://user-images.githubusercontent.com/31985052/70242649-31217c00-1797-11ea-82d1-07c59afd24e4.png)

**Comment by ireader** [comment]
which line of socketpair_create return error？

ping  10.0.0.9 is ok？

**Comment by ireader** [comment]
socket_sendto return -1，please output socket_geterror() to see more error information.

**Comment by RashmiAD** [comment]
> which line of socketpair_create return error？
> 
> ping 10.0.0.9 is ok？

Yes, the ping is successful.

**Comment by RashmiAD** [comment]
> socket_sendto return -1，please output socket_geterror() to see more error information.

![image](https://user-images.githubusercontent.com/31985052/70245925-e0ad1d00-179c-11ea-8cfc-928c939644be.png)

**Comment by ireader** [comment]
errno 101-network-is-unreachable
That's strange. what's ip of that linux device ？Does it has IPv6 address？

u_short p1,p2;
char loca[128];
char remote[128];
socket_getname(m_socket[i],local,&p1);
socket_addr_to((sockaddr*)&m_addr[i], m_addrlen[i],remote,&p2);

add above code toRTPUdpTransport::Send function(before socket_sendto), and output local/remote/p1/p2 value.

**Comment by RashmiAD** [comment]
I'm using a single board computing called HummingBoard like Raspberry pi. 
Isn't it possible to send to same IP address localhost i.e. 127.0.0.1 as the IP address of SBC (HummingBoard) is also 10.0.0.9?
This device is connected to a local LAN network through router.

**Comment by RashmiAD** [comment]
> u_short p1,p2;
> char loca[128];
> char remote[128];
> socket_getname(m_socket[i],local,&p1);
> socket_addr_to((sockaddr*)&m_addr[i], m_addrlen[i],remote,&p2);

![image](https://user-images.githubusercontent.com/31985052/70253346-10622200-17a9-11ea-93eb-a71d2683379c.png)

**Comment by ireader** [comment]
local address is "::1", is a ipv6 address, so we should bind a ipv4 address:

return sockpair_create(0==r1 ? local : NULL, m_socket, port);
==> return sockpair_create("127.0.0.1", m_socket, port);

if it's still return -1， change "127.0.0.1" to linux device ipv4 address(ip addr/ifconfig).

**Comment by RashmiAD** [comment]
Thank you for your quick response and support. It's working!
Could you please explain me how different is this h264 rtp packetization from rtph264pay of gstreamer?

**Comment by ireader** [comment]
sorry,i don't familiar with gstreamer rtph264pay .
if it isn't work proper, could you use tcpdump to capture network packets? like this:
tcpdump -i any udp -w rtp.pcap

librtp only packtize h.264  nalu to rtp packet。It does nothing to delay video.

H264FileSource is a fake source, it load video packets from a local file, send by 25pfs(interval 40ms). So, it maybe send delay.

**Comment by RashmiAD** [comment]
[rtp_2.zip](https://github.com/ireader/media-server/files/3932650/rtp_2.zip)

rtp_1 is a dump of a huge .h264 file so just added starting frames of it.
rtp_2 is a complete dump of .h264 file.

While packetizing is it that the rtp header is added to each frame? Because I'm able to stream only one frame even though it's packetizing and sending complete file through udp.

**Comment by ireader** [comment]
1. rtp_1.zip and rtp_2.zip are identical, which one is capture from g-streamer rtph264pay?

2. one h264 frame will be encode to one or more nalu;
    each nalu will be packetized to one or more udp packets(1436 bytes per udp packet);
    rtp header add to each udp packet.

3. these is timestamp for every h.264 frame,  rtp demuxer use timestamp to recover a full frame.

**Comment by RashmiAD** [comment]
1. The above captured rtp doesn't include gstreamer.
Please find below gstreamer rtp







[rtp_2_gstreamer.zip](https://github.com/ireader/media-server/files/3939116/rtp_2_gstreamer.zip)

**Comment by RashmiAD** [comment]
Could you please let me know what is the difference in gstreamer packets and librtp packets based on the above given pcap files? The streaming doesn't seem to happen properly and stuck at first frame itself.

**Comment by ireader** [comment]
Sorry, i can't find the difference between librtp and gstreamer except the rtp packet timestamp and payload length, but it should be work fine.

gstream:
![image](https://user-images.githubusercontent.com/1535445/70625752-03887700-1c5e-11ea-816b-2e4ad562a423.png)

librtp:
![image](https://user-images.githubusercontent.com/1535445/70625794-23b83600-1c5e-11ea-80a5-e52e7d288681.png)


BTW: each h.264 frame should have difference timestamp, like this:
![image](https://user-images.githubusercontent.com/1535445/70626143-d7b9c100-1c5e-11ea-9aa3-ea4f3f020ebd.png)

**Comment by RashmiAD** [comment]
Hi,
I'm trying to merge this library with my existing code. In my code I get the H264 encoded frame in std::vector<uint8_t>.
1. Could you please let me know how to use this vector in librtsp for RTP packetization and send it over UDP?
2. Also I tried merging the makefiles of my existing code and of media-server/test, but while compiling I'm getting many 'file not found errors' even though I have added the include paths correctly. Is there any quick and simple way to achieve this (eg: by just including .a or .so of whole library in my code)?

**Comment by ireader** [comment]
1. std::vector<uint8_t> not suitable for av frame(miss frame length).  it suggest to define a struct for each frame, at lease you should use std::pair<uint8_t, size_t>, uint8_t for frame data, size_t for frame data size.    Then foreach std::vector<std::pair<uint8_t, size_t>> item, and send it.

2. "file not found" means INCLUDE/SOURCE file path error, please check file path again, make sure use corrent relative path or absolute path.

**Comment by RashmiAD** [comment]
Hi, 
As said I created the struct for each frame. So how can I send this to packetize RTP over UDP using the library?

**Comment by ireader** [comment]
Q1:
![image](https://user-images.githubusercontent.com/1535445/71432497-1480c000-2715-11ea-8b7e-1b3783575f31.png)
Send frame like H264FileSource::Play,  just replace m_reader.GetNextFrame with your frame vecotr/list.  

Q2:
The timestamp of frame should be monotone increasing, like 40ms per frame(25 fps). Please check video source to make sure timestamp correct.

**Comment by RashmiAD** [comment]
Don't we have to modify the parameter of H264FileSource as now we don't need a file since the frames are present in the struct? 
Also the H264FileSource constructor calls H264FileReader where the NALU are figured out and stored in m_vectors, so if we just replace m_reader.GetNextFrame() with the struct for each frame then the Init() of H264FileReader will be missed out without identifying NALU for each frame.

**Comment by RashmiAD** [comment]
Please find the attachment.
[librtsp_test_media.zip](https://github.com/ireader/media-server/files/4030190/librtsp_test_media.zip)

I'm trying to just send the frames which I receive through thread. I have modified the files but getting assertion failure at "payload/rtp-h264-pack.c:196: rtp_h264_pack_input: Assertion `0 < (*p1 & 0x1F) && (*p1 & 0x1F) < 24' failed" .
Is there any better, easy and quick way to achieve this packetization of H.264 frame to RTP?

**Comment by ireader** [comment]
Sorry for the late reply.  

From the code, 264FileReader::Init from user input frame(memory pointer), then H264FileReader::m_videos just save the frame offset pointer, don't copy memory. So, H264FileSource::Play maybe use invalid memory pointer later.

**Comment by RashmiAD** [comment]
Could you please elaborate more on this? I'm unable to understand what you very trying to explain.

**Comment by ireader** [comment]
![image](https://user-images.githubusercontent.com/1535445/72029566-5129eb00-32c1-11ea-98aa-5a6b705a4718.png)
