### ISSUE TITLE
PS解析一帧H264被拆分成多次回调输出

### ISSUE THREAD

**Issue by xiongziliang** [ireader/media-server#75]
ps解析库，貌似存在这种可能性，
就是一帧H264被拆分成多次输出。
我在回调函数里面加了个合帧的操作，就是时间戳一样，就合并成一帧。
否则我的应用逻辑会认为是多帧画面导致花屏。
这是测试ps[文件](https://github.com/ireader/media-server/files/3965949/0000007B.mp2.zip)

**Comment by ireader** [comment]
ps解析264有三种方式：
1. 每个流开始天津AUD，会根据AUD合成帧（这是最标准最通用的方式）
2. 长度设置为0，会根据时间戳合成帧
3. 设置长度，只能根据长度合成帧，不管时间戳

这个测试文件设置了长度，所以走的路径3
