### ISSUE TITLE
如何計算 aac 的 rtp timestamp ?

### ISSUE THREAD

**Issue by givenchyhuang** [ireader/media-server#77]
想參考RTP 封裝 aac frame 時的RTP Timestamp的部分.
我只有原始的 264 和 aac 的資料
264我可以用 90000/fps 來增加視頻 rtp timestamp的部分.
但是我不知道怎麼計算音頻，音頻採樣為 8000HZ.
請問可以提點一下嗎？

**Comment by ireader** [comment]
不清楚你的aac文件存储格式，
1. 如果是mp4之类的封装格式，可以直接读取每帧音频的时间戳pts/dts， 发送rtp包时timestamp = pts * sample-rate / 1000 = pts * 8000 / 1000 = pts * 8
2. 如果是aac裸文件，可以先读7字节adts header，调用mpeg4_aac_adts_frame_length(libflv/include/mpeg4-aac.h)函数获取aac数据长度，timestamp += (1024 * 1000)/ 8000，其中8000是采样率（根据实际情况修改），1024是每帧样本数（AAC固定值，不需要修改）。伪代码如下：
timestamp = 0;
while( !EOF)
{
   file_read_7_bytes(data, 7); // adts header
   n = mpeg4_aac_adts_frame_length(data, y); 
   file_read_n_bytes(data + 7, n - 7); // 注意：n包含了adts header的7字节
   timestamp += 1024 * 1000 / 8000;
   rtp_payload_encode_input(rtp, data, n, timestamp * 8000 / 1000);
}

另外：
RTP封装AAC有两种通用方式：RFC 3640和RFC 6416，sdp生成可以参考ibrtsp/source/sdp/sdp-aac.c，rtp打包可以参考librtp/payload/rtp-mpeg4-generic-pack.c和librtp/payload/rtp-mp4a-latm-pack.c.

**Comment by ireader** [comment]
如果ADTS Header里有PCE，情况会复杂一些，但是一般应该不会遇到。

**Comment by givenchyhuang** [comment]
我的aac是裸文件，會再嘗試代碼，謝囉

**Comment by ireader** [comment]
AAC每帧1024个样本，duration = 1024 * 1000 / 8000 (ms)
对应的每帧时间戳都是 timestamp += duration
rtp时间戳单位是样本数: rtp timestamp += (1024 * 1000 / 8000) * 8000 / 1000，实际上就是每帧样本数1024

**Comment by givenchyhuang** [comment]
但我上網看，有些人提到可以用milliseconds去計算，請問你有經驗嗎？
https://stackoverflow.com/questions/59528090/add-rtp-header-before-aac-adts-header
(Video frames you can go with fps and calculate the interval/timestamp. Audio it is ptime , say for x milliseconds, you need to calculate the buffer time based on the sampling frequency of the Audio)

**Comment by ireader** [comment]
上述的pts/dts时间单位就是ms，rtp时间戳单位是样本(sample)，rtp规范假定H264的视频采样率是90000Hz，aac采样率与实际采样率一致，所以H264的rtp时间戳=pts * 90000Hz / 1000, AAC的rtp时间戳 = pts * 8000Hz / 1000, 其中/1000是将毫秒单位转换成秒。但是本质上rtp时间戳增量就等于每帧音频、视频的样本数。
