### ISSUE TITLE
mpeg4_annexbtomp4 重置avc->nb_pps 和 avc->nb_sps 导致 flv_muxer_avc失败

### ISSUE THREAD

**Issue by illuspas** [ireader/media-server#8]
```
avc->nb_pps = 0;
avc->nb_sps = 0;
```
老陈,这两句应该注释吧,不然每次进来赋0后,后面flv->avc.nb_sps < 1 判断就一直过不去了

**Comment by ireader** [comment]
if (0 == flv->avc_sequence_header)
{
	if (!flv->keyframe || flv->avc.nb_sps < 1 || flv->avc.sps[0].bytes < 4)
		return 0;
        ....
}

flv->avc_sequence_header标记用于表示是否生成了FLV AVC sequence header, 也就是AVCDecoderConfigurationRecord。 

ISO 14496-15, 5.2.4.1描述了AVCDecoderConfigurationRecord结构的数据格式，其中主要包含profile/level/SPS/PPS.  所以随后的if中才有对flv->avc.nb_sps值的检查。

flv_muxer_avc要求的输入格式是H.264 Annex B描述的流格式，并且必须包含SPS/PPS nalu。你的输入流是否一直没有SPS/PPS？如果可以的话可以给我一份裸流测试。

**Comment by illuspas** [comment]
哦对了,数据流是这样的
sps,pps,keyframe分3次传入,就会触发这个情况

**Comment by ireader** [comment]
一般来说 sps/pps这种non-VCL数据应该与VCL数据一起输入。

可以判断一下nal_unit_type，如果nal_unit_type >= 1 && nal_unit_type <= 5就可以认为是正常视频数据，其它值可以等到VCL一起输入。

**Comment by illuspas** [comment]
我这儿环境是hi3516,编码后的数据回调它就没有给合在一起, 在flv_muxer_avc里做兼容逻辑更简单些
libsrsrtmp是支持这种处理的,但我测试发现他这个性能太差,2M多的码率在hi3516上要用掉25% CPU

**Comment by ireader** [comment]
flv_muxer_avc里内部处理也是可以的，只是设计时考虑把flv_muxer功能做得更纯粹一点。

有分析过libsrsrtmp CPU高的原因吗？ 从代码来看libsrsrtmp逻辑也是很简单，没有特别费cpu的地方，是不是数据拷贝导致的CPU高？

**Comment by illuspas** [comment]
我正准备编译gprof看看

**Comment by illuspas** [comment]
经过分析,srs和您这个库,最费时的函数都是查找 h.264 start_code,
码率越大越耗时,其实大部分时候都是浪费了

**Comment by ireader** [comment]
flv_muxer_avc可以不调用，按照flv_muxer_avc直接封装成FLV格式就可以了。 查找start code确实没有必要，而且flv_muxer_avc多拷贝了一次。

**Comment by illuspas** [comment]
好的,感谢指导

**Comment by ireader** [comment]
新增了flv_muxer_h264_nalu函数解决此问题，对sps和pps的处理有些硬编码。
