### ISSUE TITLE
能支持gb28181流接收吗？

### ISSUE THREAD

**Issue by wanstonq** [ireader/media-server#80]
ts over rtp

**Comment by ireader** [comment]
28181应该是ps over rtp？ librtp是支持的。

libsip/test目录下sip-uac-test.cpp有简单的28181测试代码。

**Comment by wanstonq** [comment]
> 28181应该是ps over rtp？ librtp是支持的。
> 
> libsip/test目录下sip-uac-test.cpp有简单的28181测试代码。

谢谢！我看下

**Comment by wanstonq** [comment]
librtp 可以解端口复用的RTP流吗？在H.460.19中定义，就是音视频同一个端口，两个不同的rtpid加以区分

**Comment by ireader** [comment]
> 
> 
> librtp 可以解端口复用的RTP流吗？在H.460.19中定义，就是音视频同一个端口，两个不同的rtpid加以区分

 这个还没有实现

**Comment by ireader** [comment]
上层接收udp包后，先摘掉下4-byte multiplexID，然后再解析下rtp payload type，根据不同的payload调用相应的rtp demux。

**Comment by ireader** [comment]
相关参考文档：

- https://www.itu.int/rec/T-REC-H.460.19-201303-I/en
- https://tools.ietf.org/html/rfc5761

**Comment by wanstonq** [comment]
谢谢！
