### ISSUE TITLE
udp发送TS音频+视频流 卡顿

### ISSUE THREAD

**Issue by hh-kai** [ireader/media-server#82]
音视频同时发送就会很卡顿
单独发送音频或者单独发送视频 都很流畅
init_ts_ctx(ts_ctx)
v_pid = mpeg_ts_add_stream(H264/H265)
a_pid = mpeg_ts_add_stream(AAC)

venc_thd()
{
    while(1)
    {
        lock(ts_mtx);
        mpeg_ts_write(ts_ctx, v_pid, 0, timestamp*90, timestamp*90, data, size);
        unlock(ts_mtx);
    }
}

aenc_thd()
{
    while(1)
    {
        lock(ts_mtx);
        mpeg_ts_write(ts_ctx, a_pid, 0, timestamp*90, timestamp*90, data, size);
        unlock(ts_mtx);
    }
}
上面的timestamp均使用系统当前时间ms

试过vlc 3.0.3    ffmpeg4.0.1    potplayer1.7.8 都会出现卡顿

ffmpeg播放的部分截图
![批注 2020-04-02 163357](https://user-images.githubusercontent.com/19390025/78227543-fe4a8300-74ff-11ea-9fa3-d97dac3e3761.jpg)

**Comment by ireader** [comment]
从ffmpeg打印信息看是丢包，不清楚哪个环节有丢包，音视频ts mux时有加锁，应该不是同步问题，有没有试过将mpeg_ts_write之后的数据保存一份到本地？

**Comment by ireader** [comment]
先确认下保存到本地的数据是否可以正常播放。 方便的话可以贴下发送部分的代码。

**Comment by hh-kai** [comment]
保存到文件是正常的

发送的部分
typedef struct _TS_HANDLER_S_
{
	uint8_t 		tsBuffer[188]; // ts 一个包 固定188大小
	int 		tsBufferPos;
	uint8_t 		rtpBuffer[1500];
	int 		rtpBufferPos;
	int 		tsPktCount;

	int 		ts_v_pid;
	int 		ts_a_pid;
	
	void *pSender;
} TS_HANDLER_T;

mpeg内部的回调函数 初始化时已经指定了


static void *ts_alloc(void *param, size_t bytes)
{

	TS_HANDLER_T *handler = (TS_HANDLER_T  *)param;
	return handler->tsBuffer;
}

static void ts_free(void *param, void *packet)
{
	return ;
}

static void ts_write(void *param, const  void *packet, size_t bytes)
{
TS_HANDLER_T *handler = (TS_HANDLER_T *)param;
if (handler && handler->pCtx)
{
	if (handler->tsPktCount < 7)
	{
		memcpy(handler->rtpBuffer + handler->rtpBufferPos, packet, bytes);
		handler->rtpBufferPos += bytes;
		handler->tsPktCount ++;

		if (handler->tsPktCount == 7)
		{
			send(handler->pSender, handler->rtpBuffer, handler->rtpBufferPos);  // udp发送函数
			handler->tsPktCount = 0;
			handler->rtpBufferPos = 0;
			memset(handler->rtpBuffer, 0, 1500);
		}
		
	}
}
}

**Comment by ireader** [comment]
组7个ts包一起发送？ 看着没什么问题。

是推流到服务端吗？试着把服务端的接收udp socket buffer调大点试试。 

如果还有问题，再试试使用tcp发送。

**Comment by ireader** [comment]
也可以在接收端起个wireshark/tcpdump命令转包，然后把ts数据dump出来。

**Comment by hh-kai** [comment]
是直接通过UDP组播发送出来 udp://@xx.xxx.xx.xx:10000 这样的形式老播放

**Comment by hh-kai** [comment]
[test.zip](https://github.com/ireader/media-server/files/4420669/test.zip)
这是wire抓包保存的一段ts码流 文件播放会卡 但是发送端单独保存的音视频的正常的

**Comment by ireader** [comment]
确实很奇怪，帮忙做两件事情：

**Comment by hh-kai** [comment]
1. 
>> ffmpeg -f mpegts -i udp://228.228.2.12:20000?pkt_size=188 2> test.txt
[test2.zip](https://github.com/ireader/media-server/files/4424591/test2.zip)
buffer_size 无法识别所以去掉了
2. 上面的test.zip里面的ts文件 就是播放的wire抓包后wire保存的原始数据（分析->追踪流->UDP流)
3. 播放过程中 声音还会会变调 很奇怪 同一个线程出来的rtsp码流声音视频都是正常的
 rtsp发送流程同上面是一样的 在发送完ts音视频流后也分别发送rtsp的音视频流
4. 从ffmpeg日志里面看 没有pps 但是原始码流是有完整的spspps

**Comment by ireader** [comment]
1.  ffmpeg -i input -f mpegts "udp://hostname:port?pkt_size=188&buffer_size=65535"  url里有&号，需要加引号，&在linux命令行有特殊含义。

2/3. ffmpeg打印：Continuity check failed for pid 257 expected 13 got 14，说明test.zip里有丢包，而且只丢了一个ts包(188)字节，这是不正常的，如果是udp丢包，根据你的代码至少会丢8个ts包。可以看看send(handler->pSender, handler->rtpBuffer, handler->rtpBufferPos)这个函数，首先确认sendto返回的数据长度是否等于buffer长度，其次确认下是否设置了非阻塞udp。正常情况下udp发送不会阻塞，但是确实有udp发送会阻塞的情况，如果设置了non-block，可能会导致发送丢数据。

4. ffplay播放时出现non-existing PPS 0 referenced没关系，因为播放时不是从IDR帧开始的，后续收到I帧就不会出现这个错误了。

**Comment by hh-kai** [comment]
1. 我修改了编码参数 由原来的1920x1080@60 8000kbps 到 1024x768@25 2000kbps
卡顿明显减少 但是还会有 
2. 
[test3.zip](https://github.com/ireader/media-server/files/4424822/test3.zip)
这是加了buffer_size的日志
3. 通过下面的方式 设置为nonblock
int flags = fcntl(sock, F_GETFL, 0);
fcntl(sock, F_SETFL, flags|O_NONBLOCK);
4. udp发送和发送返回的长度相同 没有出现不同的情况

**Comment by hh-kai** [comment]
这是ffplay播放时的日志 1024x765@25 2000kbps
ffplay -i input -f mpegts "udp://hostname:port?pkt_size=188&buffer_size=65535"
[播放日志.zip](https://github.com/ireader/media-server/files/4424847/default.zip)
这期间的视频没有明显卡顿  声音出现一次卡顿变调
后面换1080p的编码 画面不卡顿 
同时对比了 vlc和ffmpeg播放 发现vlc卡顿的时候 ffmpeg并不卡顿 但是ffmpeg播放的声音会变调和有嘶哑的杂音  而且后面会一直有 但是rtsp长时间播放 声音正常

**Comment by hh-kai** [comment]
后面通过调试 发现 send部分 会出现 发送超出1500的大小 类似于 send 1504，send ok 1316 会丢一个包  这样的问题 应该是这里导致的问题

**Comment by ireader** [comment]
send为什么会有超过1316的呢？之前的数据没有发完吗？

这里有篇文章是介绍查看udp丢包的
[https://ref.onixs.biz/lost-multicast-packets-troubleshooting.html](https://ref.onixs.biz/lost-multicast-packets-troubleshooting.html)

**Comment by hh-kai** [comment]
应该是组包的时候 多组了一个包 send的时候没有注意

**Comment by hh-kai** [comment]
发现如果只单独发送视频 就不会出现 类似于 send 1504，send ok 1316 这样的问题
而且 单独发送视频也会偶有卡顿 不注意很难发现

**Comment by ireader** [comment]
send 1504是不是tsPktCount没有加锁？

udp发包尽可能组包，越大越好。

**Comment by hh-kai** [comment]
在调用mpeg_ts_write 不是已经加锁了吗? 
使用mpeg_ts_write传入一帧数据 直到全部打包好再返回
比如一帧1880大小 ts_write会调用10次之后再返回

**Comment by ireader** [comment]
if (handler->tsPktCount == 7)
{
send(handler->pSender, handler->rtpBuffer, handler->rtpBufferPos); // udp发送函数
handler->tsPktCount = 0;
handler->rtpBufferPos = 0;
memset(handler->rtpBuffer, 0, 1500);
}

不是每7个包就发送一次？

**Comment by hh-kai** [comment]
对 是每7个包发送一次

**Comment by ireader** [comment]
> 在调用mpeg_ts_write 不是已经加锁了吗?
> 使用mpeg_ts_write传入一帧数据 直到全部打包好再返回
> 比如一帧1880大小 ts_write会调用10次之后再返回



> 后面通过调试 发现 send部分 会出现 发送超出1500的大小 类似于 send 1504，send ok 1316 会丢一个包 这样的问题 应该是这里导致的问题


上面两段是矛盾的。

**Comment by ireader** [comment]
UDP组播丢包好像比较厉害，试试普通udp发送试试？

**Comment by hh-kai** [comment]
试过很低分辨率 码率也特别低的 也会有同样的问题
我之前试过自定义的rtp组包 组播发送 几乎不丢包
我试试把文件保存下来看看

**Comment by ireader** [comment]
能不能把代码简化下，上传测试代码我试试能否复现。正常来说小码率不应该会丢包。

**Comment by hh-kai** [comment]
好 我是准备这样做 过几天我传上来

**Comment by hh-kai** [comment]
测试工程已经发到你的邮箱了  这里传不了大文件

**Comment by ireader** [comment]
> 
> 
> 测试工程已经发到你的邮箱了 这里传不了大文件

非常感谢，邮件暂未收到，稍后我再试试。

**Comment by ireader** [comment]
Wireshark 导出原始TS数据：

![image](https://user-images.githubusercontent.com/1535445/80327297-31b5ce80-886e-11ea-81ea-84570eb3f05a.png)

![image](https://user-images.githubusercontent.com/1535445/80327306-3b3f3680-886e-11ea-849c-ac701a5b9b52.png)

**Comment by hh-kai** [comment]
验证过 确实是trylock非阻塞导致数据没有发送出去 换成lock就没问题了
