### ISSUE TITLE
RTP packet re-transmission in case of packet loss 

### ISSUE THREAD

**Issue by sgandiga** [ireader/media-server#83]
Does this RTP implementation perform re-transmission in case of packets lost based on the receiver report?    Thanks.

**Comment by ireader** [comment]
no, librtp don't re-transmission lost packets. RTP isn't a reliable protocol, 

[rfc 4585 RTP/AVPF](https://tools.ietf.org/html/rfc4585) NACK/PLI don't implemention yet,  maybe in Aug.
