### ISSUE TITLE
libsip编译失败

### ISSUE THREAD

**Issue by kqbi** [ireader/media-server#84]
在linux上直接make没成功
![图片](https://user-images.githubusercontent.com/40823194/79047816-a91f1780-7c4b-11ea-86d0-eef0fa4bf9b7.png)
![图片](https://user-images.githubusercontent.com/40823194/79047821-ad4b3500-7c4b-11ea-9920-cf7e47af0e6a.png)
应该是这两个缺失

**Comment by ireader** [comment]
libsip编译依赖https://github.com/ireader/sdk 下载到media-server平级目录下，目录结构如下：
/
|---media-server
|---sdk

**Comment by kqbi** [comment]
编译成功，谢谢大佬了
