### ISSUE TITLE
libsip的使用

### ISSUE THREAD

**Issue by kqbi** [ireader/media-server#85]
libsip编译成库，在用C++调用的时候
![图片](https://user-images.githubusercontent.com/40823194/79068582-9a436e00-7cfa-11ea-8a32-d11160cb300b.png)
![图片](https://user-images.githubusercontent.com/40823194/79068583-9e6f8b80-7cfa-11ea-85a1-3a6ea018a94b.png)

**Comment by ireader** [comment]
link加libsip库了吗？

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/79068946-1c349680-7cfd-11ea-9ca4-7a71b6d8ddf2.png)

**Comment by kqbi** [comment]
好像知道问题出哪了

**Comment by kqbi** [comment]
![图片](https://user-images.githubusercontent.com/40823194/79085652-f7c3d300-7d6b-11ea-93a0-cd872bf33419.png)
![图片](https://user-images.githubusercontent.com/40823194/79085679-0f9b5700-7d6c-11ea-9de9-60dfdab7a9c4.png)
依赖有点多，win下MT不行只能MD

**Comment by ireader** [comment]
> ![图片](https://user-images.githubusercontent.com/40823194/79085652-f7c3d300-7d6b-11ea-93a0-cd872bf33419.png)
> ![图片](https://user-images.githubusercontent.com/40823194/79085679-0f9b5700-7d6c-11ea-9de9-60dfdab7a9c4.png)
> 依赖有点多，win下MT不行只能MD

依赖文件确实比较多，编译可以参考VS项目文件或者Makefile。

欢迎多提意见！
