### ISSUE TITLE
ts over rtp suggestion

### ISSUE THREAD

**Issue by alexwangf** [ireader/media-server#86]
a. mark of rtp stands of frame end.
b. fix a frame delay

1. librtp/playload/rtp-ts-unpack.c
   /* if (pkt.rtp.m)
	{
		//TODO: test
		// new frame start
		helper->size = 0; // discard previous packets
		helper->lost = 0;
		helper->flags |= RTP_PAYLOAD_FLAG_PACKET_LOST; // notify source changed
		helper->seq = (uint16_t)pkt.rtp.seq;
		helper->timestamp = pkt.rtp.timestamp;
	}
	else
	{
		rtp_payload_check(helper, &pkt);
	} */
	ret = rtp_payload_check(helper, &pkt);

2. librtp/playload/rtp-payload-helper.c
   int rtp_payload_check(struct rtp_payload_helper_t* helper, const struct rtp_packet_t* pkt)
{
	int ret = 0;
	// first packet only
	if (-1 == helper->flags)
	{
		helper->flags = 0;
		helper->seq = (uint16_t)(pkt->rtp.seq - 1); // disable packet lost
		helper->timestamp = pkt->rtp.timestamp + 1; // flag for new frame
	}

	// check sequence number
	if ((uint16_t)pkt->rtp.seq != (uint16_t)(helper->seq + 1))
	{
		helper->size = 0;
		helper->lost = 1;
		helper->flags |= RTP_PAYLOAD_FLAG_PACKET_LOST;
		helper->timestamp = pkt->rtp.timestamp;
	}
	helper->seq = (uint16_t)pkt->rtp.seq;

	// check timestamp
	if (pkt->rtp.timestamp != helper->timestamp)
	{
		rtp_payload_onframe(helper);
		
	}else if(helper->lost != 1){
		if (pkt->rtp.m)
		{
			// the frame end. so decode now
			rtp_payload_write(helper, pkt);
			rtp_payload_onframe(helper);
			ret = 1;
			
		}
		
	}
	helper->timestamp = pkt->rtp.timestamp;

	return ret;//0;
}

**Comment by ireader** [comment]
Look at  RFC2250 2.1 RTP header usage
M bit: Set to 1 whenever the timestamp is discontinuous. (such as  might happen when a sender switches from one data source to another).This allows the receiver and any intervening RTP mixers or translators that are synchronizing to the flow to ignore the difference between this timestamp and any previous timestamp in their clock phase detectors.

IN TS OVER RTP, M bit don't mean frame end!!!

**Comment by alexwangf** [comment]
refer to RFC3550
 marker (M): 1 bit
      The interpretation of the marker is defined by a profile.  It is
      intended to allow significant events such as frame boundaries to
      be marked in the packet stream.  A profile MAY define additional
      marker bits or specify that there is no marker bit by changing the
      number of bits in the payload type field (see Section 5.3).

     When i get ts stream by demux rtp stream(from miracast protocol by android phone),i get wrong ts stream. besides that,if not fix it,a frame delay will produce. when the android phone is motionless，the video decode could not get the first video frame.The screen（run librtp） will balck.
     I'm not familiar with player.   Just suggestion..

**Comment by alexwangf** [comment]
refer to RFC3550
marker (M): 1 bit
      The interpretation of the marker is defined by a profile. It is
intended to allow significant events such as frame boundaries to
be marked in the packet stream. A profile MAY define additional
marker bits or specify that there is no marker bit by changing the
number of bits in the payload type field (see Section 5.3).

      When i get ts stream by demux rtp stream(from miracast protocol by android phone),i get wrong ts stream. besides that,if not fix it,a frame delay will produce. when the android phone is motionless，the video decode could not get the first video frame.The screen（run librtp） will balck.
     I'm not familiar with player.   Just suggestion..

**Comment by ireader** [comment]
> When i get ts stream by demux rtp stream(from miracast protocol by android phone),i get wrong ts stream. 

What's wrong ? Could you upload a test bit stream file, or wireshark pcap file?

> besides that,if not fix it,a frame delay will produce. when the android phone is motionless，the video decode could not get the first video frame.The screen（run librtp） will balck.

Yes, these is a frame delay, becase frame boundary check by timestamp.
