### ISSUE TITLE
sps问题导致srs解析失败，异常关闭

### ISSUE THREAD

**Issue by ht101996** [ireader/media-server#87]
static int h264_sps_copy(struct h264_annexbtomp4_handle_t* mp4, const uint8_t* nalu, int bytes)
{
	int i;
	int offset;
    uint8_t spsid;

	if (bytes < 4 + 1)
	{
		assert(0);
		mp4->errcode = -1;
		return -1; // invalid length
	}

	offset = 4 * 8; // 1-NALU + 3-profile+flags+level
	spsid = mpeg4_h264_read_ue(nalu, bytes, &offset);

	for (i = 0; i < mp4->avc->nb_sps; i++)
	{
		offset = 4 * 8; // reset offset
		if (spsid == mpeg4_h264_read_ue(mp4->avc->sps[i].data, mp4->avc->sps[i].bytes, &offset))
		{
			if (bytes == mp4->avc->sps[i].bytes && 0 == memcmp(nalu, mp4->avc->sps[i].data, bytes))
				return 0; // do nothing

			if (bytes > mp4->avc->sps[i].bytes && mp4->avcptr + (bytes - mp4->avc->sps[i].bytes) > mp4->avc->data + sizeof(mp4->avc->data))
			{
				assert(0);
				mp4->errcode = -1;
				return -1; // too big
			}

			mpeg4_avc_remove(mp4->avc, mp4->avc->sps[i].data, mp4->avc->sps[i].bytes, mp4->avcptr);
			mp4->avcptr -= mp4->avc->sps[i].bytes;

			if (mp4->update) *mp4->update = 1; // set update flag
			mp4->avc->sps[i].data = mp4->avcptr;
			mp4->avc->sps[i].bytes = (uint16_t)bytes;
			memcpy(mp4->avcptr, nalu, bytes);
			mp4->avcptr += bytes;
			return 0;
		}
	}

	// copy new
	assert(mp4->avc->nb_sps < sizeof(mp4->avc->sps) / sizeof(mp4->avc->sps[0]));
	if (mp4->avc->nb_sps >= sizeof(mp4->avc->sps) / sizeof(mp4->avc->sps[0])
		|| mp4->avcptr + bytes > mp4->avc->data + sizeof(mp4->avc->data))
	{
		assert(0);
		mp4->errcode = -1;
		return -1;
	}

	if (mp4->update) *mp4->update = 1; // set update flag
	mp4->avc->sps[mp4->avc->nb_sps].data = mp4->avcptr;
	mp4->avc->sps[mp4->avc->nb_sps].bytes = (uint16_t)bytes;
	memcpy(mp4->avcptr, nalu, bytes);
	mp4->avcptr += bytes;
	++mp4->avc->nb_sps;
	return 0;
}

陈哥，上面的 ++mp4->avc->nb_sps;   这个操作目的是啥? 这里的sps问题会导致srs下面这个地方报错，同时也会使ffmpeg报 “SPS decoding failure, trying again after escaping the NAL” 这个错误。

`````SRS代码```````````````
 int8_t numOfSequenceParameterSets = stream->read_1bytes();
    numOfSequenceParameterSets &= 0x1f;
    if (numOfSequenceParameterSets != 1) {
        return srs_error_new(ERROR_HLS_DECODE_ERROR, "decode SPS");
    }
`````````````````````````````

**Comment by ht101996** [comment]
这个是有问题的文件
[failed.flv.zip](https://github.com/ireader/media-server/files/4542790/failed.flv.zip)

**Comment by ireader** [comment]
mp4->avc->nb_sps是统计流中sps个数，在h264_sps_copy中会判断sps与之前的sps ID是否相同，如果相同，则会替换原来的sps。
在你的failed.flv测试文件中，有两种sps，且id及内容各不相同，所以会走到nb_sps++逻辑。

两处sps数据如下：
![image](https://user-images.githubusercontent.com/1535445/80436734-65f2c300-8932-11ea-89d9-8197454cd4da.png)


![image](https://user-images.githubusercontent.com/1535445/80436708-56737a00-8932-11ea-8d8b-eedbf8e95ef3.png)

**Comment by ireader** [comment]
另外从failed.flv文件看，数据也有点问题，第二次的sps数据 0000 0001 67d8应该是数据有问题的，可以查一下输入源是不是有错误。
