### ISSUE TITLE
RTSP tcp连接 onerror 110

### ISSUE THREAD

**Issue by Jddl** [ireader/media-server#88]
用VLC测试RTSP server的时候，总是在连接10s左右 出现error code为110

**Comment by Jddl** [comment]
![image](https://user-images.githubusercontent.com/11550798/80562523-94e46400-8a1a-11ea-8738-464765718e37.png)

**Comment by Jddl** [comment]
应该是20s

**Comment by ireader** [comment]
这个错误信息是rtsp的tcp链接一直空闲导致的。如果使用udp传输数据，rtsp的tcp链接就空闲了，内部的定时器会产生回调，打印一条110（ETIMEOUT）错误信息，这个可以忽略。

**Comment by Jddl** [comment]
忽略是没问题，但是VLC再发送控制指令就不行了，tcp被destroy了。然后相机端就有个session关不掉了 ，好尴尬呀

**Comment by ireader** [comment]
vlc有重连功能，关闭时可以正常进入rtsp的onteardown过程。

rtsp本身并没有要求tcp是长链接，rtsp-server-tcp.c中默认超时20s，可以修改TIMEOUT_RECV值，改为60s。

**Comment by Jddl** [comment]
大大的赞！
