### ISSUE TITLE
strange behavior in librtsp/test/media/mp4-file-source.cpp?

### ISSUE THREAD

**Issue by smg31** [ireader/media-server#89]
Hi, I'm quite new to open source software. The other day I found this software and started to play with it. Your great work would be really appreciated.

I'm now running your software using Ubuntu under WSL (Windows Subsystem for Linux).

When I enabled your test program of rtsp_example(), it worked fine for me using your 25th/Apr, 2020 revision. However when I attempted the same using the latest commit (4th/May, 2020), I observed that something seemed to be wrong in the H.264 RTP packets.

So when I took a look at which changes might have affected, I came across the following changes in libflv/source/mpeg4-avc.c.

```
diff --git a/libflv/source/mpeg4-avc.c b/libflv/source/mpeg4-avc.c
index e370126..a5cb8f5 100644
--- a/libflv/source/mpeg4-avc.c
+++ b/libflv/source/mpeg4-avc.c
@@ -107,6 +107,7 @@ int mpeg4_avc_decoder_configuration_record_load(const uint8_t* data, size_t byte
         p += len;
        }

+       avc->off = p - avc->data;
        return j;
 }
```

May I ask you to check whether this is valid change, please? I confirmed that rtsp_example() worked well again after I commented out the above change.

BTW, I also found that your latest changes broke "make test" target build. It would be appreciated you could also address this point.

Best regards,
smg31

**Comment by ireader** [comment]
Sorry, it work fine for me local test. Could you show me the error message?  Or, upload your mp4 file?

**Comment by ireader** [comment]
> BTW, I also found that your latest changes broke "make test" target build.

Thanks for your feedback!

**Comment by smg31** [comment]
When I once again tried the same thing, I could no longer observe the strange behavior..., It originally demonstrated H.264 decode error (greenish video) at the beginning of the movie play... Perhaps it might have been due to my network environment..

Sorry to trouble you.

**Comment by ireader** [comment]
> It originally demonstrated H.264 decode error (greenish video) at the beginning of the movie play...

It could be a problem sending RTCP packages. Try to comment below code in MP4FileSource::SendRTCP

![image](https://user-images.githubusercontent.com/1535445/81479457-cb5d8280-9255-11ea-9505-b571350636b0.png)

**Comment by smg31** [comment]
Thank you for your feedback.

Anyway I think you can close this issue ticket since what I reported doesn't quite make sense since I no longer be able to reproduce the issue in my end...
