### ISSUE TITLE
sip register时，两个参数需要单独设置

### ISSUE THREAD

**Issue by wanstonq** [ireader/media-server#90]
auth.qop="auth"
auth.cnonce=“0a4f113b”
auth.algorithm="MD5"

调用http_header_auth前

**Comment by ireader** [comment]
不明白你的意思，请把上下文描述清楚。

**Comment by wanstonq** [comment]
struct http_header_www_authenticate_t auth;
memset(&auth, 0, sizeof(auth));
http_header_www_authenticate(www_authenticate, &auth);

http_header_www_authenticate解析出的auth，三个参数是空字符串
再通过http_header_auth生成response，会导致注册认证失败。

**Comment by ireader** [comment]
明白了，这种情况是服务端没有返回auth算法。不知道服务端是什么软件，如果服务端需要认证，一般应该是需要返回algorithm和nonce字段。

**Comment by wanstonq** [comment]
服务器返回的字段：
WWW-Authenticate: Digest realm="3402000000",qop="auth,auth-int",nonce="779ea8cdda68815cc6a56a1ab785361f"

**Comment by ireader** [comment]
回头我处理下吧，默认algorithm是MD5，qop选择auth。
感谢反馈
