### ISSUE TITLE
RTSP随机出现马赛克，花屏

### ISSUE THREAD

**Issue by Jddl** [ireader/media-server#91]
特别是I帧，画面变化大的时候，是I帧过大吗

**Comment by Jddl** [comment]
![image](https://user-images.githubusercontent.com/11550798/83497388-fe113880-a4ec-11ea-914b-896eaa61bb63.png)
这个是海思sdk里的rtsp拉流
![image](https://user-images.githubusercontent.com/11550798/83497431-0f5a4500-a4ed-11ea-9e02-40f1baab7c4d.png)
这个是基于librtp,librtsp的拉流

**Comment by Jddl** [comment]
并不是丢包引起的，抓包来看，序列都是正常的

**Comment by ireader** [comment]
udp socket recv buffer设置的多大？ 如果是高清流，I帧数据比较大，udp 接收慢会导致丢数据。可以通过SO_RCVBUF选项配置大一点的缓冲区。

**Comment by Jddl** [comment]
我可能描述的不是很对啊，我是用3559打包的rtp，确实是高清流，4k的，然后是vlc播放，在vlc播放的时候抓包。从抓包看，序列都是连续的。所以不是丢包引起的，在想是不是时间戳不对，或者是缓冲的问题，另外rtp打包的时候，发现I桢附近，会有4个字节的小包，这个正常吗？

**Comment by ireader** [comment]
1. 不确定4字节小包是什么，可以截图看看内容。

2. 一般内网不会丢包，数据包会正常发送到接收端的协议栈里（这是wireshark看没有丢包的原因，因为确实收到了），但是如果你的接收程序调用recvfrom慢了，内核协议栈的buffer空间有限，新的数据包到来时内核会丢包。 所以你可以尝试下设置socket option，把SO_RCVBUF值设置大一点（比如4M/8M）

**Comment by Jddl** [comment]
对比了一下，好像是把某个P帧丢掉了，但是序列是连续的。本来怀疑是缓冲队列造成的，可是不用缓冲，也会有这样的情况，好奇怪的

**Comment by ireader** [comment]
1. SO_RCVBUF值设置的多少？ 
2. 接收数据不做任何处理，只打印rtp包号，确认下接收的rtp包有没有不连续。

**Comment by Jddl** [comment]
我是rtsp server，所以应该和SO_RCVBUF没关系的。像是某一帧没传到librtp里

**Comment by ireader** [comment]
把传入到librtp之前的数据在本地存一份，4字节长度+数据内容

librtp输入的rtp包也保存一份，同样4字节长度+rtp包内容

二进制模式保存

**Comment by Jddl** [comment]
确认是传入librtp之前丢掉的数据。
谢谢 老陈！
