### ISSUE TITLE
librtsp 支持双向对讲吗

### ISSUE THREAD

**Issue by Jddl** [ireader/media-server#96]
void (*onrtp)(void* param, uint8_t channel, const void* data, uint16_t bytes);

onrtp 是不是可以接收客户端的语音？

**Comment by ireader** [comment]
rtsp是单向的，要么拉流，要么推流。真正的双向对讲，需要用sip协商。

sip对讲可以参考libsip/test目录下sip-uas-test2.cpp和sip-uac-test2.cpp。
sip-uas-test2.cpp可以用android手机自带的sip电话测试。在手机里配置sip服务器为你的ip地址，拨打sip电话既可以双向对讲（本地播放的一段pcm文件）。

ip-uac-test2.cpp更复杂一些，里面包含了ice打洞部分，相对功能完善一点。

**Comment by Jddl** [comment]
海康的平台可以接入ONVIF协议的摄像头，平台有对讲功能。
那对讲是通过RTSP实现的吗？还是SIP或者自定义协议

**Comment by ireader** [comment]
抓包看看？
