### ISSUE TITLE
LINK : fatal error LNK1104: 无法打开文件“avcodec.lib” 错误

### ISSUE THREAD

**Issue by Hoke** [ireader/media-server#97]
下载最新master分支的代码，在window10 visual studio2017 环境，
出现错误：LINK : fatal error LNK1104: 无法打开文件“avcodec.lib”

**Comment by ireader** [comment]
可以删除avcodec.lib相关的库，不依赖ffmpeg。

应该是在test工程的link项里

**Comment by Hoke** [comment]
可以了，谢谢
